export class NewAccountPageConstant {

    static get elementNames() {
        return {
            newAccount: 'New Account',
            information: 'Information',
            productDetails: 'Product Details',
            inside: 'Inside',
            outside: 'Outside',
            product: 'Product',
            owner: 'Owner',
            status: 'Status',
            acct: 'Acct',
            contentIFrame: 'contentIFrame',
            description: 'Description',
            created: 'Created',
            forecast: 'Forecast',
            fundsSource: 'FundsSource',
            referralSource: 'ReferralSource',
            calendarIcon: 'CalendarIcon',
            clockIcon: 'ClockIcon',
            calenderDateOutOfRange: 'CalenderDate OutOfRange',
            calenderDateInRange: 'CalenderDate InRange',
            time: 'Time',
            save: 'Save',
            saveAndClose: 'saveAndClose',
            close: 'close',
            calendarPopUp: 'ClockIcon',
            timePicker: 'Time Picker',
            overView: 'Overview',
            contactRequired: 'CONTACT is required.',
            accNumberRequired: 'Account number is required.',
            openedAccount: 'Opened Account',
            closedAccount: 'Closed Account',
            brokerage: 'BROKERAGE',
            commercialChecking: 'COMMERCIAL CHECKING',
            creditCard: 'CREDITCARD',
            mutualFunds: 'MUTUAL FUNDS',
            ok: 'OK',
            cancel: 'Cancel',
            confirmDialog: 'Confirm Dialog',
            callCenter: 'Call Center',
            conventions: 'Conventions',
            directMail: 'Direct Mail',
            emailLead: 'Email lead',
            confirmDialogTitle: 'Confirm Dialog Title',
            searchContact: 'Search Contact',
            household: 'Household',
            noProductSelected: 'no product is selected.',
            name: 'Name',
            email: 'Email',
            phone: 'Phone',
            potentialInvestment: 'Potential Investment',
        };
    }

    static get attributes() {
        return {
            classes: {
                subSection: 'sub-section',
                iconCalendar: 'icon-calendar',
                clockIcon: 'clockIcon',
                rcOtherMonth: 'rcOtherMonth',
                iconSave: 'icon-save',
                iconAdd: 'icon-add',
                iconClose: 'icon-close',
                calendarPopUp: 'RadCalendar',
                timePopUp: 'RadCalendarTimeView',
                cellNavigation: 'cell-navigation',
                cellContents: 'cell-contents',
                tabStrip: 'tabstrip',
                uiDialogTitle: 'ui-dialog-title',
                uiDialogButtonSet: 'ui-dialog-buttonset',
                gridCheckBox: 'gridCheckBox',
                displayName: 'display-name',
                entityInfo: 'entity-info',
                headerLabel: 'header-label',
                phone: 'phone',
                iconMandatory: 'icon-mandatory',
            },
            name: {
                accountDetailsControl: 'accountdetails_control',
                productTypeSelector: 'productTypeSelector',
                activityStatusDD: 'activitystatusdd',
                externalKeyID: 'externalKeyID',
                dateInput: '$dateInput',
                outsideBusinessControl: 'outside_business_control',
                referralSourceIdControl: 'referral_source_id_control',
                selectProductSelector: 'selectorproductSelector',
            },
            id: {
                userDisplayTable: 'userDisplayTable',
                contentIframe: 'contentIframe',
                openContact: 'OpenContact',
                timeViewTdl: 'timeView_tdl',
                saveButton: 'savebutton',
                closeButton: 'closebutton',
                requiredFieldValidator: 'RequiredFieldValidator',
                accIdValidator: 'externalKeyIDvalidator',
                confirmDialog: 'confirmationDialog',
                seachContact: '_accountdetails_',
                gridData: 'gridListing_GridData',
                topMenu: '_headingUpdatePanel',
                numericValidator: 'NumericValidator',
            },
        };
    }
}
