import { StepLogger } from '../../../../core/logger/step-logger';
import { PageHelper } from '../../../components/html/page-helper';
import { BrowsePageHelper } from '../../../page-objects/pages/browse-reports-page/browse-page.helper';
import { CommonPageHelper } from '../../../page-objects/pages/common/common-page.helper';
import { HomePage1Helper } from '../../../page-objects/pages/home-page/home-page1.helper';
import { LoginPageHelper } from '../../../page-objects/pages/login-page/login-page.helper';
import { SuiteNames } from '../../helpers/suite-names';

describe(SuiteNames.regressionSuite, () => {
    let loginPageHelper: LoginPageHelper;

    beforeAll(async () => {
        loginPageHelper = LoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
    });

    beforeEach(async () => {
        await loginPageHelper.goTo();
        await LoginPageHelper.loginAsAdmin();
    });

    // Jira References - COTRAC-2097
    it('Verify if user shall be able to Collapse the sections on screen - [22915088]', async () => {
        // Auto generated by aurea-automation - extension on Tue, 16 Apr 2019 11: 48: 25 GMT

        StepLogger.caseId = 22915088;
        StepLogger.stepId(1);
        StepLogger.step('Click on Reports menu on left side navigation pane of the screen.');
        await HomePage1Helper.clickReportsLink();
        StepLogger.verification('The Reports menu should expand.');
        await HomePage1Helper.verifyReportExpand();

        StepLogger.stepId(2);
        StepLogger.step('Check the Reports menu option list.');
        StepLogger.verification(`The Reports menu should have 4 options:
        Browse
        Custom Reports
        Report Writer
        Pending Reports`);
        await HomePage1Helper.verifyReportItemDisplay();

        StepLogger.stepId(3);
        StepLogger.step('Click on the Browse option menu.');
        await HomePage1Helper.clickOnBrowseButton();
        StepLogger.verification('The Standard Reports page is displayed in the right side pane.');
        await BrowsePageHelper.verifyBrowserPageIsDisplayed();

        StepLogger.stepId(4);
        StepLogger.step('Select Category from the Grouping Dropdown.');
        // Selected by default
        StepLogger.verification('The data in the grid is grouped by Category option.');
        await BrowsePageHelper.verifyGroupAppearing();

        StepLogger.stepId(5);
        StepLogger.step('Click on minus sign (-) next to Category group.');
        await BrowsePageHelper.clickMinusButton();
        StepLogger.verification('The details of that section on screen is collapsed.');
        await BrowsePageHelper.verifySectionCollapse();

        StepLogger.stepId(6);
        StepLogger.step('Click on Sign off button at the bottom in the left side Navigation Pane.');
        await CommonPageHelper.signOffApp();
        StepLogger.verification('The Login screen is displayed again.');
        await LoginPageHelper.verifyLoginPage();
    });

    // Jira References - COTRAC-2097
    it('Verify if user shall be able to Expand the sections on screen - [22915089]', async () => {
        // Auto generated by aurea-automation - extension on Tue, 16 Apr 2019 16: 24: 49 GMT

        StepLogger.caseId = 22915089;
        StepLogger.stepId(1);
        StepLogger.step('Click on Reports menu on left side navigation pane of the screen.');
        await HomePage1Helper.clickReportsLink();
        StepLogger.verification('The Reports menu should expand.');
        await HomePage1Helper.verifyReportExpand();

        StepLogger.stepId(2);
        StepLogger.step('Check the Reports menu option list.');
        StepLogger.verification(`The Reports menu should have 4 options:
        Browse
        Custom Reports
        Report Writer
        Pending Reports`);
        await HomePage1Helper.verifyReportItemDisplay();

        StepLogger.stepId(3);
        StepLogger.step('Click on the Browse option menu.');
        await HomePage1Helper.clickOnBrowseButton();
        StepLogger.verification('The Standard Reports page is displayed in the right side pane.');
        await BrowsePageHelper.verifyBrowserPageIsDisplayed();

        StepLogger.stepId(4);
        StepLogger.step('Select Category from the Grouping Dropdown.');
        // Selected by default
        StepLogger.verification('The data in the grid is grouped by Category option.');
        await BrowsePageHelper.verifyGroupAppearing();

        StepLogger.stepId(5);
        StepLogger.step('Click on minus sign (-) next to Category group.');
        await BrowsePageHelper.clickMinusButton();
        StepLogger.verification('The details of that section on screen is collapsed.');
        await BrowsePageHelper.verifySectionCollapse();

        StepLogger.stepId(6);
        StepLogger.step('Click on plus sign (+) next to Category group.');
        await BrowsePageHelper.clickPlusButton();
        StepLogger.verification('The details of that section on screen is expanded');
        await BrowsePageHelper.verifySectionExpand();

        StepLogger.stepId(7);
        StepLogger.step('Click on Sign off button at the bottom in the left side Navigation Pane.');
        await CommonPageHelper.signOffApp();
        StepLogger.verification('The Login screen is displayed again.');
        await LoginPageHelper.verifyLoginPage();
    });
});
