import { StepLogger } from '../../../../../core/logger/step-logger';
import { PageHelper } from '../../../../components/html/page-helper';
import { GoalsConstants } from '../../../../page-objects/pages/administration/goals/goals.constants';
import { GoalsHelper } from '../../../../page-objects/pages/administration/goals/goals.helper';
import { HomePageHelper } from '../../../../page-objects/pages/home-page/home-page.helper';
import { HomePage1Helper } from '../../../../page-objects/pages/home-page/home-page1.helper';
import { LoginPageHelper } from '../../../../page-objects/pages/login-page/login-page.helper';
import { SuiteNames } from '../../../helpers/suite-names';

describe(SuiteNames.regressionSuite, () => {
    let loginPageHelper: LoginPageHelper;

    beforeAll(async () => {
        loginPageHelper = LoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
    });

    beforeEach(async () => {
        await loginPageHelper.goTo();
        await LoginPageHelper.loginAsAdmin();
    });

    it('To verify list of Roles is displayed in drop-down "Start with records from this role". - [22968019]', async () => {
        // Auto generated by aurea-automation - util on Thu, 18 Apr 2019 01:47:19 GMT

        StepLogger.caseId = 22968019;
        StepLogger.stepId(1);
        StepLogger.step('Go to "Administration -> Goals"');
        await HomePageHelper.clickAdministrationLink();
        await HomePage1Helper.clickOnGoalsOptionUnderAdministration();
        StepLogger.verification('Manage goals page should be displayed.');
        await GoalsHelper.verifyManageGoalsPage();

        StepLogger.stepId(2);
        StepLogger.step('Click "Customize User" button');
        await GoalsHelper.clickOnCustomizeUserButton();
        StepLogger.verification('"Customize User Goals" pop-up should be displayed.');
        await GoalsHelper.verifyCustomizeUserGoalsPopUp();

        StepLogger.stepId(3);
        StepLogger.step('Click on "Start with records from this role".');
        await GoalsHelper.clickOnStartWithRecordsFromThisRole();
        StepLogger.verification('List of Roles is displayed in drop-down');
        await GoalsHelper.verifyStartWithRecordsFromThisRole();
    });

    it('To verify list of users is displayed in drop-down "Start with records from this user". - [22968025]', async () => {
        // Auto generated by aurea-automation - util on Thu, 18 Apr 2019 05:56:58 GMT

        StepLogger.caseId = 22968025;
        StepLogger.stepId(1);
        StepLogger.step('Go to "Administration -> Goals"');
        await HomePageHelper.clickAdministrationLink();
        await HomePage1Helper.clickOnGoalsOptionUnderAdministration();
        StepLogger.verification('Manage goals page should be displayed.');
        await GoalsHelper.verifyManageGoalsPage();

        StepLogger.stepId(2);
        StepLogger.step('Click "Customize User" button');
        await GoalsHelper.clickOnCustomizeUserButton();
        StepLogger.verification('"Customize User Goals" pop-up should be displayed.');
        await GoalsHelper.verifyCustomizeUserGoalsPopUp();

        StepLogger.stepId(3);
        StepLogger.step('Click Start with records from this user" .');
        await GoalsHelper.clickOnStartWithRecordsFromThisUser();
        StepLogger.verification('List of Users is displayed in drop-down');
        await GoalsHelper.verifyStartWithRecordsFromThisUser();
    });

    it('To verify user is able to close "Customize User Goals" pop-up window by clicking on close icon. - [22968026]', async () => {
        // Auto generated by aurea-automation - util on Thu, 18 Apr 2019 06:07:02 GMT

        StepLogger.caseId = 22968026;
        StepLogger.stepId(1);
        StepLogger.step('Go to "Administration -> Goals"');
        await HomePageHelper.clickAdministrationLink();
        await HomePage1Helper.clickOnGoalsOptionUnderAdministration();
        StepLogger.verification('Manage goals page should be displayed.');
        await GoalsHelper.verifyManageGoalsPage();

        StepLogger.stepId(2);
        StepLogger.step('Click "Customize User" button');
        await GoalsHelper.clickOnCustomizeUserButton();
        StepLogger.verification('"Customize User Goals" pop-up should be displayed.');
        await GoalsHelper.verifyCustomizeUserGoalsPopUp();

        StepLogger.stepId(3);
        StepLogger.step('Click Close icon');
        await GoalsHelper.clickOnCloseIcon();
        StepLogger.verification('"Customize User Goals" pop-up window is closed');
        await GoalsHelper.verifyCustomizeUserGoalsPopUpClosed();
    });

    it('To verify the functionality of Cancel button on "Customize User Goals" pop-up window. - [22968027]', async () => {
        // Auto generated by aurea-automation - util on Thu, 18 Apr 2019 07:13:48 GMT

        StepLogger.caseId = 22968027;
        StepLogger.stepId(1);
        StepLogger.step('Go to "Administration -> Goals"');
        await HomePageHelper.clickAdministrationLink();
        await HomePage1Helper.clickOnGoalsOptionUnderAdministration();
        StepLogger.verification('Manage goals page should be displayed.');
        await GoalsHelper.verifyManageGoalsPage();

        StepLogger.stepId(2);
        StepLogger.step('Click "Customize User" button');
        await GoalsHelper.clickOnCustomizeUserButton();
        StepLogger.verification('"Customize User Goals" pop-up should be displayed.');
        await GoalsHelper.verifyCustomizeUserGoalsPopUp();

        StepLogger.stepId(3);
        StepLogger.step('Click Cancel button');
        await GoalsHelper.clickCancelOnCustomizeUserPopup();
        StepLogger.verification('"Customize User Goals" pop-up window is closed');
        await GoalsHelper.verifyCustomizeUserGoalsPopUpClosed();
    });

    it('To verify if user goal is customized by selecting role from drop-down "Start with records from this role" - [22968028]', async () => {
        // Auto generated by aurea-automation - util on Thu, 18 Apr 2019 08:06:06 GMT

        StepLogger.caseId = 22968028;
        const user = GoalsConstants.user;
        const role = GoalsConstants.businessDevelopment;

        StepLogger.stepId(1);
        StepLogger.step('Go to "Administration -> Goals"');
        await HomePageHelper.clickAdministrationLink();
        await HomePage1Helper.clickOnGoalsOptionUnderAdministration();
        StepLogger.verification('Manage goals page should be displayed.');
        await GoalsHelper.verifyManageGoalsPage();

        StepLogger.stepId(2);
        StepLogger.step('Click "Customize User" button');
        await GoalsHelper.clickOnCustomizeUserButton();
        StepLogger.verification('"Customize User Goals" pop-up should be displayed.');
        await GoalsHelper.verifyCustomizeUserGoalsPopUp();

        StepLogger.stepId(3);
        StepLogger.step('Select a user to customize from "Select the user to customize" drop-down');
        await GoalsHelper.selectAUserFromCustomizeDropDown(user);
        StepLogger.verification('User is able to select a user from drop-down.');
        await GoalsHelper.verifyUserSelected(user);

        StepLogger.stepId(4);
        StepLogger.step('Select the radio button - "Start with records from this role"');
        await GoalsHelper.clickOnStartWithRecordsFromThisRoleRadio();
        StepLogger.verification('User is able to select radio button');
        await GoalsHelper.verifyStartWithRecordsFromThisRoleRadioSelected();

        StepLogger.stepId(5);
        StepLogger.step('Select a role from "Start with records from this role" drop-down');
        await GoalsHelper.selectARoleFromDropDown(role);
        StepLogger.verification('User is able to select role from drop-down');
        await GoalsHelper.verifyRoleSelected(role);

        StepLogger.stepId(6);
        StepLogger.step('Click Save button');
        await GoalsHelper.clickSaveOnCustomizeUserPopup();
        StepLogger.verification('Window is closed and user is redirected to Manage Goal page.');
        await GoalsHelper.verifyCustomizeUserGoalsPopUpClosed();
    });
});
