import { StepLogger } from '../../../../../core/logger/step-logger';
import { PageHelper } from '../../../../components/html/page-helper';
import { DepartmentsHelper } from '../../../../page-objects/pages/administration/organization/departments/departments.helper';
import { HomePageHelper } from '../../../../page-objects/pages/home-page/home-page.helper';
import { LoginPageHelper } from '../../../../page-objects/pages/login-page/login-page.helper';
import { SuiteNames } from '../../../helpers/suite-names';

describe(SuiteNames.regressionSuite, () => {
    let loginPageHelper: LoginPageHelper;

    beforeAll(async () => {
        loginPageHelper = LoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
    });

    beforeEach(async () => {
        await loginPageHelper.goTo();
        await LoginPageHelper.loginAsAdmin();
    });

    it('To verify that the user is able to navigate to Manage Departments page. - [22441975]', async () => {
        // Auto generated by aurea-automation - util on Fri, 22 Mar 2019 05:43:11 GMT

        StepLogger.caseId = 22441975;
        StepLogger.stepId(1);
        StepLogger.step('Click "Administration" link displayed in the left panel.');
        await HomePageHelper.clickAdministrationLink();
        StepLogger.verification('Option available under administration section should be displayed.');
        await HomePageHelper.verifyOptionsUnderAdministration();

        StepLogger.stepId(2);
        StepLogger.step('Click "Organization" displayed under administration.');
        await HomePageHelper.clickOrganizationUnderAdministration();
        StepLogger.verification('Item available under Organization should be displayed.');
        await HomePageHelper.optionsUnderOrganization();

        StepLogger.stepId(3);
        StepLogger.step('Click "Departments"');
        await HomePageHelper.clickDepartmentsUnderOrganization();
        StepLogger.verification('Manage Departments page should be displayed.');
        await DepartmentsHelper.verifyManageDepartmentsPageDisplayed();
    });

    it('To verify the list of Items in Grid on Manage Departments Page - [22441976]', async () => {
        // Auto generated by aurea-automation - util on Fri, 22 Mar 2019 06:40:28 GMT

        StepLogger.caseId = 22441976;
        StepLogger.stepId(1);
        StepLogger.step('Click "Administration" link displayed in the left panel.');
        await HomePageHelper.clickAdministrationLink();
        StepLogger.verification('Option available under administration section should be displayed.');
        await HomePageHelper.verifyOptionsUnderAdministration();

        StepLogger.stepId(2);
        StepLogger.step('Click "Departments"');
        await HomePageHelper.clickOrganizationUnderAdministration();
        await HomePageHelper.clickDepartmentsUnderOrganization();
        StepLogger.verification('Manage Departments page should be displayed.');
        await DepartmentsHelper.verifyManageDepartmentsPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Verify the Items displayed in the grid.');
        StepLogger.verification(`Following item should be displayed:
        1. Department
        2. Code
        3. Description
        4. Active`);
        await DepartmentsHelper.verifyDepartmentsPageItemsGrid();
    });

    it('To verify the button available on "Manage Departments page". - [22441978]', async () => {
        // Auto generated by aurea-automation - util on Fri, 22 Mar 2019 06:52:12 GMT

        StepLogger.caseId = 22441978;
        StepLogger.stepId(1);
        StepLogger.step('Goto  "Administration -> Organization" displayed under administration.');
        await HomePageHelper.clickAdministrationLink();
        StepLogger.verification('Option available under administration section should be displayed.');
        await HomePageHelper.verifyOptionsUnderAdministration();

        StepLogger.stepId(2);
        StepLogger.step('Click "Departments"');
        await HomePageHelper.clickOrganizationUnderAdministration();
        await HomePageHelper.clickDepartmentsUnderOrganization();
        StepLogger.verification('Manage Departments page should be displayed.');
        await DepartmentsHelper.verifyManageDepartmentsPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('To verify the button available on "Manage Department page".');
        StepLogger.verification(`Following options should be displayed.
        1. Add Department
        2. Refresh
        3. Export to Excel
        4. Export to Word`);
        await DepartmentsHelper.verifyButtons();
    });

    it('To verify that user is able to navigate to "New Department" page. - [22441993]', async () => {
        // Auto generated by aurea-automation - util on Fri, 22 Mar 2019 08:49:21 GMT

        StepLogger.caseId = 22441993;
        StepLogger.stepId(1);
        StepLogger.step('Goto  "Administration -> Organization" displayed under administration.');
        await HomePageHelper.clickAdministrationLink();
        StepLogger.verification('Option available under administration section should be displayed.');
        await HomePageHelper.verifyOptionsUnderAdministration();

        StepLogger.stepId(2);
        StepLogger.step('Click "Departments"');
        await HomePageHelper.clickOrganizationUnderAdministration();
        await HomePageHelper.clickDepartmentsUnderOrganization();
        StepLogger.verification('Manage Departments page should be displayed.');
        await DepartmentsHelper.verifyManageDepartmentsPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click "Add Department"');
        await DepartmentsHelper.clickAddDepartment();
        StepLogger.verification('"New department" page should be displayed.');
        await DepartmentsHelper.verifyNewDepartmentScreen();
    });

    it('To verify the functionality of cancel button on Add new department page. - [22441996]', async () => {
        // Auto generated by aurea-automation - util on Fri, 22 Mar 2019 09:23:28 GMT

        StepLogger.caseId = 22441996;
        StepLogger.stepId(1);
        StepLogger.step('Goto  "Administration -> Organization" displayed under administration.');
        await HomePageHelper.clickAdministrationLink();
        StepLogger.verification('Option available under administration section should be displayed.');
        await HomePageHelper.verifyOptionsUnderAdministration();

        StepLogger.stepId(2);
        StepLogger.step('Click "Departments"');
        await HomePageHelper.clickOrganizationUnderAdministration();
        await HomePageHelper.clickDepartmentsUnderOrganization();
        StepLogger.verification('Manage Departments page should be displayed.');
        await DepartmentsHelper.verifyManageDepartmentsPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click "Add Department"');
        await DepartmentsHelper.clickAddDepartment();
        StepLogger.verification('"New department" page should be displayed.');
        await DepartmentsHelper.verifyNewDepartmentScreen();

        StepLogger.stepId(4);
        StepLogger.step('Click "cancel" button.');
        await DepartmentsHelper.clickOnCancel();
        StepLogger.verification('New department page should be closed.');
        await DepartmentsHelper.verifyNewDepartmentScreenClosed();
    });
});
