import { StepLogger } from '../../../../core/logger/step-logger';
import { PageHelper } from '../../../components/html/page-helper';
import { CommonPageConstant } from '../../../page-objects/pages/common/common-page.constant';
import { CommonPageHelper } from '../../../page-objects/pages/common/common-page.helper';
import { ContactPageHelper } from '../../../page-objects/pages/contact-page/contact-page.helper';
import { LoginPageHelper } from '../../../page-objects/pages/login-page/login-page.helper';
import { CampaignsConstant } from '../../../page-objects/pages/marketing/campaigns/campaigns.constants';
import { CampaignsPage } from '../../../page-objects/pages/marketing/campaigns/campaigns.po';
import { NewProspectPageHelper } from '../../../page-objects/pages/new-prospect-page/new-prospect-page.helper';
import { ReferralsPageHelper } from '../../../page-objects/pages/referrals/referrals.helper';
import { CasesHelper } from '../../../page-objects/pages/service-center/cases/cases.helper';
import { SuiteNames } from '../../helpers/suite-names';

describe(SuiteNames.regressionSuite, () => {
    let loginPageHelper: LoginPageHelper;

    beforeAll(async () => {
        loginPageHelper = LoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
    });

    beforeAll(async () => {
        await loginPageHelper.goTo();
        await LoginPageHelper.loginAsAdmin();
    });

    // Jira References - COTRAC-2439
    it('Verify user can sort the data in Owner column in descending order - [22980506]', async () => {
        // Auto generated by aurea-automation - util on Thu, 27 Jun 2019 11:47:58 GMT

        StepLogger.caseId = 22980506;
        StepLogger.stepId(1);
        StepLogger.step('Click on global search button.');
        await CommonPageHelper.clickOnGlobalSearchButton();
        StepLogger.verification('The Search text field is displayed.');
        await CommonPageHelper.verifyGlobalTextboxDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Select Contacts from the dropdown next to search text field.');
        await CommonPageHelper.selectItemFromGlobalDropdown(CommonPageConstant.names.contact);
        StepLogger.verification('The Contacts option is selected from the dropdown.');
        await CommonPageHelper.verifySelectedItemFromGlobalDropdown(CommonPageConstant.names.contact);

        StepLogger.stepId(3);
        StepLogger.step(`Enter the name of the Commercial Prospect/Contact (Company) on the search
        bar and click on the search button e.g. Manpasand Beverages Ltd`);
        await CommonPageHelper.typeValueInGlobalTextFieldAndClickSearchIcon(CommonPageConstant.testData.manpasandBeveragesLtd);
        StepLogger.verification('The Contact card is displayed on the screen.');
        await ReferralsPageHelper.verifyActivityCardDisplayed(CommonPageConstant.testData.manpasandBeveragesLtd);

        StepLogger.stepId(4);
        StepLogger.step('Click on the Commercial Prospect/Contact (Company) Contact card.');
        await ReferralsPageHelper.clickOnActivityCard(CommonPageConstant.testData.manpasandBeveragesLtd);
        StepLogger.verification('The snapshot window is displayed for the Commercial Prospect/Contact (Company)');
        await ContactPageHelper.verifySnapshotModalIsDisplayed(false);

        StepLogger.stepId(5);
        StepLogger.step('Click on close button on the snapshot window.');
        await ContactPageHelper.closeSnapshotModal();
        StepLogger.verification('The detail of the contact is displayed on a new page with overview tab displayed as default.');
        await ContactPageHelper.verifyContactPageIsDisplayed(false);

        StepLogger.stepId(6);
        StepLogger.step('Click on Cases button in the left side navigation pane.');
        await NewProspectPageHelper.clickCases();
        StepLogger.verification('The screen is refreshed and the Cases information is displayed on the right side pane.');
        await NewProspectPageHelper.verifyCasesPage();

        StepLogger.stepId(7);
        StepLogger.step('Click on Owner column to sort the data');
        await CasesHelper.clickOnColumnHeader(CampaignsPage.elements.marketingColumns.owner);
        StepLogger.verification('The data in Owner column is sorted in ascending order');
        await CasesHelper.verifyRecordsSortedAsc(CampaignsConstant.elementNames.marketingColumns.owner, false);

        StepLogger.stepId(8);
        StepLogger.step('Click on Owner column to sort the data');
        await CasesHelper.clickOnColumnHeader(CampaignsPage.elements.marketingColumns.owner);
        StepLogger.verification('The data in Owner column is sorted in descending order');
        await CasesHelper.verifyRecordsSortedDesc(CampaignsConstant.elementNames.marketingColumns.owner);
    });

    // Jira References - COTRAC-2439
    it('Verify user can sort the data in Queue column in ascending order - [22980508]', async () => {
        // Auto generated by aurea-automation - util on Thu, 27 Jun 2019 12:53:12 GMT

        StepLogger.caseId = 22980508;
        StepLogger.stepId(1);
        StepLogger.step('Click on global search button.');
        await CommonPageHelper.clickOnGlobalSearchButton();
        StepLogger.verification('The Search text field is displayed.');
        await CommonPageHelper.verifyGlobalTextboxDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Select Contacts from the dropdown next to search text field.');
        await CommonPageHelper.selectItemFromGlobalDropdown(CommonPageConstant.names.contact);
        StepLogger.verification('The Contacts option is selected from the dropdown.');
        await CommonPageHelper.verifySelectedItemFromGlobalDropdown(CommonPageConstant.names.contact);

        StepLogger.stepId(3);
        StepLogger.step(`Enter the name of the Commercial Prospect/Contact (Company) on the search
        bar and click on the search button e.g. Manpasand Beverages Ltd`);
        await CommonPageHelper.typeValueInGlobalTextFieldAndClickSearchIcon(CommonPageConstant.testData.manpasandBeveragesLtd);
        StepLogger.verification('The Contact card is displayed on the screen.');
        await ReferralsPageHelper.verifyActivityCardDisplayed(CommonPageConstant.testData.manpasandBeveragesLtd);

        StepLogger.stepId(4);
        StepLogger.step('Click on the Commercial Prospect/Contact (Company) Contact card.');
        await ReferralsPageHelper.clickOnActivityCard(CommonPageConstant.testData.manpasandBeveragesLtd);
        StepLogger.verification('The snapshot window is displayed for the Commercial Prospect/Contact (Company)');
        await ContactPageHelper.verifySnapshotModalIsDisplayed(false);

        StepLogger.stepId(5);
        StepLogger.step('Click on close button on the snapshot window.');
        await ContactPageHelper.closeSnapshotModal();
        StepLogger.verification('The detail of the contact is displayed on a new page with overview tab displayed as default.');
        await ContactPageHelper.verifyContactPageIsDisplayed(false);

        StepLogger.stepId(6);
        StepLogger.step('Click on Cases button in the left side navigation pane.');
        await NewProspectPageHelper.clickCases();
        StepLogger.verification('The screen is refreshed and the Cases information is displayed on the right side pane.');
        await NewProspectPageHelper.verifyCasesPage();

        StepLogger.stepId(7);
        StepLogger.step('Click on Queue column to sort the data');
        await CasesHelper.clickOnColumnHeader(CampaignsPage.elements.marketingColumns.queue);
        StepLogger.verification('The data in Queue column is sorted in ascending order');
        await CasesHelper.verifyRecordsSortedAsc(CampaignsConstant.elementNames.marketingColumns.queue);
    });

    // Jira References - COTRAC-2439
    it('Verify user can sort the data in Queue column in descending order - [22980509]', async () => {
        // Auto generated by aurea-automation - util on Thu, 27 Jun 2019 13:27:05 GMT

        StepLogger.caseId = 22980509;
        StepLogger.stepId(1);
        StepLogger.step('Click on global search button.');
        await CommonPageHelper.clickOnGlobalSearchButton();
        StepLogger.verification('The Search text field is displayed.');
        await CommonPageHelper.verifyGlobalTextboxDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Select Contacts from the dropdown next to search text field.');
        await CommonPageHelper.selectItemFromGlobalDropdown(CommonPageConstant.names.contact);
        StepLogger.verification('The Contacts option is selected from the dropdown.');
        await CommonPageHelper.verifySelectedItemFromGlobalDropdown(CommonPageConstant.names.contact);

        StepLogger.stepId(3);
        StepLogger.step(`Enter the name of the Commercial Prospect/Contact (Company) on the search
        bar and click on the search button e.g. Manpasand Beverages Ltd`);
        await CommonPageHelper.typeValueInGlobalTextFieldAndClickSearchIcon(CommonPageConstant.testData.manpasandBeveragesLtd);
        StepLogger.verification('The Contact card is displayed on the screen.');
        await ReferralsPageHelper.verifyActivityCardDisplayed(CommonPageConstant.testData.manpasandBeveragesLtd);

        StepLogger.stepId(4);
        StepLogger.step('Click on the Commercial Prospect/Contact (Company) Contact card.');
        await ReferralsPageHelper.clickOnActivityCard(CommonPageConstant.testData.manpasandBeveragesLtd);
        StepLogger.verification('The snapshot window is displayed for the Commercial Prospect/Contact (Company)');
        await ContactPageHelper.verifySnapshotModalIsDisplayed(false);

        StepLogger.stepId(5);
        StepLogger.step('Click on close button on the snapshot window.');
        await ContactPageHelper.closeSnapshotModal();
        StepLogger.verification('The detail of the contact is displayed on a new page with overview tab displayed as default.');
        await ContactPageHelper.verifyContactPageIsDisplayed(false);

        StepLogger.stepId(6);
        StepLogger.step('Click on Cases button in the left side navigation pane.');
        await NewProspectPageHelper.clickCases();
        StepLogger.verification('The screen is refreshed and the Cases information is displayed on the right side pane.');
        await NewProspectPageHelper.verifyCasesPage();

        StepLogger.stepId(7);
        StepLogger.step('Click on Queue column to sort the data');
        await CasesHelper.clickOnColumnHeader(CampaignsPage.elements.marketingColumns.queue);
        StepLogger.verification('The data in Queue column is sorted in ascending order');
        await CasesHelper.verifyRecordsSortedAsc(CampaignsConstant.elementNames.marketingColumns.queue, false);

        StepLogger.stepId(8);
        StepLogger.step('Click on Queue column to sort the data');
        await CasesHelper.clickOnColumnHeader(CampaignsPage.elements.marketingColumns.queue);
        StepLogger.verification('The data in Queue column is sorted in descending order');
        await CasesHelper.verifyRecordsSortedDesc(CampaignsConstant.elementNames.marketingColumns.queue);
    });

    // Jira References - COTRAC-2439
    it('Verify user can sort the data in Queue Branch column in ascending order - [22980518]', async () => {
        // Auto generated by aurea-automation - util on Fri, 28 Jun 2019 04:58:08 GMT

        StepLogger.caseId = 22980518;
        StepLogger.stepId(1);
        StepLogger.step('Click on global search button.');
        await CommonPageHelper.clickOnGlobalSearchButton();
        StepLogger.verification('The Search text field is displayed.');
        await CommonPageHelper.verifyGlobalTextboxDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Select Contacts from the dropdown next to search text field.');
        await CommonPageHelper.selectItemFromGlobalDropdown(CommonPageConstant.names.contact);
        StepLogger.verification('The Contacts option is selected from the dropdown.');
        await CommonPageHelper.verifySelectedItemFromGlobalDropdown(CommonPageConstant.names.contact);

        StepLogger.stepId(3);
        StepLogger.step(`Enter the name of the Commercial Prospect/Contact (Company) on the search
        bar and click on the search button e.g. Manpasand Beverages Ltd`);
        await CommonPageHelper.typeValueInGlobalTextFieldAndClickSearchIcon(CommonPageConstant.testData.manpasandBeveragesLtd);
        StepLogger.verification('The Contact card is displayed on the screen.');
        await ReferralsPageHelper.verifyActivityCardDisplayed(CommonPageConstant.testData.manpasandBeveragesLtd);

        StepLogger.stepId(4);
        StepLogger.step('Click on the Commercial Prospect/Contact (Company) Contact card.');
        await ReferralsPageHelper.clickOnActivityCard(CommonPageConstant.testData.manpasandBeveragesLtd);
        StepLogger.verification('The snapshot window is displayed for the Commercial Prospect/Contact (Company)');
        await ContactPageHelper.verifySnapshotModalIsDisplayed(false);

        StepLogger.stepId(5);
        StepLogger.step('Click on close button on the snapshot window.');
        await ContactPageHelper.closeSnapshotModal();
        StepLogger.verification('The detail of the contact is displayed on a new page with overview tab displayed as default.');
        await ContactPageHelper.verifyContactPageIsDisplayed(false);

        StepLogger.stepId(6);
        StepLogger.step('Click on Cases button in the left side navigation pane.');
        await NewProspectPageHelper.clickCases();
        StepLogger.verification('The screen is refreshed and the Cases information is displayed on the right side pane.');
        await NewProspectPageHelper.verifyCasesPage();

        StepLogger.stepId(7);
        StepLogger.step('Click on Queue Branch column to sort the data');
        await CasesHelper.clickOnColumnHeader(CampaignsPage.elements.marketingColumns.queueBranch);
        StepLogger.verification('The data in Queue Branch column is sorted in ascending order');
        await CasesHelper.verifyRecordsSortedAsc(CampaignsConstant.elementNames.marketingColumns.queueBranch);
    });

    // Jira References - COTRAC-2439
    it('Verify user can sort the data in Queue Branch column in descending order - [22980519]', async () => {
        // Auto generated by aurea-automation - util on Fri, 28 Jun 2019 05:17:37 GMT

        StepLogger.caseId = 22980519;
        StepLogger.stepId(1);
        StepLogger.step('Click on global search button.');
        await CommonPageHelper.clickOnGlobalSearchButton();
        StepLogger.verification('The Search text field is displayed.');
        await CommonPageHelper.verifyGlobalTextboxDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Select Contacts from the dropdown next to search text field.');
        await CommonPageHelper.selectItemFromGlobalDropdown(CommonPageConstant.names.contact);
        StepLogger.verification('The Contacts option is selected from the dropdown.');
        await CommonPageHelper.verifySelectedItemFromGlobalDropdown(CommonPageConstant.names.contact);

        StepLogger.stepId(3);
        StepLogger.step(`Enter the name of the Commercial Prospect/Contact (Company) on the search
        bar and click on the search button e.g. Manpasand Beverages Ltd`);
        await CommonPageHelper.typeValueInGlobalTextFieldAndClickSearchIcon(CommonPageConstant.testData.manpasandBeveragesLtd);
        StepLogger.verification('The Contact card is displayed on the screen.');
        await ReferralsPageHelper.verifyActivityCardDisplayed(CommonPageConstant.testData.manpasandBeveragesLtd);

        StepLogger.stepId(4);
        StepLogger.step('Click on the Commercial Prospect/Contact (Company) Contact card.');
        await ReferralsPageHelper.clickOnActivityCard(CommonPageConstant.testData.manpasandBeveragesLtd);
        StepLogger.verification('The snapshot window is displayed for the Commercial Prospect/Contact (Company)');
        await ContactPageHelper.verifySnapshotModalIsDisplayed(false);

        StepLogger.stepId(5);
        StepLogger.step('Click on close button on the snapshot window.');
        await ContactPageHelper.closeSnapshotModal();
        StepLogger.verification('The detail of the contact is displayed on a new page with overview tab displayed as default.');
        await ContactPageHelper.verifyContactPageIsDisplayed(false);

        StepLogger.stepId(6);
        StepLogger.step('Click on Cases button in the left side navigation pane.');
        await NewProspectPageHelper.clickCases();
        StepLogger.verification('The screen is refreshed and the Cases information is displayed on the right side pane.');
        await NewProspectPageHelper.verifyCasesPage();

        StepLogger.stepId(7);
        StepLogger.step('Click on Queue Branch column to sort the data');
        await CasesHelper.clickOnColumnHeader(CampaignsPage.elements.marketingColumns.queueBranch);
        StepLogger.verification('The data in Queue Branch column is sorted in ascending order');
        await CasesHelper.verifyRecordsSortedAsc(CampaignsConstant.elementNames.marketingColumns.queueBranch, false);

        StepLogger.stepId(8);
        StepLogger.step('Click on Queue Branch column to sort the data');
        await CasesHelper.clickOnColumnHeader(CampaignsPage.elements.marketingColumns.queueBranch);
        StepLogger.verification('The data in Queue Branch column is sorted in descending order');
        await CasesHelper.verifyRecordsSortedDesc(CampaignsConstant.elementNames.marketingColumns.queueBranch);
    });

    // Jira References - COTRAC-2439
    it('Verify user can sort the data in Submitter column in ascending order - [22980522]', async () => {
        // Auto generated by aurea-automation - util on Fri, 28 Jun 2019 05:25:19 GMT

        StepLogger.caseId = 22980522;
        StepLogger.stepId(1);
        StepLogger.step('Click on global search button.');
        await CommonPageHelper.clickOnGlobalSearchButton();
        StepLogger.verification('The Search text field is displayed.');
        await CommonPageHelper.verifyGlobalTextboxDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Select Contacts from the dropdown next to search text field.');
        await CommonPageHelper.selectItemFromGlobalDropdown(CommonPageConstant.names.contact);
        StepLogger.verification('The Contacts option is selected from the dropdown.');
        await CommonPageHelper.verifySelectedItemFromGlobalDropdown(CommonPageConstant.names.contact);

        StepLogger.stepId(3);
        StepLogger.step(`Enter the name of the Commercial Prospect/Contact (Company) on the search
        bar and click on the search button e.g. Manpasand Beverages Ltd`);
        await CommonPageHelper.typeValueInGlobalTextFieldAndClickSearchIcon(CommonPageConstant.testData.manpasandBeveragesLtd);
        StepLogger.verification('The Contact card is displayed on the screen.');
        await ReferralsPageHelper.verifyActivityCardDisplayed(CommonPageConstant.testData.manpasandBeveragesLtd);

        StepLogger.stepId(4);
        StepLogger.step('Click on the Commercial Prospect/Contact (Company) Contact card.');
        await ReferralsPageHelper.clickOnActivityCard(CommonPageConstant.testData.manpasandBeveragesLtd);
        StepLogger.verification('The snapshot window is displayed for the Commercial Prospect/Contact (Company)');
        await ContactPageHelper.verifySnapshotModalIsDisplayed(false);

        StepLogger.stepId(5);
        StepLogger.step('Click on close button on the snapshot window.');
        await ContactPageHelper.closeSnapshotModal();
        StepLogger.verification('The detail of the contact is displayed on a new page with overview tab displayed as default.');
        await ContactPageHelper.verifyContactPageIsDisplayed(false);

        StepLogger.stepId(6);
        StepLogger.step('Click on Cases button in the left side navigation pane.');
        await NewProspectPageHelper.clickCases();
        StepLogger.verification('The screen is refreshed and the Cases information is displayed on the right side pane.');
        await NewProspectPageHelper.verifyCasesPage();

        StepLogger.stepId(7);
        StepLogger.step('Click on Submitter column to sort the data');
        await CasesHelper.clickOnColumnHeader(CampaignsPage.elements.marketingColumns.submitter);
        StepLogger.verification('The data in Submitter column is sorted in ascending order');
        await CasesHelper.verifyRecordsSortedAsc(CampaignsConstant.elementNames.marketingColumns.submitter);
    });

    // Jira References - COTRAC-2439
    it('Verify user can sort the data in Submitter column in descending order - [22980528]', async () => {
        // Auto generated by aurea-automation - util on Fri, 28 Jun 2019 05:36:39 GMT

        StepLogger.caseId = 22980528;
        StepLogger.stepId(1);
        StepLogger.step('Click on global search button.');
        await CommonPageHelper.clickOnGlobalSearchButton();
        StepLogger.verification('The Search text field is displayed.');
        await CommonPageHelper.verifyGlobalTextboxDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Select Contacts from the dropdown next to search text field.');
        await CommonPageHelper.selectItemFromGlobalDropdown(CommonPageConstant.names.contact);
        StepLogger.verification('The Contacts option is selected from the dropdown.');
        await CommonPageHelper.verifySelectedItemFromGlobalDropdown(CommonPageConstant.names.contact);

        StepLogger.stepId(3);
        StepLogger.step(`Enter the name of the Commercial Prospect/Contact (Company) on the search
        bar and click on the search button e.g. Manpasand Beverages Ltd`);
        await CommonPageHelper.typeValueInGlobalTextFieldAndClickSearchIcon(CommonPageConstant.testData.manpasandBeveragesLtd);
        StepLogger.verification('The Contact card is displayed on the screen.');
        await ReferralsPageHelper.verifyActivityCardDisplayed(CommonPageConstant.testData.manpasandBeveragesLtd);

        StepLogger.stepId(4);
        StepLogger.step('Click on the Commercial Prospect/Contact (Company) Contact card.');
        await ReferralsPageHelper.clickOnActivityCard(CommonPageConstant.testData.manpasandBeveragesLtd);
        StepLogger.verification('The snapshot window is displayed for the Commercial Prospect/Contact (Company)');
        await ContactPageHelper.verifySnapshotModalIsDisplayed(false);

        StepLogger.stepId(5);
        StepLogger.step('Click on close button on the snapshot window.');
        await ContactPageHelper.closeSnapshotModal();
        StepLogger.verification('The detail of the contact is displayed on a new page with overview tab displayed as default.');
        await ContactPageHelper.verifyContactPageIsDisplayed(false);

        StepLogger.stepId(6);
        StepLogger.step('Click on Cases button in the left side navigation pane.');
        await NewProspectPageHelper.clickCases();
        StepLogger.verification('The screen is refreshed and the Cases information is displayed on the right side pane.');
        await NewProspectPageHelper.verifyCasesPage();

        StepLogger.stepId(7);
        StepLogger.step('Click on Submitter column to sort the data');
        await CasesHelper.clickOnColumnHeader(CampaignsPage.elements.marketingColumns.submitter);
        StepLogger.verification('The data in Submitter column is sorted in ascending order');
        await CasesHelper.verifyRecordsSortedAsc(CampaignsConstant.elementNames.marketingColumns.submitter, false);

        StepLogger.stepId(8);
        StepLogger.step('Click on Submitter column to sort the data');
        await CasesHelper.clickOnColumnHeader(CampaignsPage.elements.marketingColumns.submitter);
        StepLogger.verification('The data in Submitter column is sorted in descending order');
        await CasesHelper.verifyRecordsSortedDesc(CampaignsConstant.elementNames.marketingColumns.submitter);
    });

    // Jira References - COTRAC-2439
    it('Verify user can sort the data in Category column in ascending order - [22980563]', async () => {
        // Auto generated by aurea-automation - util on Fri, 28 Jun 2019 05:54:52 GMT

        StepLogger.caseId = 22980563;
        StepLogger.stepId(1);
        StepLogger.step('Click on global search button.');
        await CommonPageHelper.clickOnGlobalSearchButton();
        StepLogger.verification('The Search text field is displayed.');
        await CommonPageHelper.verifyGlobalTextboxDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Select Contacts from the dropdown next to search text field.');
        await CommonPageHelper.selectItemFromGlobalDropdown(CommonPageConstant.names.contact);
        StepLogger.verification('The Contacts option is selected from the dropdown.');
        await CommonPageHelper.verifySelectedItemFromGlobalDropdown(CommonPageConstant.names.contact);

        StepLogger.stepId(3);
        StepLogger.step(`Enter the name of the Commercial Prospect/Contact (Company) on the search
        bar and click on the search button e.g. Manpasand Beverages Ltd`);
        await CommonPageHelper.typeValueInGlobalTextFieldAndClickSearchIcon(CommonPageConstant.testData.manpasandBeveragesLtd);
        StepLogger.verification('The Contact card is displayed on the screen.');
        await ReferralsPageHelper.verifyActivityCardDisplayed(CommonPageConstant.testData.manpasandBeveragesLtd);

        StepLogger.stepId(4);
        StepLogger.step('Click on the Commercial Prospect/Contact (Company) Contact card.');
        await ReferralsPageHelper.clickOnActivityCard(CommonPageConstant.testData.manpasandBeveragesLtd);
        StepLogger.verification('The snapshot window is displayed for the Commercial Prospect/Contact (Company)');
        await ContactPageHelper.verifySnapshotModalIsDisplayed(false);

        StepLogger.stepId(5);
        StepLogger.step('Click on close button on the snapshot window.');
        await ContactPageHelper.closeSnapshotModal();
        StepLogger.verification('The detail of the contact is displayed on a new page with overview tab displayed as default.');
        await ContactPageHelper.verifyContactPageIsDisplayed(false);

        StepLogger.stepId(6);
        StepLogger.step('Click on Cases button in the left side navigation pane.');
        await NewProspectPageHelper.clickCases();
        StepLogger.verification('The screen is refreshed and the Cases information is displayed on the right side pane.');
        await NewProspectPageHelper.verifyCasesPage();

        StepLogger.stepId(7);
        StepLogger.step('Click on Category column to sort the data');
        await CasesHelper.clickOnColumnHeader(CampaignsPage.elements.marketingColumns.category);
        StepLogger.verification('The data in Category column is sorted in ascending order');
        await CasesHelper.verifyRecordsSortedAsc(CampaignsConstant.elementNames.marketingColumns.category);
    });

    // Jira References - COTRAC-2439
    it('Verify user can sort the data in Category column in descending order - [22980567]', async () => {
        // Auto generated by aurea-automation - util on Fri, 28 Jun 2019 06:04:48 GMT

        StepLogger.caseId = 22980567;
        StepLogger.stepId(1);
        StepLogger.step('Click on global search button.');
        await CommonPageHelper.clickOnGlobalSearchButton();
        StepLogger.verification('The Search text field is displayed.');
        await CommonPageHelper.verifyGlobalTextboxDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Select Contacts from the dropdown next to search text field.');
        await CommonPageHelper.selectItemFromGlobalDropdown(CommonPageConstant.names.contact);
        StepLogger.verification('The Contacts option is selected from the dropdown.');
        await CommonPageHelper.verifySelectedItemFromGlobalDropdown(CommonPageConstant.names.contact);

        StepLogger.stepId(3);
        StepLogger.step(`Enter the name of the Commercial Prospect/Contact (Company) on the search
        bar and click on the search button e.g. Manpasand Beverages Ltd`);
        await CommonPageHelper.typeValueInGlobalTextFieldAndClickSearchIcon(CommonPageConstant.testData.manpasandBeveragesLtd);
        StepLogger.verification('The Contact card is displayed on the screen.');
        await ReferralsPageHelper.verifyActivityCardDisplayed(CommonPageConstant.testData.manpasandBeveragesLtd);

        StepLogger.stepId(4);
        StepLogger.step('Click on the Commercial Prospect/Contact (Company) Contact card.');
        await ReferralsPageHelper.clickOnActivityCard(CommonPageConstant.testData.manpasandBeveragesLtd);
        StepLogger.verification('The snapshot window is displayed for the Commercial Prospect/Contact (Company)');
        await ContactPageHelper.verifySnapshotModalIsDisplayed(false);

        StepLogger.stepId(5);
        StepLogger.step('Click on close button on the snapshot window.');
        await ContactPageHelper.closeSnapshotModal();
        StepLogger.verification('The detail of the contact is displayed on a new page with overview tab displayed as default.');
        await ContactPageHelper.verifyContactPageIsDisplayed(false);

        StepLogger.stepId(6);
        StepLogger.step('Click on Cases button in the left side navigation pane.');
        await NewProspectPageHelper.clickCases();
        StepLogger.verification('The screen is refreshed and the Cases information is displayed on the right side pane.');
        await NewProspectPageHelper.verifyCasesPage();

        StepLogger.stepId(7);
        StepLogger.step('Click on Category column to sort the data');
        await CasesHelper.clickOnColumnHeader(CampaignsPage.elements.marketingColumns.category);
        StepLogger.verification('The data in Category column is sorted in ascending order');
        await CasesHelper.verifyRecordsSortedAsc(CampaignsConstant.elementNames.marketingColumns.category, false);

        StepLogger.stepId(8);
        StepLogger.step('Click on Category column to sort the data');
        await CasesHelper.clickOnColumnHeader(CampaignsPage.elements.marketingColumns.category);
        StepLogger.verification('The data in Category column is sorted in descending order');
        await CasesHelper.verifyRecordsSortedDesc(CampaignsConstant.elementNames.marketingColumns.category);
    });
});
