import { StepLogger } from '../../../../core/logger/step-logger';
import { PageHelper } from '../../../components/html/page-helper';
import { CommonPageConstant } from '../../../page-objects/pages/common/common-page.constant';
import { CommonPageHelper } from '../../../page-objects/pages/common/common-page.helper';
import { ContactPageHelper } from '../../../page-objects/pages/contact-page/contact-page.helper';
import { LoginPageHelper } from '../../../page-objects/pages/login-page/login-page.helper';
import { CampaignsPageHelperExtension } from '../../../page-objects/pages/marketing/campaigns/campaigns-extension.helper';
import { CampaignsPageHelper } from '../../../page-objects/pages/marketing/campaigns/campaigns.helper';
import { NewCasePageHelperExtension } from '../../../page-objects/pages/new-case-page/new-case-page.extension.helper';
import { ReferralsPageHelper } from '../../../page-objects/pages/referrals/referrals.helper';
import { SuiteNames } from '../../helpers/suite-names';

describe(SuiteNames.regressionSuite, () => {
    let loginPageHelper: LoginPageHelper;

    beforeAll(async () => {
        loginPageHelper = LoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
    });

    beforeAll(async () => {
        await loginPageHelper.goTo();
        await LoginPageHelper.loginAsAdmin();
    });

    // Jira References - COTRAC-2291
    it('Verify if user shall be able to see the History modal screen - [22958297]', async () => {
        // Auto generated by aurea-automation - util on Thu, 27 Jun 2019 08:20:42 GMT

        StepLogger.caseId = 22958297;
        StepLogger.stepId(1);
        StepLogger.step('Select Contact in the search dropdown list.');
        await CommonPageHelper.clickOnGlobalSearchButton();
        await CommonPageHelper.selectItemFromGlobalDropdown(CommonPageConstant.names.contact);
        StepLogger.verification('Contact should be selected properly.');
        await CommonPageHelper.verifySelectedItemFromGlobalDropdown(CommonPageConstant.names.contact);

        StepLogger.stepId(2);
        StepLogger.step('Fill the Search input field with text "Manpasand Beverages Ltd" and hit "Enter" button in the keyboard.');
        await CommonPageHelper.typeValueInGlobalTextFieldAndClickSearchIcon(CommonPageConstant.testData.manpasandBeveragesLtd);
        StepLogger.verification('Should display the company contact properly.');
        await ReferralsPageHelper.verifyActivityCardDisplayed(CommonPageConstant.testData.manpasandBeveragesLtd);

        StepLogger.stepId(3);
        StepLogger.step('Click on "Manpasand Beverages Ltd" company card.');
        await ReferralsPageHelper.clickOnActivityCard(CommonPageConstant.testData.manpasandBeveragesLtd);
        StepLogger.verification('Should display the company details screen in a new tab.');
        await ContactPageHelper.verifySnapshotModalIsDisplayed(false);

        StepLogger.stepId(4);
        StepLogger.step('Click on Three Dots menu button.');
        await ContactPageHelper.closeSnapshotModal();
        await NewCasePageHelperExtension.clickMenuButton();
        StepLogger.verification('Should display the options list:-Copy Link To Page-Email Link To Page-Print-History');
        await CampaignsPageHelper.verifyHistoryOptionFromTheDropdown();
        await CampaignsPageHelper.verifyEmailOptionFromTheDropdown();

        StepLogger.stepId(5);
        StepLogger.step('Click on History menu button.');
        await CampaignsPageHelper.clickOnHistoryOptionFromTheDropdown();
        StepLogger.verification('Should display the History modal screen properly.');
        await CampaignsPageHelperExtension.verifyHistoryModalIsDisplayed(true);
    });

    // Jira References - COTRAC-2291
    it('Verify if user shall be able to Print a file with Notes checkbox checked - [22958851]', async () => {
        // Auto generated by aurea-automation - util on Thu, 27 Jun 2019 09:00:24 GMT

        StepLogger.caseId = 22958851;
        StepLogger.stepId(1);
        StepLogger.step('Select Contact in the search dropdown list.');
        await CommonPageHelper.clickOnGlobalSearchButton();
        await CommonPageHelper.selectItemFromGlobalDropdown(CommonPageConstant.names.contact);
        StepLogger.verification('Contact should be selected properly.');
        await CommonPageHelper.verifySelectedItemFromGlobalDropdown(CommonPageConstant.names.contact);

        StepLogger.stepId(2);
        StepLogger.step('Fill the Search input field with text "Manpasand Beverages Ltd" and hit "Enter" button in the keyboard.');
        await CommonPageHelper.typeValueInGlobalTextFieldAndClickSearchIcon(CommonPageConstant.testData.manpasandBeveragesLtd);
        StepLogger.verification('Should display the company contact properly.');
        await ReferralsPageHelper.verifyActivityCardDisplayed(CommonPageConstant.testData.manpasandBeveragesLtd);

        StepLogger.stepId(3);
        StepLogger.step('Click on "Manpasand Beverages Ltd" company card.');
        await ReferralsPageHelper.clickOnActivityCard(CommonPageConstant.testData.manpasandBeveragesLtd);
        StepLogger.verification('Should display the company details screen in a new tab.');
        await ContactPageHelper.verifySnapshotModalIsDisplayed(false);

        StepLogger.stepId(4);
        StepLogger.step('Click on Three Dots menu button.');
        await ContactPageHelper.closeSnapshotModal();
        await NewCasePageHelperExtension.clickMenuButton();
        StepLogger.verification('Should display the options list:-Copy Link To Page-Email Link To Page-Print-History');
        await CampaignsPageHelper.verifyHistoryOptionFromTheDropdown();
        await CampaignsPageHelper.verifyEmailOptionFromTheDropdown();

        StepLogger.stepId(5);
        StepLogger.step('Click on Print menu button.');
        await CampaignsPageHelper.clickPrint();
        StepLogger.verification('Should display the Print modal screen properly.');
        await CampaignsPageHelper.verifyPrintModalIsDisplayed(false);

        StepLogger.stepId(6);
        StepLogger.step('Check the checkbox:-Notes');
        await CampaignsPageHelper.checkNoteBox(false);
        StepLogger.verification('The Notes checkbox should be checked properly.');
        await CampaignsPageHelper.verifyNoteBox(false);

        StepLogger.stepId(7);
        StepLogger.step('Click on Print button.');
        await ContactPageHelper.closeSnapshotModal();
        await NewCasePageHelperExtension.clickMenuButton();
        await CampaignsPageHelper.clickPrint();
        StepLogger.verification('Should display the Print screen with the options selected by user.');
        await CampaignsPageHelper.verifyPrintModalIsDisplayed(true);
    });
});
