export class ReportWriterReportsConstant {

    static get elementNames() {
        return {
            reportWriterReports: 'Report Writer Reports',
            preview: 'Preview',
            action: 'Actions',
            name: 'Name',
            type: 'Type',
            lastchange: 'Last Change',
            description: 'Description',
            images: 'Images',
            yearlyquarters: 'Yearly Quarters',
            resources: 'Resources',
            reports: 'Reports',
            createEdit: 'Create/Edit',
            newReport: 'New report',
            editThisReport: 'Edit this report',
            copyThisReport: 'Clone this report',
            deleteThisReport: 'Delete this report',
            lockThisReport: 'Click to lock this report',
            runThisReport: 'Run this report',
            newUnionReport: 'New union report',
            schema: 'Schema',
            connections: 'Connections',
            create: 'Create',
            edit: 'Edit',
            reportName: 'Report name:',
            reportCriteria: 'Report Criteria:',
            expand: 'Expand',
            collapse: 'Collapse',
            permissions: 'Permissions',
            groups: 'Groups',
            users: 'Users',
            importExport: 'Import / Export',
            export: 'Export',
            import: 'Import',
            removeSelected: 'Remove selected',
            top: 'Top',
            refresh: 'Refresh',
            sheetPage: 'sheet page',
        };
    }

    static get attributes() {
        return {
            classes: {
                title: '.toolbar-title',
                selected: 'rtsSelected',
                preview: '.report_preview_link',
            },
            id: {
                runReport: 'RunReport',
                addConditionals: 'AddConditional',
                close: 'Close',
                editConditionals: 'WindowEditConditional',
            },
            name: {
                edit: 'Edit this report',
                editConditionals: 'Edit Conditional',
                general: 'General',
                sharing: 'Sharing',
                conditionals: 'Conditionals',
                addConditionals: 'Add Conditionals',
                close: 'Close',
                runReport: 'Run This Report',
                createAndEdit: 'Create/Edit',
                createAndEditForm: 'Reports -> Create/Edit',
                columnSelection: 'Column Selection',
                tableRelationships: 'Report Selection',
                filtration: 'Filtration',
                groupsSummaries	: 'Groups/Summaries',
                uIType: 'UI Type:',
                dropDown: 'Drop down',
                checkboxes: 'Checkboxes',
                value: 'Value',
                add: 'Add',
                groups: 'Groups',
                groupsAll: 'Groups All',
                users: 'Users',
                sharingSaved: 'Sharing saved.',
                editCheckbox: 'Edit',
                editAll: 'Edit All',
                export: 'Export',
                exportAll: 'Export All',
                label: 'Label',
                btnSave: 'btnSave',
                editThisConditional: 'Edit this conditional',
                makeCopy: 'Make a copy below',
                remove: 'Remove',
                generatingReport: 'Generating report...',
            },
        };
    }
}
