import { StepLogger } from '../../../../../core/logger/step-logger';
import { PageHelper } from '../../../../components/html/page-helper';
import { CustomItemHelper } from '../../../../page-objects/pages/administration/configuration/custom-item/custom-item.helper';
import { OutsideInstitutionHelper } from '../../../../page-objects/pages/administration/configuration/outside-institutions/outside-institutions.helper';
import { BranchesHelper } from '../../../../page-objects/pages/administration/organization/branches/branches.helper';
import { CaseAreasHelper } from '../../../../page-objects/pages/administration/service-center/case-areas-page/case-areas.helper';
import { ApplicationStatusHelper } from '../../../../page-objects/pages/administration/system/application-status/application-status.helper';
import { ContactPageHelper } from '../../../../page-objects/pages/contact-page/contact-page.helper';
import { ContactPage } from '../../../../page-objects/pages/contact-page/contact-page.po';
import { HomePageConstant } from '../../../../page-objects/pages/home-page/home-page.constants';
import { HomePageHelper } from '../../../../page-objects/pages/home-page/home-page.helper';
import { HomePage } from '../../../../page-objects/pages/home-page/home-page.po';
import { HomePage1Helper } from '../../../../page-objects/pages/home-page/home-page1.helper';
import { LoginPageHelper } from '../../../../page-objects/pages/login-page/login-page.helper';
import { ManageCompensationPageHelper } from '../../../../page-objects/pages/manage-compensation-page/manage-compensation-page.helper';
import { SuiteNames } from '../../../helpers/suite-names';

describe(SuiteNames.regressionSuite, () => {
    const searchText = HomePageConstant.testData.alec;
    let loginPageHelper: LoginPageHelper;

    beforeAll(async () => {
        loginPageHelper = LoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
    });

    beforeEach(async () => {
        await PageHelper.restartBrowser();
        await loginPageHelper.goTo();
        await LoginPageHelper.loginAsAdmin();
    });

    // Jira References - COTRAC-2113
    it('To verify that non-admin user cannot access "Custom Item Types" once access is revoked by admin user - [22981127]', async () => {
        // Auto generated by aurea-automation - util on Thu, 18 Apr 2019 13:56:50 GMT

        StepLogger.caseId = 22981127;
        StepLogger.stepId(1);
        StepLogger.step('Login to the Application with non-admin user whose access is revoked in Pre condition tc. [Test_ros_001/Test12345]');
        StepLogger.verification('User should be able to login.');
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Click Administration from left pane');
        await HomePageHelper.clickAdministrationLink();
        StepLogger.verification('Sub options under Administration are displayed');
        await HomePageHelper.verifyOptionsUnderAdministration();

        StepLogger.stepId(3);
        StepLogger.step('Verify if Custom Item Types is displayed under Configuration');
        StepLogger.verification('Custom Item Types should be missing under Configuration');
        await HomePage1Helper.navigateConfigurationCustomItemTypes();
    });

    // Jira References - COTRAC-2113
    it('To verify that non-admin user cannot access "Corrections" once access is revoked by admin user - [22981125]', async () => {
        // Auto generated by aurea-automation - util on Thu, 18 Apr 2019 13:56:50 GMT

        StepLogger.caseId = 22981125;
        StepLogger.stepId(1);
        StepLogger.step('Login to the Application with non-admin user whose access is revoked in Pre condition tc. [Test_ros_001/Test12345]');
        StepLogger.verification('User should be able to login.');
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Click Search icon at top right corner of page beside the username of logged in user');
        await HomePageHelper.clickSearchButton();
        StepLogger.verification('Search box is displayed');
        await HomePageHelper.verifySearchBox();

        StepLogger.stepId(3);
        StepLogger.step('Search for a contact');
        await HomePageHelper.enterSearchTextAndClicksearch(searchText);
        StepLogger.verification('Search result/results should be displayed in contact');
        await HomePageHelper.verifyContactCardIsDisplayed(searchText);

        StepLogger.stepId(4);
        StepLogger.step('Click on the contact card in search results');
        await HomePageHelper.clickOnSearchResult(searchText);
        StepLogger.verification('New tab with details of contact should be displayed');
        await ContactPageHelper.verifyOverviewIsDisplayed(false);

        StepLogger.stepId(5);
        StepLogger.step('Verify if "Admin" text is displayed at top left corner of page hovering over which displays "Corrections Utility"');
        await ContactPageHelper.closeSnapshotModal();
        await ContactPage.header.admin.hoverOver();
        StepLogger.verification('"Admin" text and "Corrections Utility" is missing');
        await ContactPage.header.correctionsUtility.verifyDisplayedStatus();

    });

    // Jira References - COTRAC-2113
    it('To verify that non-admin user cannot access "Add Institution" once access is revoked by admin user - [22981118]', async () => {
        // Auto generated by aurea-automation - util on Thu, 18 Apr 2019 13:56:51 GMT

        StepLogger.caseId = 22981118;
        StepLogger.stepId(1);
        StepLogger.step('Login to the Application with non-admin user whose access is revoked in Pre condition tc. [Test_ros_001/Test12345]');
        StepLogger.verification('User should be able to login.');
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Click Administration from left pane');
        await HomePageHelper.clickAdministrationLink();
        StepLogger.verification('Sub options under Administration are displayed');
        await HomePageHelper.verifyOptionsUnderAdministration();

        StepLogger.stepId(3);
        StepLogger.step('Click Configuration and verify if Outside Institutions is displayed');
        await HomePage1Helper.navigateConfigurationOutsideInstitutions();
        StepLogger.verification('Outside Institutions should not be displayed');
        await OutsideInstitutionHelper.verifyManageOutsideInstitutionPage();
    });

    // Jira References - COTRAC-2113
    it('To verify that non-admin user cannot access "Case Areas" once access is revoked by admin user - [22981121]', async () => {
        // Auto generated by aurea-automation - util on Thu, 18 Apr 2019 13:56:51 GMT

        StepLogger.caseId = 22981121;
        StepLogger.stepId(1);
        StepLogger.step('Login to the Application with non-admin user whose access is revoked in Pre condition tc. [Test_ros_001/Test12345]');
        StepLogger.verification('User should be able to login.');
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Click Administration from left pane');
        await HomePageHelper.clickAdministrationLink();
        StepLogger.verification('Sub options under Administration are displayed');
        await HomePageHelper.verifyOptionsUnderAdministration();

        StepLogger.stepId(3);
        StepLogger.step('Verify if Case Areas is displayed under Service Center');
        await HomePage1Helper.navigateServiceCenterCaseAreas();
        StepLogger.verification('Case Areas should not be present');
        await CaseAreasHelper.verifyCaseAreasPageDisplayed();
    });

    // Jira References - COTRAC-2113
    it('To verify that non-admin user cannot access "Compensation" once access is revoked by admin user - [22981124]', async () => {
        // Auto generated by aurea-automation - util on Thu, 18 Apr 2019 13:56:52 GMT

        StepLogger.caseId = 22981124;
        StepLogger.stepId(1);
        StepLogger.step('Login to the Application with non-admin user whose access is revoked in Pre condition tc. [Test_ros_001/Test12345]');
        StepLogger.verification('User should be able to login.');
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Click Administration from left pane');
        await HomePageHelper.clickAdministrationLink();
        StepLogger.verification('Sub options under Administration are displayed');
        await HomePageHelper.verifyOptionsUnderAdministration();

        StepLogger.stepId(3);
        StepLogger.step('Verify if Compensation is displayed under Administration');
        await HomePage1Helper.clickCompensationAdministration();
        StepLogger.verification('Compensation should not be displayed');
        await ManageCompensationPageHelper.verifyManageCompensationPageDisplayed();
    });

    // Jira References - COTRAC-2113
    it('To verify that non-admin user cannot access "Application Status" once access is revoked by admin user - [22981119]', async () => {
        // Auto generated by aurea-automation - util on Thu, 18 Apr 2019 13:56:52 GMT

        StepLogger.caseId = 22981119;
        StepLogger.stepId(1);
        StepLogger.step('Login to the Application with non-admin user whose access is revoked in Pre condition tc. [Test_ros_001/Test12345]');
        StepLogger.verification('User should be able to login.');
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Click Administration from left pane');
        await HomePageHelper.clickAdministrationLink();
        StepLogger.verification('Sub options under Administration are displayed');
        await HomePageHelper.verifyOptionsUnderAdministration();

        StepLogger.stepId(3);
        StepLogger.step('Click System and verify if Application Status is displayed');
        await HomePage1Helper.navigateSystemApplicationStatus();
        StepLogger.verification('Application Status should not be displayed');
        await ApplicationStatusHelper.verifyApplicationStatusPageDisplayed();
    });

    // Jira References - COTRAC-2113
    it('To verify that non-admin user cannot access "Branches" once access is revoked by admin user - [22981120]', async () => {
        // Auto generated by aurea-automation - util on Thu, 18 Apr 2019 13:56:52 GMT

        StepLogger.caseId = 22981120;
        StepLogger.stepId(1);
        StepLogger.step('Login to the Application with non-admin user whose access is revoked in Pre condition tc. [Test_ros_001/Test12345]');
        StepLogger.verification('User should be able to login.');
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Click Administration from left pane');
        await HomePageHelper.clickAdministrationLink();
        StepLogger.verification('Sub options under Administration are displayed');
        await HomePageHelper.verifyOptionsUnderAdministration();

        StepLogger.stepId(3);
        StepLogger.step('Verify if Branches is displayed under Organization');
        await HomePage1Helper.navigateOrganizationBranches();
        StepLogger.verification('Branches should not be displayed under Organization');
        await BranchesHelper.verifyManageBranchesPageDisplayed();
    });

    // Jira References - COTRAC-2113
    it('To verify that non-admin user cannot access "Custom Items" once access is revoked by admin user - [22981128]', async () => {
        // Auto generated by aurea-automation - util on Thu, 18 Apr 2019 13:56:52 GMT

        StepLogger.caseId = 22981128;
        StepLogger.stepId(1);
        StepLogger.step('Login to the Application with non-admin user whose access is revoked in Pre condition tc. [Test_ros_001/Test12345]');
        StepLogger.verification('User should be able to login.');
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Click Administration from left pane');
        await HomePageHelper.clickAdministrationLink();
        StepLogger.verification('Sub options under Administration are displayed');
        await HomePageHelper.verifyOptionsUnderAdministration();

        StepLogger.stepId(3);
        StepLogger.step('Verify if Custom Items is displayed under Configuration');
        await HomePage1Helper.navigateConfigurationCustomItems();
        StepLogger.verification('Custom Items should be missing under Configuration');
        await CustomItemHelper.verifyCustomItemPageDisplayed();
    });
});
