import { StepLogger } from '../../../../../core/logger/step-logger';
import { PageHelper } from '../../../../components/html/page-helper';
import { RelationshipsConstants } from '../../../../page-objects/pages/administration/configuration/relationships/relationships.constants';
import { RelationshipsHelper } from '../../../../page-objects/pages/administration/configuration/relationships/relationships.helper';
import { HomePageHelper } from '../../../../page-objects/pages/home-page/home-page.helper';
import { HomePage1Helper } from '../../../../page-objects/pages/home-page/home-page1.helper';
import { LoginPageHelper } from '../../../../page-objects/pages/login-page/login-page.helper';
import { SuiteNames } from '../../../helpers/suite-names';

describe(SuiteNames.regressionSuite, () => {
    let loginPageHelper: LoginPageHelper;

    beforeAll(async () => {
        loginPageHelper = LoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
    });

    beforeEach(async () => {
        await loginPageHelper.goTo();
        await LoginPageHelper.loginAsAdmin();
    });

    it('To verify that the user is able to navigate to Manage Relationships page - [22737951]', async () => {
        // Auto generated by aurea-automation - util on Mon, 08 Apr 2019 01:44:53 GMT

        StepLogger.caseId = 22737951;
        StepLogger.stepId(1);
        StepLogger.step('Click "Administration" link displayed in the left panel.');
        await HomePageHelper.clickAdministrationLink();
        StepLogger.verification('Option available under administration section should be displayed.');
        await HomePageHelper.verifyOptionsUnderAdministration();

        StepLogger.stepId(2);
        StepLogger.step('Click "Configuration" displayed under administration');
        await HomePageHelper.clickConfigurationUnderAdministration();
        StepLogger.verification('Items available under Configuration should be displayed.');
        await HomePageHelper.verifyOptionsUnderConfiguration();

        StepLogger.stepId(3);
        StepLogger.step('Click "Relationships"');
        await HomePage1Helper.clickRelationshipsUnderConfiguration();
        StepLogger.verification('Manage Relationships should be displayed.');
        await RelationshipsHelper.verifyRelationshipsManagePageDisplayed();
    });

    it('To verify the list of Items in Grid on Manage Relationships Page - [22745316]', async () => {
        // Auto generated by aurea-automation - util on Mon, 08 Apr 2019 04:38:13 GMT

        StepLogger.caseId = 22745316;
        StepLogger.stepId(1);
        StepLogger.step('Go to "Administration - > Configuration " displayed under administration.');
        await HomePageHelper.clickAdministrationLink();
        await HomePageHelper.clickConfigurationUnderAdministration();
        StepLogger.verification('Items available under Configuration should be displayed');
        await HomePageHelper.verifyOptionsUnderConfiguration();

        StepLogger.stepId(2);
        StepLogger.step('Click Relationships');
        await HomePage1Helper.clickRelationshipsUnderConfiguration();
        StepLogger.verification('Manage Relationships page is displayed in right pane');
        await RelationshipsHelper.verifyRelationshipsManagePageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Verify the Items displayed in the grid.');
        StepLogger.verification(`Below items are displayed :
        - Code
        - Description
        - Primary
        - Sort Order
        - Active`);
        await RelationshipsHelper.verifyItemGridsInRelationshipsPage();
    });

    it('To verify the buttons available on "Manage Relationships" page - [22746158]', async () => {
        // Auto generated by aurea-automation - util on Mon, 08 Apr 2019 05:25:24 GMT

        StepLogger.caseId = 22746158;
        StepLogger.stepId(1);
        StepLogger.step('Go to "Administration - > Configuration " displayed under administration.');
        await HomePageHelper.clickAdministrationLink();
        await HomePageHelper.clickConfigurationUnderAdministration();
        StepLogger.verification('Items available under Configuration should be displayed');
        await HomePageHelper.verifyOptionsUnderConfiguration();

        StepLogger.stepId(2);
        StepLogger.step('Click Relationships');
        await HomePage1Helper.clickRelationshipsUnderConfiguration();
        StepLogger.verification('Manage Relationships page is displayed in right pane');
        await RelationshipsHelper.verifyRelationshipsManagePageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Verify the buttons available on Manage Relationships page');
        StepLogger.verification(`Below buttons are available:
        - Add Relationship
        - Refresh
        - Export to Excel
        - Export to Word`);
        await RelationshipsHelper.verifyButtons();
    });

    it('To verify user is able to navigate to "New Relationship" window - [22777261]', async () => {
        // Auto generated by aurea-automation - util on Mon, 08 Apr 2019 05:25:24 GMT

        StepLogger.caseId = 22777261;
        StepLogger.stepId(1);
        StepLogger.step('Go to "Administration - > Configuration " displayed under administration.');
        await HomePageHelper.clickAdministrationLink();
        await HomePageHelper.clickConfigurationUnderAdministration();
        StepLogger.verification('Items available under Configuration should be displayed');
        await HomePageHelper.verifyOptionsUnderConfiguration();

        StepLogger.stepId(2);
        StepLogger.step('Click Relationships');
        await HomePage1Helper.clickRelationshipsUnderConfiguration();
        StepLogger.verification('Manage Relationships page is displayed in right pane');
        await RelationshipsHelper.verifyRelationshipsManagePageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click Add Relationship button');
        await RelationshipsHelper.clickOnAddRelationshipButton();
        StepLogger.verification('New Relationship window is displayed');
        await RelationshipsHelper.verifyNewRelationshipScreen();
    });

    it('To verify that the validation error message is displayed when all the mandatory fields are left blank - [22777262]', async () => {
        // Auto generated by aurea-automation - util on Mon, 08 Apr 2019 07:24:30 GMT

        StepLogger.caseId = 22777262;
        const error = RelationshipsConstants.errorMessages.code;

        StepLogger.stepId(1);
        StepLogger.step('Go to "Administration - > Configuration " displayed under administration.');
        await HomePageHelper.clickAdministrationLink();
        await HomePageHelper.clickConfigurationUnderAdministration();
        StepLogger.verification('Items available under Configuration should be displayed');
        await HomePageHelper.verifyOptionsUnderConfiguration();

        StepLogger.stepId(2);
        StepLogger.step('Click Relationships');
        await HomePage1Helper.clickRelationshipsUnderConfiguration();
        StepLogger.verification('Manage Relationships page is displayed in right pane');
        await RelationshipsHelper.verifyRelationshipsManagePageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click Add Relationship button');
        await RelationshipsHelper.clickOnAddRelationshipButton();
        StepLogger.verification('New Relationship window is displayed');
        await RelationshipsHelper.verifyNewRelationshipScreen();

        StepLogger.stepId(4);
        StepLogger.step('Click "save" leaving all the mandatory fields blank.');
        await RelationshipsHelper.clickOnSaveButton();
        StepLogger.verification('Validation Error message should be displayed');
        await RelationshipsHelper.verifyValidationErrorMessage(error);
    });
});
