import { StepLogger } from '../../../../../core/logger/step-logger';
import { PageHelper } from '../../../../components/html/page-helper';
import { HomePageOneHelper } from '../../../../page-objects/pages/home-page/home-page-one.helper';
import { HomePageHelper } from '../../../../page-objects/pages/home-page/home-page.helper';
import { HomePage } from '../../../../page-objects/pages/home-page/home-page.po';
import { LoginPageHelper } from '../../../../page-objects/pages/login-page/login-page.helper';
import { NewTaskPageConstant } from '../../../../page-objects/pages/new-task-page/new-task-page.constants';
import { NewTaskPageHelper } from '../../../../page-objects/pages/new-task-page/new-task-page.helper';
import { TasksQueuePageHelper } from '../../../../page-objects/pages/tasks-queue-page/tasks-queue-page.helper';
import { SuiteNames } from '../../../helpers/suite-names';

describe(SuiteNames.regressionSuite, () => {
    let loginPageHelper: LoginPageHelper;

    beforeAll(async () => {
        loginPageHelper = LoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
    });

    beforeEach(async () => {
        await PageHelper.restartBrowser();
        await loginPageHelper.goTo();
    });

    // Jira References - COTRAC-139
    it('Verify the functionality of close button on new task page - [22915272]', async () => {
        // Auto generated by aurea-automation - util on Fri, 29 Mar 2019 05:07:38 GMT

        StepLogger.caseId = 22915272;
        StepLogger.preCondition('Execute C22395398 to login as an administrator');
        await LoginPageHelper.loginAsAdmin();
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        StepLogger.stepId(1);
        StepLogger.step('Expand the Queues menu in the left panel and click Tasks menu');
        await HomePageOneHelper.expandQueueAndClickTask();
        StepLogger.verification('Tasks Queue page should be displayed');
        await TasksQueuePageHelper.verifyTasksQueuePageDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Click on the Add Task icon (notepad+ sign) in top left of the Tasks Queue page');
        await TasksQueuePageHelper.clickAddTaskIcon();
        StepLogger.verification('New Tasks page should be displayed');
        await NewTaskPageHelper.verifyNewTaskPageIsDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click Close icon on top right of the page');
        await NewTaskPageHelper.clickClose();
        StepLogger.verification(
            'Warning message should be displayed " Are you sure you want to leave this page? Unsaved changes will be lost."'
        );
        await NewTaskPageHelper.verifyConfirmWindow();

        StepLogger.stepId(4);
        StepLogger.step('Click OK');
        await NewTaskPageHelper.clickDialogOk();
        StepLogger.verification('New Task page should get closed and user should be navigated back to Tasks Queue page');
        await TasksQueuePageHelper.verifyTasksQueuePageDisplayed();
    });

    // Jira References - COTRAC-139
    it('Verify that the User can access New Task window via Tasks Queue page - [22915256]', async () => {
        // Auto generated by aurea-automation - util on Fri, 29 Mar 2019 05:07:38 GMT

        StepLogger.caseId = 22915256;
        StepLogger.preCondition('Execute C22395398 to login as an administrator');
        await LoginPageHelper.loginAsAdmin();
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        StepLogger.stepId(1);
        StepLogger.step('Expand the Queues menu in the left panel.');
        await HomePageHelper.clickQueuesLink();
        StepLogger.verification('Queues menu should get expanded');
        await HomePageHelper.verifyQueuesMenuIsExpanded();

        StepLogger.stepId(2);
        StepLogger.step('Verify Tasks menu option is displayed under Queues menu');
        StepLogger.verification('Tasks menu option should be displayed under Queues menu');
        await HomePageHelper.verifyOptionsDisplayedUnderQueues();

        StepLogger.stepId(3);
        StepLogger.step('Click on the Tasks menu');
        await HomePageHelper.clickTasksUnderQueues();
        StepLogger.verification('Tasks Queue page should be displayed');
        await TasksQueuePageHelper.verifyTasksQueuePageDisplayed();

        StepLogger.stepId(4);
        StepLogger.step('Click on the Add Task icon (notepad+ sign) in top left of the Tasks Queue page');
        await TasksQueuePageHelper.clickAddTaskIcon();
        StepLogger.verification('New Tasks page should be displayed');
        await NewTaskPageHelper.verifyNewTaskPageIsDisplayed();
    });

    // Jira References - COTRAC-139
    it('Verify validation message when user clicks save without entering any values on Add Task page - [22915278]', async () => {
        // Auto generated by aurea-automation - util on Fri, 29 Mar 2019 05:07:38 GMT

        StepLogger.caseId = 22915278;
        StepLogger.preCondition('Execute C22395398 to login as an administrator');
        await LoginPageHelper.loginAsAdmin();
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        StepLogger.stepId(1);
        StepLogger.step('Expand the Queues menu in the left panel and click Tasks menu');
        await HomePageOneHelper.expandQueueAndClickTask();
        StepLogger.verification('Tasks Queue page should be displayed');
        await TasksQueuePageHelper.verifyTasksQueuePageDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Click on the Add Task icon (notepad+ sign) in top left of the Tasks Queue page');
        await TasksQueuePageHelper.clickAddTaskIcon();
        StepLogger.verification('New Tasks page should be displayed');
        await NewTaskPageHelper.verifyNewTaskPageIsDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click Save icon on top right of the page');
        await NewTaskPageHelper.clickSave();
        StepLogger.verification('Error message should be displayed for Subject field as "SUBJECT is required"');
        await NewTaskPageHelper.verifySubjectIsRequired();
    });

    // Jira References - COTRAC-139
    it('Verify that the User attributes and buttons in New Task window - [22915260]', async () => {
        // Auto generated by aurea-automation - util on Fri, 29 Mar 2019 05:07:38 GMT

        StepLogger.caseId = 22915260;
        StepLogger.preCondition('New Tasks page should be already displayed C22915256');
        await NewTaskPageHelper.navigateToNewTask();

        StepLogger.stepId(1);
        StepLogger.step('Verify the attributes in New Tasks page');
        StepLogger.verification(`Following attributes should be displayed under Overview tab Details section
            SUBJECT, OWNER, DATE START, DATE DUE, STATUS, DESCRIPTION and SYNC TO OUTLOOK option`);
        await NewTaskPageHelper.verifyAttributes();

        StepLogger.stepId(2);
        StepLogger.step('Verify mandatory attributes in New Tasks page');
        StepLogger.verification('SUBJECT, OWNER, DATE START, STATUS attributes should be marked with * indicating mandatory fields');
        await NewTaskPageHelper.verifyMandatoryAttributes();

        StepLogger.stepId(3);
        StepLogger.step('Verify Save and Close buttons on top right of the page');
        StepLogger.verification('Save and Close buttons should appear on top right of the page');
        await NewTaskPageHelper.verifySaveAndClose();
    });

    // Jira References - COTRAC-139
    it('Verify validation error message when user select Start date after Due date - [22915284]', async () => {
        // Auto generated by aurea-automation - util on Fri, 29 Mar 2019 05:07:39 GMT

        StepLogger.caseId = 22915284;
        const uniqueText = await PageHelper.getUniqueId();

        StepLogger.preCondition('Execute C22395398 to login as an administrator');
        await LoginPageHelper.loginAsAdmin();
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        StepLogger.stepId(1);
        StepLogger.step('Expand the Queues menu in the left panel and click Tasks menu');
        await HomePageOneHelper.expandQueueAndClickTask();
        StepLogger.verification('Tasks Queue page should be displayed');
        await TasksQueuePageHelper.verifyTasksQueuePageDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Click on the Add Task icon (notepad+ sign) in top left of the Tasks Queue page');
        await TasksQueuePageHelper.clickAddTaskIcon();
        StepLogger.verification('New Tasks page should be displayed');
        await NewTaskPageHelper.verifyNewTaskPageIsDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Enter Subject for the Task');
        await NewTaskPageHelper.enterSubject(uniqueText);
        StepLogger.verification('Entered values should be displayed');
        await NewTaskPageHelper.verifySubjectIsEntered(uniqueText);

        StepLogger.stepId(4);
        StepLogger.step('From the OWNER dropdown list select "QUEUE"');
        await NewTaskPageHelper.selectOwner(NewTaskPageConstant.queue);
        StepLogger.verification('Queue should get selected for Owner');
        await NewTaskPageHelper.verifyEnteredOwnerIsSelected(NewTaskPageConstant.queue);

        StepLogger.stepId(5);
        StepLogger.step('Enter Date Start after the Date Due from the Date time pickers');
        StepLogger.verification('Selected Date time values should be displayed in Date Start and Date Due fields');
        await NewTaskPageHelper.enterStartDateAfterDueAndVerify();

        StepLogger.stepId(6);
        StepLogger.step('Click Save icon on top right of the page');
        await NewTaskPageHelper.clickSave();
        StepLogger.verification('Validation Error message should be displayed "Date Start is invalid." beside the Date Start field');
        await NewTaskPageHelper.verifyInvalidStartDate();
    });

    // Jira References - COTRAC-139
    it('Verify that user can Create a queue task with "Sync to Outlook" option ON - [22915401]', async () => {
        // Auto generated by aurea-automation - util on Fri, 29 Mar 2019 05:07:39 GMT

        StepLogger.caseId = 22915401;
        const uniqueText = await PageHelper.getUniqueId();

        StepLogger.preCondition('Execute C22395398 to login as an administrator');
        await LoginPageHelper.loginAsAdmin();
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        StepLogger.stepId(1);
        StepLogger.step('Expand the Queues menu in the left panel and click Tasks menu');
        await HomePageOneHelper.expandQueueAndClickTask();
        StepLogger.verification('Tasks Queue page should be displayed');
        await TasksQueuePageHelper.verifyTasksQueuePageDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Click on the Add Task icon (notepad+ sign) in top left of the Tasks Queue page');
        await TasksQueuePageHelper.clickAddTaskIcon();
        StepLogger.verification('New Tasks page should be displayed');
        await NewTaskPageHelper.verifyNewTaskPageIsDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Enter Subject for the Task');
        await NewTaskPageHelper.enterSubject(uniqueText);
        StepLogger.verification('Entered values should be displayed');
        await NewTaskPageHelper.verifySubjectIsEntered(uniqueText);

        StepLogger.stepId(4);
        StepLogger.step('From the OWNER dropdown list select "QUEUE"');
        await NewTaskPageHelper.selectOwner(NewTaskPageConstant.queue);
        StepLogger.verification('Queue should get selected for Owner');
        await NewTaskPageHelper.verifyEnteredOwnerIsSelected(NewTaskPageConstant.queue);

        StepLogger.stepId(5);
        StepLogger.step('Select Task and Branch values from the dropdown lists');
        await NewTaskPageHelper.selectTaskAndBranch(NewTaskPageConstant.taskQueueForEmail, NewTaskPageConstant.cornell);
        StepLogger.verification('Selected values should be displayed');
        await NewTaskPageHelper.verifyEnteredTaskAndBranchAreSelected(NewTaskPageConstant.taskQueueForEmail, NewTaskPageConstant.cornell);

        StepLogger.stepId(6);
        StepLogger.step('Enter Date Start and Date Due from the Date time pickers');
        StepLogger.verification('Selected Date time values should be displayed in Date Start and Date Due fields');
        await NewTaskPageHelper.enterDatesAndVerify();

        StepLogger.stepId(7);
        StepLogger.step('Verify that "Undetermined" is selected by default in status field');
        StepLogger.verification('"Undetermined" should be selected by default in status field');
        await NewTaskPageHelper.verifyEnteredStatusIsSelected(NewTaskPageConstant.undetermined);

        StepLogger.stepId(8);
        StepLogger.step('Enter values for Description');
        await NewTaskPageHelper.enterDescription(uniqueText);
        StepLogger.verification('Entered values should be displayed');
        await NewTaskPageHelper.verifyEnteredDescription(uniqueText);

        StepLogger.stepId(9);
        StepLogger.step('Change the "SYNC TO OUTLOOK" to yes');
        await NewTaskPageHelper.clickSyncToOutLookOff();
        StepLogger.verification('"SYNC TO OUTLOOK" value should get changed to yes');
        await NewTaskPageHelper.verifySyncToOutLookOn();

        StepLogger.stepId(10);
        StepLogger.step('Click Save icon on top right of the page');
        await NewTaskPageHelper.clickSaveAndClose();
        StepLogger.verification(`1. Task should be saved
            2. New Task page should get closed
            3. Created new Task should be displayed in Tasks Queue page`);
        await TasksQueuePageHelper.verifyTaskIsSavedAndDisplayedUnderTaskQueue(uniqueText);
    });

    // Jira References - COTRAC-139
    it('Verify that user can Create a queue task with status "Accepted/In progress" - [22915450]', async () => {
        // Auto generated by aurea-automation - util on Fri, 29 Mar 2019 05:07:39 GMT

        StepLogger.caseId = 22915450;
        const uniqueText = await PageHelper.getUniqueId();

        StepLogger.preCondition('Execute C22395398 to login as an administrator');
        await LoginPageHelper.loginAsAdmin();
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        StepLogger.stepId(1);
        StepLogger.step('Expand the Queues menu in the left panel and click Tasks menu');
        await HomePageOneHelper.expandQueueAndClickTask();
        StepLogger.verification('Tasks Queue page should be displayed');
        await TasksQueuePageHelper.verifyTasksQueuePageDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Click on the Add Task icon (notepad+ sign) in top left of the Tasks Queue page');
        await TasksQueuePageHelper.clickAddTaskIcon();
        StepLogger.verification('New Tasks page should be displayed');
        await NewTaskPageHelper.verifyNewTaskPageIsDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Enter Subject for the Task');
        await NewTaskPageHelper.enterSubject(uniqueText);
        StepLogger.verification('Entered values should be displayed');
        await NewTaskPageHelper.verifySubjectIsEntered(uniqueText);

        StepLogger.stepId(4);
        StepLogger.step('From the OWNER dropdown list select "QUEUE"');
        await NewTaskPageHelper.selectOwner(NewTaskPageConstant.queue);
        StepLogger.verification('Queue should get selected for Owner');
        await NewTaskPageHelper.verifyEnteredOwnerIsSelected(NewTaskPageConstant.queue);

        StepLogger.stepId(5);
        StepLogger.step('Select Task and Branch values from the dropdown lists');
        await NewTaskPageHelper.selectTaskAndBranch(NewTaskPageConstant.taskQueueForEmail, NewTaskPageConstant.cornell);
        StepLogger.verification('Selected values should be displayed');
        await NewTaskPageHelper.verifyEnteredTaskAndBranchAreSelected(NewTaskPageConstant.taskQueueForEmail, NewTaskPageConstant.cornell);

        StepLogger.stepId(6);
        StepLogger.step('Enter Date Start and Date Due from the Date time pickers');
        StepLogger.verification('Selected Date time values should be displayed in Date Start and Date Due fields');
        await NewTaskPageHelper.enterDatesAndVerify();

        StepLogger.stepId(7);
        StepLogger.step('Select Status field "Accepted/In progress" from Status menu dropdown');
        await NewTaskPageHelper.selectStatus(NewTaskPageConstant.acceptedInProgress);
        StepLogger.verification('"Accepted/In progress" should be selected for status field and Date Completed field should be displayed');
        await NewTaskPageHelper.verifyEnteredStatusIsSelected(NewTaskPageConstant.acceptedInProgress);

        StepLogger.stepId(8);
        StepLogger.step('Enter values for Description');
        await NewTaskPageHelper.enterDescription(uniqueText);
        StepLogger.verification('Entered values should be displayed');
        await NewTaskPageHelper.verifyEnteredDescription(uniqueText);

        StepLogger.stepId(9);
        StepLogger.step('Click Save icon on top right of the page');
        await NewTaskPageHelper.clickSaveAndClose();
        StepLogger.verification(`1. Task should be saved
            2. New Task page should get closed
            3. Created new Task should be displayed in Tasks Queue page`);
        await TasksQueuePageHelper.verifyTaskIsSavedAndDisplayedUnderTaskQueue(uniqueText);
    });
});
