import { StepLogger } from '../../../../core/logger/step-logger';
import { PageHelper } from '../../../components/html/page-helper';
import {
    ReferralSourcesConstant
} from '../../../page-objects/pages/administration/configuration/referral-sources/referral-sources.constants';
import {
    ReferralSourcesHelper
} from '../../../page-objects/pages/administration/configuration/referral-sources/referral-sources.helper';
import { HomePageHelper } from '../../../page-objects/pages/home-page/home-page.helper';
import { LoginPageHelper } from '../../../page-objects/pages/login-page/login-page.helper';
import { SuiteNames } from '../../helpers/suite-names';

describe(SuiteNames.regressionSuite, () => {
    let loginPageHelper: LoginPageHelper;
    const referralActive = `${ReferralSourcesConstant.elementNames.test}${PageHelper.getUniqueId()}${PageHelper.getUniqueId()}`;
    const referralInactive = `${ReferralSourcesConstant.elementNames.test}${PageHelper.getUniqueId()}${PageHelper.getUniqueId()}`;

    beforeAll(async () => {
        loginPageHelper = LoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
    });

    beforeEach(async () => {
        await PageHelper.restartBrowser();
        await loginPageHelper.goTo();
        await LoginPageHelper.loginAsAdmin();
    });

    // Jira References - COTRAC-3595
    it('To verify that the user is able to navigate to Manage Referral Sources page - [22958231]', async () => {
        // Auto generated by aurea-automation - util on Thu, 28 Mar 2019 08:43:53 GMT
        StepLogger.caseId = 22958231;

        StepLogger.stepId(1);
        StepLogger.step('Click "Administration" link displayed in the left panel.');
        await HomePageHelper.clickAdministrationLink();
        StepLogger.verification('Option available under administration section should be displayed.');
        await HomePageHelper.verifyOptionsUnderAdministration();

        StepLogger.stepId(2);
        StepLogger.step('Click "Configuration" displayed under administration');
        await HomePageHelper.clickConfigurationUnderAdministration();
        StepLogger.verification('Items available under Configuration should be displayed.');
        await HomePageHelper.verifyOptionsUnderConfiguration();

        StepLogger.stepId(3);
        StepLogger.step('Click "Referral Sources"');
        await HomePageHelper.clickReferralSourcesUnderConfigurationUnderAdministration();
        StepLogger.verification('Manage Referral Sources page is displayed');
        await ReferralSourcesHelper.verifyReferralSourcesPageDisplayed();
    });

    // Jira References - COTRAC-3597
    it('To verify the buttons available on Manage Referral Sources page - [22958236]', async () => {
        // Auto generated by aurea-automation - util on Thu, 28 Mar 2019 10:57:11 GMT
        StepLogger.caseId = 22958236;

        StepLogger.preCondition('Navigate to Administration');
        await ReferralSourcesHelper.navigateToAdministration();

        StepLogger.stepId(1);
        StepLogger.step('Go to "Administration - > Configuration " displayed under administration.');
        await HomePageHelper.clickConfigurationUnderAdministration();
        StepLogger.verification('Items available under Configuration should be displayed');
        await HomePageHelper.verifyOptionsUnderConfiguration();

        StepLogger.stepId(2);
        StepLogger.step('Click Referral Sources');
        await HomePageHelper.clickReferralSourcesUnderConfigurationUnderAdministration();
        StepLogger.verification('Manage Referral Sources page is displayed in right pane');
        await ReferralSourcesHelper.verifyReferralSourcesPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Verify the buttons displayed');
        StepLogger.verification(`Below buttons should be present:
            - Add Referral Sources
            - Refresh
            - Export to Excel
            - Export to Word`);
        await ReferralSourcesHelper.verifyPageButtons();
    });

    // Jira References - COTRAC-3596
    it('To verify user is able to navigate to "New Referral Source" window - [22958242]', async () => {
        // Auto generated by aurea-automation - util on Thu, 28 Mar 2019 08:57:14 GMT
        StepLogger.caseId = 22958242;

        StepLogger.preCondition('Navigate to Administration');
        await ReferralSourcesHelper.navigateToAdministration();

        StepLogger.stepId(1);
        StepLogger.step('Go to "Administration - > Configuration " displayed under administration.');
        await HomePageHelper.clickConfigurationUnderAdministration();
        StepLogger.verification('Items available under Configuration should be displayed');
        await HomePageHelper.verifyOptionsUnderConfiguration();

        StepLogger.stepId(2);
        StepLogger.step('Click Referral Sources');
        await HomePageHelper.clickReferralSourcesUnderConfigurationUnderAdministration();
        StepLogger.verification('Manage Referral Sources page is displayed in right pane');
        await ReferralSourcesHelper.verifyReferralSourcesPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click "Add Referral Sources" button');
        await ReferralSourcesHelper.clickAddReferralSource();
        StepLogger.verification('"New Referral Source" window is displayed');
        await ReferralSourcesHelper.verifyReferralSourceDialog();
    });

    // Jira References - COTRAC-3598
    it('To verify contents of "New Referral Source" window - [22958243]', async () => {
        // Auto generated by aurea-automation - util on Thu, 28 Mar 2019 11:05:23 GMT
        StepLogger.caseId = 22958243;

        StepLogger.preCondition('Navigate to Referral Sources and click Add');
        await ReferralSourcesHelper.navigateToReferralSources();
        await ReferralSourcesHelper.clickAddReferralSource();

        StepLogger.stepId(1);
        StepLogger.step('Verify the fields present');
        StepLogger.verification(`Below fields are present:
            - Referral Source
            - Status`);
        await ReferralSourcesHelper.verifyReferralDialogFields(true);

        StepLogger.stepId(2);
        StepLogger.step('Verify if close icon is present on window');
        StepLogger.verification('Close icon is present at top right corner of window');
        await ReferralSourcesHelper.verifyCloseIcon();

        StepLogger.stepId(3);
        StepLogger.step('Verify the buttons present');
        StepLogger.verification('"Save" and "Cancel" buttons are present');
        await ReferralSourcesHelper.verifyReferralDialogButtons(true);
    });

    // Jira References - COTRAC-3590
    it('To verify that the validation error message is displayed when Referral Source is left blank - [22958246]', async () => {
        // Auto generated by aurea-automation - util on Thu, 28 Mar 2019 09:08:33 GMT
        StepLogger.caseId = 22958246;

        StepLogger.preCondition('Navigate to Referral Sources');
        await ReferralSourcesHelper.navigateToReferralSources();

        StepLogger.stepId(1);
        StepLogger.step('Click Add Referral Sources button');
        await ReferralSourcesHelper.clickAddReferralSource();
        StepLogger.verification('"New Referral Source" window is displayed');
        await ReferralSourcesHelper.verifyReferralSourceDialog();

        StepLogger.stepId(2);
        StepLogger.step('Verify "Referral Source" field is marked mandatory using an asterisk');
        StepLogger.verification('"Referral Source" field is marked mandatory using an asterisk');
        await ReferralSourcesHelper.verifyIconMandatory(true);

        StepLogger.stepId(3);
        StepLogger.step('Click Save button leaving "Referral Source" field blank');
        await ReferralSourcesHelper.clickSaveReferralSourceDialog();
        StepLogger.verification('Error message pop-up asking to enter Referral Source name is displayed');
        await ReferralSourcesHelper.verifyEnterNameDialog();
    });

    // Jira References - COTRAC-3591
    it('To verify that "New Referral Source" window is closed when clicked on close icon - [22958248]', async () => {
        // Auto generated by aurea-automation - util on Thu, 28 Mar 2019 09:34:39 GMT
        StepLogger.caseId = 22958248;

        StepLogger.preCondition('Navigate to Referral Sources');
        await ReferralSourcesHelper.navigateToReferralSources();

        StepLogger.stepId(1);
        StepLogger.step('Click Add Referral Sources button');
        await ReferralSourcesHelper.clickAddReferralSource();
        StepLogger.verification('"New Referral Source" window is displayed');
        await ReferralSourcesHelper.verifyReferralSourceDialog();

        StepLogger.stepId(2);
        StepLogger.step('Verify close icon is present at top right corner of window');
        StepLogger.verification('Close icon is present');
        await ReferralSourcesHelper.verifyCloseIcon();

        StepLogger.stepId(3);
        StepLogger.step('Click close icon');
        await ReferralSourcesHelper.clickCloseIcon();
        StepLogger.verification('Window is closed');
        await ReferralSourcesHelper.verifyReferralSourceDialogClosed();
    });

    // Jira References - COTRAC-3592
    it('To verify user is able to create new active referral source - [22958250]', async () => {
        // Auto generated by aurea-automation - util on Thu, 28 Mar 2019 09:42:33 GMT
        StepLogger.caseId = 22958250;

        StepLogger.preCondition('Navigate to Referral Sources');
        await ReferralSourcesHelper.navigateToReferralSources();

        StepLogger.stepId(1);
        StepLogger.step('Click Add Referral Sources button');
        await ReferralSourcesHelper.clickAddReferralSource();
        StepLogger.verification('"New Referral Source" window is displayed');
        await ReferralSourcesHelper.verifyReferralSourceDialog();

        StepLogger.stepId(2);
        StepLogger.step('Fill in value for "Referral Source" field');
        await ReferralSourcesHelper.enterReferralName(referralActive, true);
        StepLogger.verification('User is able to enter value for "Referral Source" field');
        await ReferralSourcesHelper.verifyReferralName(referralActive);

        StepLogger.stepId(3);
        StepLogger.step('Select "Active" from status field drop-down');
        await ReferralSourcesHelper.selectStatusOption(ReferralSourcesConstant.statusDropdown.active);
        StepLogger.verification('Status is set to "Active"');
        await ReferralSourcesHelper.verifyStatusSelectedOption(ReferralSourcesConstant.statusDropdown.active);

        StepLogger.stepId(4);
        StepLogger.step('Click Save button');
        await ReferralSourcesHelper.clickSaveReferralSourceDialog();
        StepLogger.verification('Window is closed and Referral source is saved');
        await ReferralSourcesHelper.verifyDialogClosedAndReferralSaved(referralActive);
    });

    // Jira References - COTRAC-3593
    it('To verify user is able to create new inactive referral source - [22958251]', async () => {
        // Auto generated by aurea-automation - util on Thu, 28 Mar 2019 10:06:03 GMT
        StepLogger.caseId = 22958251;

        StepLogger.preCondition('Navigate to Referral Sources');
        await ReferralSourcesHelper.navigateToReferralSources();

        StepLogger.stepId(1);
        StepLogger.step('Click Add Referral Sources button');
        await ReferralSourcesHelper.clickAddReferralSource();
        StepLogger.verification('"New Referral Source" window is displayed');
        await ReferralSourcesHelper.verifyReferralSourceDialog();

        StepLogger.stepId(2);
        StepLogger.step('Fill in value for "Referral Source" field');
        await ReferralSourcesHelper.enterReferralName(referralInactive, true);
        StepLogger.verification('User is able to enter value for "Referral Source" field');
        await ReferralSourcesHelper.verifyReferralName(referralInactive);

        StepLogger.stepId(3);
        StepLogger.step('Verify that default value in status field is set to "Inactive"');
        await ReferralSourcesHelper.selectStatusOption(ReferralSourcesConstant.statusDropdown.inactive);
        StepLogger.verification('Default value in status field is set to "Inactive"');
        await ReferralSourcesHelper.verifyStatusSelectedOption(ReferralSourcesConstant.statusDropdown.inactive);

        StepLogger.stepId(4);
        StepLogger.step('Click Save button');
        await ReferralSourcesHelper.clickSaveReferralSourceDialog();
        StepLogger.verification('Window is closed and Referral source is saved');
        await ReferralSourcesHelper.verifyDialogClosedAndReferralSaved(referralInactive);
    });

    // Jira References - COTRAC-3594
    it('To verify newly added referral source is displayed in grid on Manage Referral Sources page - [22958253]', async () => {
        // Auto generated by aurea-automation - util on Thu, 28 Mar 2019 10:08:55 GMT
        StepLogger.caseId = 22958253;

        StepLogger.preCondition('Navigate to Referral Sources');
        await ReferralSourcesHelper.navigateToReferralSources();

        // Step 1 has been covered in preCondition
        StepLogger.stepId(1);
        StepLogger.step('Verify that user is on Manage Referral Sources page');
        StepLogger.verification('User is on Manage Referral Sources page');

        StepLogger.stepId(2);
        StepLogger.step('Verify if referral source added in precondition test case is displayed in the grid');
        await ReferralSourcesHelper.searchReferral(referralActive);
        StepLogger.verification('Referral source is displayed in grid');
        await ReferralSourcesHelper.verifyReferralSaved(referralActive);

        StepLogger.stepId(3);
        StepLogger.step(`Verify if name of referral source displayed is correct and "Active" field checkbox is
            checked/unchecked depending on status marked as "Active" or "Inactive" respectively`);
        StepLogger.verification('Name is correct and Active field checked-box is appropriate');
        await ReferralSourcesHelper.verifyReferralNameAndStatus(referralActive);
    });
});
