import { StepLogger } from '../../../../../core/logger/step-logger';
import { PageHelper } from '../../../../components/html/page-helper';
import { DistrictsHelper } from '../../../../page-objects/pages/administration/organization/districts/districts.helper';
import { HomePageHelper } from '../../../../page-objects/pages/home-page/home-page.helper';
import { HomePage1Helper } from '../../../../page-objects/pages/home-page/home-page1.helper';
import { LoginPageHelper } from '../../../../page-objects/pages/login-page/login-page.helper';
import { SuiteNames } from '../../../helpers/suite-names';

describe(SuiteNames.regressionSuite, () => {
    let loginPageHelper: LoginPageHelper;

    beforeAll(async () => {
        loginPageHelper = LoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
    });

    beforeEach(async () => {
        await loginPageHelper.goTo();
        await LoginPageHelper.loginAsAdmin();
    });

    it('To verify that the user is able to navigate to Manage Districts page. - [22437183]', async () => {
        // Auto generated by aurea-automation - util on Mon, 25 Mar 2019 01:59:42 GMT

        StepLogger.caseId = 22437183;
        StepLogger.stepId(1);
        StepLogger.step('Click "Administration" link displayed in the left panel.');
        await HomePageHelper.clickAdministrationLink();
        StepLogger.verification('Option available under administration section should be displayed.');
        await HomePageHelper.verifyOptionsUnderAdministration();

        StepLogger.stepId(2);
        StepLogger.step('Click "Organization" displayed under administration.');
        await HomePageHelper.clickOrganizationUnderAdministration();
        StepLogger.verification('Item available under Organization should be displayed.');
        await HomePageHelper.optionsUnderOrganization();

        StepLogger.stepId(3);
        StepLogger.step('Click "Districts"');
        await HomePage1Helper.clickDistrictsUnderOrganization();
        StepLogger.verification('"Manage Districts" should be displayed.');
        await DistrictsHelper.verifyManageDistrictsPageDisplayed();
    });

    it('To verify the list of Items in Grid on Manage Districts Page - [22437184]', async () => {
        // Auto generated by aurea-automation - util on Mon, 25 Mar 2019 04:43:30 GMT

        StepLogger.caseId = 22437184;
        StepLogger.stepId(1);
        StepLogger.step('Go to  "Administration -> Organization" displayed under administration.');
        await HomePageHelper.clickAdministrationLink();
        await HomePageHelper.clickOrganizationUnderAdministration();
        StepLogger.verification('Item available under Organization should be displayed.');
        await HomePageHelper.optionsUnderOrganization();

        StepLogger.stepId(2);
        StepLogger.step('Click "Districts"');
        await HomePage1Helper.clickDistrictsUnderOrganization();
        StepLogger.verification('"Manage Districts" should be displayed.');
        await DistrictsHelper.verifyManageDistrictsPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Verify the Items displayed in the grid.');
        StepLogger.verification(`Following item should be displayed:
        1. District
        2. District Code
        3. Active`);
        await DistrictsHelper.verifyDistrictsPageItemsGrid();
    });

    it('To verify the button available on "Manage Districts page". - [22437185]', async () => {
        // Auto generated by aurea-automation - util on Mon, 25 Mar 2019 05:20:59 GMT

        StepLogger.caseId = 22437185;
        StepLogger.stepId(1);
        StepLogger.step('Go to  "Administration -> Organization" displayed under administration.');
        await HomePageHelper.clickAdministrationLink();
        await HomePageHelper.clickOrganizationUnderAdministration();
        StepLogger.verification('Item available under Organization should be displayed.');
        await HomePageHelper.optionsUnderOrganization();

        StepLogger.stepId(2);
        StepLogger.step('Click "Districts"');
        await HomePage1Helper.clickDistrictsUnderOrganization();
        StepLogger.verification('"Manage Districts" should be displayed.');
        await DistrictsHelper.verifyManageDistrictsPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('To verify the button available on "Manage Districts page".');
        StepLogger.verification(`Following options should be displayed.
        1. Add
        2. Refresh
        3. Export to Excel
        4. Export to Word`);
        await DistrictsHelper.verifyButtons();
    });

    it('To verify that user is able to navigate to "New District" page. - [22437193]', async () => {
        // Auto generated by aurea-automation - util on Mon, 25 Mar 2019 06:09:22 GMT

        StepLogger.caseId = 22437193;
        StepLogger.stepId(1);
        StepLogger.step('Go to  "Administration -> Organization" displayed under administration.');
        await HomePageHelper.clickAdministrationLink();
        await HomePageHelper.clickOrganizationUnderAdministration();
        StepLogger.verification('Item available under Organization should be displayed.');
        await HomePageHelper.optionsUnderOrganization();

        StepLogger.stepId(2);
        StepLogger.step('Click "Districts"');
        await HomePage1Helper.clickDistrictsUnderOrganization();
        StepLogger.verification('"Manage Districts" should be displayed.');
        await DistrictsHelper.verifyManageDistrictsPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click "Add District"');
        await DistrictsHelper.clickOnAddDistrict();
        StepLogger.verification('"New district" page should be displayed.');
        await DistrictsHelper.verifyNewDistrictsScreen();
    });

    it('To verify the functionality of cancel button on Add new district page. - [22437194]', async () => {
        // Auto generated by aurea-automation - util on Mon, 25 Mar 2019 06:33:18 GMT

        StepLogger.caseId = 22437194;
        StepLogger.stepId(1);
        StepLogger.step('Go to  "Administration -> Organization" displayed under administration.');
        await HomePageHelper.clickAdministrationLink();
        await HomePageHelper.clickOrganizationUnderAdministration();
        StepLogger.verification('Item available under Organization should be displayed.');
        await HomePageHelper.optionsUnderOrganization();

        StepLogger.stepId(2);
        StepLogger.step('Click "Districts"');
        await HomePage1Helper.clickDistrictsUnderOrganization();
        StepLogger.verification('"Manage Districts" should be displayed.');
        await DistrictsHelper.verifyManageDistrictsPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click "Add District"');
        await DistrictsHelper.clickOnAddDistrict();
        StepLogger.verification('"New district" page should be displayed.');
        await DistrictsHelper.verifyNewDistrictsScreen();

        StepLogger.stepId(4);
        StepLogger.step('Click "cancel"');
        await DistrictsHelper.clickOnCancelButton();
        StepLogger.verification('New district page should be closed and no district is created.');
        await DistrictsHelper.verifyNewDistrictsScreenClosed();
    });
});
