import { StepLogger } from '../../../../core/logger/step-logger';
import { PageHelper } from '../../../components/html/page-helper';
import { RolesConstants } from '../../../page-objects/pages/administration/security/roles/roles.constants';
import { RolesHelper } from '../../../page-objects/pages/administration/security/roles/roles.helper';
import { HomePageOneHelper } from '../../../page-objects/pages/home-page/home-page-one.helper';
import { HomePageHelper } from '../../../page-objects/pages/home-page/home-page.helper';
import { HomePage1Helper } from '../../../page-objects/pages/home-page/home-page1.helper';
import { LoginPageHelper } from '../../../page-objects/pages/login-page/login-page.helper';
import { YearQuartersPageHelper } from '../../../page-objects/pages/report-writer-reports-page/year-quarters-page/year-quarters-page.helper';
import { SuiteNames } from '../../helpers/suite-names';

describe(SuiteNames.regressionSuite, () => {
    let loginPageHelper: LoginPageHelper;

    beforeAll(async () => {
        loginPageHelper = LoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
    });

    beforeEach(async () => {
        await loginPageHelper.goTo();
        await LoginPageHelper.loginAsAdmin();
        await HomePageHelper.clickAdministrationLink();
        await HomePageHelper.verifyOptionsUnderAdministration();
        await HomePage1Helper.clickSecurityCenterUnderAdministration();
    });

    // Jira References - COTRAC-2268
    it('Verify Pagination is appearing on the page. - [22971600]', async () => {
        // Auto generated by aurea-automation - util on Fri, 12 Jul 2019 08:59:28 GMT

        StepLogger.caseId = 22971600;
        StepLogger.stepId(1);
        StepLogger.step('Verify user click on Role menu');
        await HomePageOneHelper.clickOnRolesUnderSecuritySubmenuUnderAdministrationMenu();
        StepLogger.verification('Manage Role page should open.');
        await RolesHelper.verifyRolesPageDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Verify columns appearing on the page.');
        // Handled in verification
        StepLogger.verification(`Following columns should be appearing on the page:
		Role
		Description
		Active
		Delete`);
        await RolesHelper.verifyColumnReporterPage();

        StepLogger.stepId(3);
        StepLogger.step('Verify pagination should be appearing at the end of the table');
        StepLogger.verification(`pagination should be appearing at the end of the table showing page number,
         total number of records on page and total no of records present.`);
        await YearQuartersPageHelper.verifyPaginationDisplayed();
        await YearQuartersPageHelper.verifyPaginationButtons();
        await YearQuartersPageHelper.verifyPageSizeDisplayed();
    });

    // Jira References - COTRAC-2268
    it('Verify Export to Excel button is appearing on the page. - [22971602]', async () => {
        // Auto generated by aurea-automation - util on Fri, 12 Jul 2019 09:52:39 GMT

        StepLogger.caseId = 22971602;
        StepLogger.stepId(1);
        StepLogger.step('Verify user click on Role menu');
        await HomePageOneHelper.clickOnRolesUnderSecuritySubmenuUnderAdministrationMenu();
        StepLogger.verification('Manage Role page should open.');
        await RolesHelper.verifyRolesPageDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Verify columns appearing on the page.');
        // Handled in verification
        StepLogger.verification(`Following columns should be appearing on the page:
	    Role
		Description
		Active
		Delete`);
        await RolesHelper.verifyColumnReporterPage();

        StepLogger.stepId(3);
        StepLogger.step('Verify Export to Excel button is appearing on the right top side of the page.');
        // Handled in verification
        StepLogger.verification('Export to Excel button should be appearing on the right top side of the page.');
        await RolesHelper.verifyExportToExcel();
    });

    // Jira References - COTRAC-2268
    it('Verify Export to Word button is appearing on the page. - [22971603]', async () => {
        // Auto generated by aurea-automation - util on Fri, 12 Jul 2019 09:59:41 GMT

        StepLogger.caseId = 22971603;
        StepLogger.stepId(1);
        StepLogger.step('Verify user click on Role menu');
        await HomePageOneHelper.clickOnRolesUnderSecuritySubmenuUnderAdministrationMenu();
        StepLogger.verification('Manage Role page should open.');
        await RolesHelper.verifyRolesPageDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Verify columns appearing on the page.');
        // Handled in verification
        StepLogger.verification(`Following columns should be appearing on the page:
		Role
		Description
		Active
		Delete`);
        await RolesHelper.verifyColumnReporterPage();

        StepLogger.stepId(3);
        StepLogger.step('Verify Export to Word button is appearing on the right top side of the page.');
        // Handled in verification
        StepLogger.verification('Export to Word button should be appearing on the right top side of the page.');
        await RolesHelper.verifyExportToWord();
    });

    // Jira References - COTRAC-2268
    it('Verify user clicks on the Export to Excel button - [22971605]', async () => {
        // Auto generated by aurea-automation - util on Fri, 12 Jul 2019 10:05:07 GMT

        StepLogger.caseId = 22971605;
        StepLogger.stepId(1);
        StepLogger.step('Verify user click on Role menu');
        await HomePageOneHelper.clickOnRolesUnderSecuritySubmenuUnderAdministrationMenu();
        StepLogger.verification('Manage Role page should open.');
        await RolesHelper.verifyRolesPageDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Verify columns appearing on the page.');
        // Handled in verification
        StepLogger.verification(`Following columns should be appearing on the page:
		Role
		Description
		Active
		Delete`);
        await RolesHelper.verifyColumnReporterPage();

        StepLogger.stepId(3);
        StepLogger.step('Verify Export to Excel button is appearing on the right top side of the page.');
        // Handled in verification
        StepLogger.verification('Export to Excel button should be appearing on the right top side of the page.');
        await RolesHelper.verifyExportToExcel();

        StepLogger.stepId(4);
        StepLogger.step('Click on the Export to Excel button');
        await RolesHelper.clickExportToExcel();
        StepLogger.verification('File should be downloaded with .xls extension.');
        await RolesHelper.verifyDownload(RolesConstants.elementNames.fileName);
        await RolesHelper.verifyDownload(RolesConstants.elementNames.excelFileExtension);
    });

    // Jira References - COTRAC-2268
    it('Verify user clicks on the Export to Word button - [22971606]', async () => {
        // Auto generated by aurea-automation - util on Fri, 12 Jul 2019 11:44:19 GMT

        StepLogger.caseId = 22971606;
        StepLogger.stepId(1);
        StepLogger.step('Verify user click on Role menu');
        await HomePageOneHelper.clickOnRolesUnderSecuritySubmenuUnderAdministrationMenu();
        StepLogger.verification('Manage Role page should open.');
        await RolesHelper.verifyRolesPageDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Verify columns appearing on the page.');
        // Handled in verification
        StepLogger.verification(`Following columns should be appearing on the page:
		Role
		Description
		Active
		Delete`);
        await RolesHelper.verifyColumnReporterPage();

        StepLogger.stepId(3);
        StepLogger.step('Verify Export to Word button is appearing on the right top side of the page.');
        // Handled in verification
        StepLogger.verification('Export to Word button should be appearing on the right top side of the page.');
        await RolesHelper.verifyExportToWord();

        StepLogger.stepId(4);
        StepLogger.step('Click on the Export to Word button');
        await RolesHelper.clickExportToWord();
        StepLogger.verification('File should be downloaded with .doc extension.');
        await RolesHelper.verifyDownload(RolesConstants.elementNames.fileName);
        await RolesHelper.verifyDownload(RolesConstants.elementNames.wordFileExtension);
    });

    // Jira References - COTRAC-2268
    it('Verify user clicks on any role, role detail page should open. - [22971608]', async () => {
        // Auto generated by aurea-automation - util on Fri, 12 Jul 2019 11:57:21 GMT

        StepLogger.caseId = 22971608;
        StepLogger.stepId(1);
        StepLogger.step('Verify user click on Role menu');
        await HomePageOneHelper.clickOnRolesUnderSecuritySubmenuUnderAdministrationMenu();
        StepLogger.verification('Manage Role page should open.');
        await RolesHelper.verifyRolesPageDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Verify Add Role button is appearing on the top left side of the page.');
        // Handled in verification
        StepLogger.verification('Add Role button should be appearing on the top left side of the page.');
        await RolesHelper.verifyAddRole();

        StepLogger.stepId(3);
        StepLogger.step('Click on the Add Role button');
        await RolesHelper.clickAddRole();
        StepLogger.verification('A new page should open with heading "New Role".');
        await RolesHelper.verifyAddRolesPageDisplayed();
    });
});
