import { StepLogger } from '../../../../../core/logger/step-logger';
import { PageHelper } from '../../../../components/html/page-helper';
import { CustomItemConstants } from '../../../../page-objects/pages/administration/configuration/custom-item/custom-item.constants';
import { CustomItemHelper } from '../../../../page-objects/pages/administration/configuration/custom-item/custom-item.helper';
import { CustomItemPage } from '../../../../page-objects/pages/administration/configuration/custom-item/custom-item.po';
import { CommonPageHelper } from '../../../../page-objects/pages/common/common-page.helper';
import { HomePage } from '../../../../page-objects/pages/home-page/home-page.po';
import { LoginPageHelper } from '../../../../page-objects/pages/login-page/login-page.helper';
import { SuiteNames } from '../../../helpers/suite-names';

describe(SuiteNames.regressionSuite, () => {
    const table = CustomItemConstants.table;
    const status = CustomItemConstants.elementNames;
    let loginPageHelper: LoginPageHelper;

    beforeAll(async () => {
        loginPageHelper = LoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
    });

    beforeEach(async () => {
        await loginPageHelper.goTo();
        await LoginPageHelper.loginAsAdmin();
    });

    // Jira References - COTRAC-162
    it('Verify user views options on Custom Items page. - [22934875]', async () => {
        // Auto generated by aurea-automation - util on Fri, 19 Apr 2019 14:06:06 GMT

        StepLogger.caseId = 22934875;
        StepLogger.stepId(1);
        StepLogger.step('Navigate to Administration --> Configuration --> Custom Item in the left side navigation pane');
        await CustomItemHelper.navigateToAdministrationConfiguration();
        StepLogger.verification('The is navigated to Custom Item option.');
        await HomePage.configurationUnderAdministration.customItem.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Click on Custom Items menu in left side Navigation Pane.');
        await CustomItemHelper.clickCustomItemAndSelectItem();
        StepLogger.verification('The Custom Items page is displayed in the right side pane.');
        await CustomItemHelper.verifyCustomItemPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Verify user views options on Custom Items page.');
        StepLogger.verification(`The user is able to view below options on Custom Items page:
            Sort
            Refresh
            Add Custom Item
            Export to Excel
            Export to Word`);
        await CustomItemHelper.verifyAllButtonDisplayed();

        StepLogger.stepId(4);
        StepLogger.step('Click on Sign off button at the bottom in the left side Navigation Pane.');
        await CommonPageHelper.signOffApp();
        StepLogger.verification('The Login screen is displayed again.');
        await LoginPageHelper.verifyLoginPage();
    });

    // Jira References - COTRAC-162
    it('Verify if user shall be able to see the header content properly - [22934874]', async () => {
        // Auto generated by aurea-automation - util on Fri, 19 Apr 2019 14:06:06 GMT

        StepLogger.caseId = 22934874;
        StepLogger.stepId(1);
        StepLogger.step('Navigate to Administration --> Configuration --> Custom Item in the left side navigation pane');
        await CustomItemHelper.navigateToAdministrationConfiguration();
        StepLogger.verification('The is navigated to Custom Item option.');
        await HomePage.configurationUnderAdministration.customItem.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Click on Custom Items menu in left side Navigation Pane.');
        await CustomItemHelper.clickCustomItemAndSelectItem();
        StepLogger.verification('The Custom Items page is displayed in the right side pane.');
        await CustomItemHelper.verifyCustomItemPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Verify the header content on Custom Items page.');
        StepLogger.verification('The Items are listed in Grid with Header "Manage Custom Items" ' +
            'and column headings [Item - Type - Active]');
        await CustomItemHelper.verifyPageTitleAndTableColumnsDisplayed();

        StepLogger.stepId(4);
        StepLogger.step('Click on Sign off button at the bottom in the left side Navigation Pane.');
        await CommonPageHelper.signOffApp();
        StepLogger.verification('The Login screen is displayed again.');
        await LoginPageHelper.verifyLoginPage();
    });

    // Jira References - COTRAC-162
    it('Verify if user shall be able to refresh the page clicking on Refresh button - [22934876]', async () => {
        // Auto generated by aurea-automation - util on Fri, 19 Apr 2019 14:06:06 GMT

        StepLogger.caseId = 22934876;
        StepLogger.stepId(1);
        StepLogger.step('Navigate to Administration --> Configuration --> Custom Item in the left side navigation pane');
        await CustomItemHelper.navigateToAdministrationConfiguration();
        StepLogger.verification('The is navigated to Custom Item option.');
        await HomePage.configurationUnderAdministration.customItem.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Click on Custom Items menu in left side Navigation Pane.');
        await CustomItemHelper.clickCustomItemAndSelectItem();
        StepLogger.verification('The Custom Items page is displayed in the right side pane.');
        await CustomItemHelper.verifyCustomItemPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on the refresh button on the top left side of the screen');
        await CustomItemHelper.clickRefresh();
        StepLogger.verification('The screen is refreshed and data is updated accordingly.');
        await CustomItemHelper.verifyCustomItemPageDisplayed();

        StepLogger.stepId(4);
        StepLogger.step('Click on Sign off button at the bottom in the left side Navigation Pane.');
        await CommonPageHelper.signOffApp();
        StepLogger.verification('The Login screen is displayed again.');
        await LoginPageHelper.verifyLoginPage();
    });

    // Jira References - COTRAC-162
    it('Verify if user is able to access the Custom Items page - [22934873]', async () => {
        // Auto generated by aurea-automation - util on Fri, 19 Apr 2019 14:06:06 GMT

        StepLogger.caseId = 22934873;
        StepLogger.stepId(1);
        StepLogger.step('Navigate to Administration --> Configuration --> Custom Item in the left side navigation pane');
        await CustomItemHelper.navigateToAdministrationConfiguration();
        StepLogger.verification('The is navigated to Custom Item option.');
        await HomePage.configurationUnderAdministration.customItem.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Click on Custom Items menu in left side Navigation Pane.');
        await CustomItemHelper.clickCustomItemAndSelectItem();
        StepLogger.verification('The Custom Items page is displayed in the right side pane.');
        await CustomItemHelper.verifyCustomItemPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on Sign off button at the bottom in the left side Navigation Pane.');
        await CommonPageHelper.signOffApp();
        StepLogger.verification('The Login screen is displayed again.');
        await LoginPageHelper.verifyLoginPage();
    });

    // Jira References - COTRAC-162
    it('Verify Save button functionality on Edit Custom Item page. - [22934879]', async () => {
        // Auto generated by aurea-automation - util on Fri, 19 Apr 2019 14:06:07 GMT
        const newItemName = PageHelper.getUniqueId();

        StepLogger.caseId = 22934879;
        StepLogger.stepId(1);
        StepLogger.step('Navigate to Administration --> Configuration --> Custom Item in the left side navigation pane');
        await CustomItemHelper.navigateToAdministrationConfiguration();
        StepLogger.verification('The is navigated to Custom Item option.');
        await HomePage.configurationUnderAdministration.customItem.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Click on Custom Items menu in left side Navigation Pane.');
        await CustomItemHelper.clickCustomItemAndSelectItem();
        StepLogger.verification('The Custom Items page is displayed in the right side pane.');
        await CustomItemHelper.verifyCustomItemPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on edit button next to Item column to view and edit the Custom Item');
        await CustomItemHelper.clickEditElement();
        StepLogger.verification(`The Edit item page is displayed with Save and Cancel buttons and following fields :
            DISPOSITION
            ITEM TYPE
            STATUS`);
        await CustomItemHelper.verifyEditItemElementsDisplayed();

        StepLogger.stepId(4);
        StepLogger.step('Make desired changes to the Custom Item.');
        await CustomItemHelper.changeDataElementsInEdit(newItemName);
        StepLogger.verification('The changes are displayed in the fields.');
        await CustomItemHelper.verifyChangesEnteredInEdit(newItemName);

        StepLogger.stepId(5);
        StepLogger.step('Click on Save button.');
        await CustomItemHelper.clickSave();
        StepLogger.verification('The record is saved and the Edit Item window is closed.');
        await CustomItemPage.editItem.editItemTitle.verifyHiddenStatus();

        StepLogger.stepId(6);
        StepLogger.step('Click on the refresh button on Manage Custom Item page.');
        await CustomItemHelper.clickRefresh();
        await CustomItemHelper.clickOnUnselectedTableItemName(newItemName);
        StepLogger.verification('The changes made to the record are reflected on the Manage Custom Item page.');
        await CustomItemHelper.verifyChangesDisplayedInTableItems(newItemName, status.open, true);

        StepLogger.stepId(7);
        // Applied in the postCondition
        StepLogger.step('Click on Sign off button at the bottom in the left side Navigation Pane.');
        StepLogger.verification('The Login screen is displayed again.');

        StepLogger.postCondition('Revert the changed data');
        await CustomItemHelper.revertDataElementsInEdit(table.itemName);
    });

    // Jira References - COTRAC-162
    it('Verify Cancel button functionality on Edit Custom Item page. - [22934880]', async () => {
        // Auto generated by aurea-automation - util on Fri, 19 Apr 2019 14:06:07 GMT
        const customItem = PageHelper.getUniqueId();

        StepLogger.caseId = 22934880;
        StepLogger.stepId(1);
        StepLogger.step('Navigate to Administration --> Configuration --> Custom Item in the left side navigation pane');
        await CustomItemHelper.navigateToAdministrationConfiguration();
        StepLogger.verification('The is navigated to Custom Item option.');
        await HomePage.configurationUnderAdministration.customItem.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Click on Custom Items menu in left side Navigation Pane.');
        await CustomItemHelper.clickCustomItemAndSelectItem();
        StepLogger.verification('The Custom Items page is displayed in the right side pane.');
        await CustomItemHelper.verifyCustomItemPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on edit button next to Item column to view and edit the Custom Item');
        await CustomItemHelper.clickEditElement();
        StepLogger.verification(`The Edit item page is displayed with Save and Cancel buttons and following fields :
            DISPOSITION
            ITEM TYPE
            STATUS`);
        await CustomItemHelper.verifyEditItemElementsDisplayed();

        StepLogger.stepId(4);
        StepLogger.step('Make desired changes to the Custom Item.');
        await CustomItemHelper.changeDataElementsInEdit(customItem);
        StepLogger.verification('The changes are displayed in the fields.');
        await CustomItemHelper.verifyChangesEnteredInEdit(customItem);

        StepLogger.stepId(5);
        StepLogger.step('Click on Cancel button on Edit window.');
        await CustomItemHelper.clickCancel();
        StepLogger.verification('The record is not updated and the Edit window is closed.');
        await CustomItemHelper.verifyChangesDisplayedInTableItems(table.itemName, status.disposition);

        StepLogger.stepId(6);
        StepLogger.step('Click on Sign off button at the bottom in the left side Navigation Pane.');
        await CommonPageHelper.signOffApp();
        StepLogger.verification('The Login screen is displayed again.');
        await LoginPageHelper.verifyLoginPage();
    });

    // Jira References - COTRAC-162
    it('Verify Add Custom Item button functionality on Custom Items page - [22934877]', async () => {
        // Auto generated by aurea-automation - util on Fri, 19 Apr 2019 14:06:07 GMT

        StepLogger.caseId = 22934877;
        StepLogger.stepId(1);
        StepLogger.step('Navigate to Administration --> Configuration --> Custom Item in the left side navigation pane');
        await CustomItemHelper.navigateToAdministrationConfiguration();
        StepLogger.verification('The is navigated to Custom Item option.');
        await HomePage.configurationUnderAdministration.customItem.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Click on Custom Items menu in left side Navigation Pane.');
        await CustomItemHelper.clickCustomItemAndSelectItem();
        StepLogger.verification('The Custom Items page is displayed in the right side pane.');
        await CustomItemHelper.verifyCustomItemPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on Add Custom Item button.');
        await CustomItemHelper.clickOnAddItem();
        StepLogger.verification(`The New Item window is displayed with Save and Cancel buttons and following fields:
            SORTABLE ITEM
            ITEM TYPE
            STATUS`);
        await CustomItemHelper.verifyEditItemElementsDisplayed();

        StepLogger.stepId(4);
        StepLogger.step('Click on Close button (cross sign) on New Item window.');
        await CustomItemHelper.clickClose();
        StepLogger.verification('The New Item window is closed and the main application is displayed again.');
        await CustomItemHelper.verifyPageTitleAndTableColumnsDisplayed();

        StepLogger.stepId(5);
        StepLogger.step('Click on Sign off button at the bottom in the left side Navigation Pane.');
        await CommonPageHelper.signOffApp();
        StepLogger.verification('The Login screen is displayed again.');
        await LoginPageHelper.verifyLoginPage();
    });

    // Jira References - COTRAC-162
    it('Verify if user is able to view the Custom Item - [22934878]', async () => {
        // Auto generated by aurea-automation - util on Fri, 19 Apr 2019 14:06:07 GMT

        StepLogger.caseId = 22934878;
        StepLogger.stepId(1);
        StepLogger.step('Navigate to Administration --> Configuration --> Custom Item in the left side navigation pane');
        await CustomItemHelper.navigateToAdministrationConfiguration();
        StepLogger.verification('The is navigated to Custom Item option.');
        await HomePage.configurationUnderAdministration.customItem.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Click on Custom Items menu in left side Navigation Pane.');
        await CustomItemHelper.clickCustomItemAndSelectItem();
        StepLogger.verification('The Custom Items page is displayed in the right side pane.');
        await CustomItemHelper.verifyCustomItemPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on edit button next to Item column to view and edit the Custom Item');
        await CustomItemHelper.clickEditElement();
        StepLogger.verification(`The Edit item page is displayed with Save and Cancel buttons and following fields :
            DISPOSITION
            ITEM TYPE
            STATUS`);
        await CustomItemHelper.verifyEditItemElementsDisplayed();
        await CustomItemHelper.clickCancel();

        StepLogger.stepId(4);
        StepLogger.step('Click on Sign off button at the bottom in the left side Navigation Pane.');
        await CommonPageHelper.signOffApp();
        StepLogger.verification('The Login screen is displayed again.');
        await LoginPageHelper.verifyLoginPage();
    });
});
