import { StepLogger } from '../../../../core/logger/step-logger';
import { PageHelper } from '../../../components/html/page-helper';
import { Constants } from '../../../components/misc-utils/constants';
import { HomePageConstant } from '../../../page-objects/pages/home-page/home-page.constants';
import { HomePage1Helper } from '../../../page-objects/pages/home-page/home-page1.helper';
import { LoginPageHelper } from '../../../page-objects/pages/login-page/login-page.helper';
import { ReportWriterReportsPageHelper } from '../../../page-objects/pages/report-writer-reports-page/report-writer-reports-page.helper';
import { YearQuartersPageConstants } from '../../../page-objects/pages/report-writer-reports-page/year-quarters-page/year-quarters-page.constants';
import { YearQuartersPageHelper } from '../../../page-objects/pages/report-writer-reports-page/year-quarters-page/year-quarters-page.helper';
import { SuiteNames } from '../../helpers/suite-names';

describe(SuiteNames.regressionSuite, () => {
    let loginPageHelper: LoginPageHelper;

    beforeAll(async () => {
        loginPageHelper = LoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
    });

    beforeAll(async () => {
        await loginPageHelper.goTo();
        await LoginPageHelper.loginAsAdmin();
    });

    // Jira References - COTRAC-2413
    it('To verify if user is able to navigate to "Resources -> Yearly Quarters" on "Report Writer Reports" page - [22997637]', async () => {
        // Auto generated by aurea-automation - util on Wed, 19 Jun 2019 10:43:34 GMT

        StepLogger.caseId = 22997637;
        StepLogger.stepId(1);
        StepLogger.step('Navigate to Reports -> Report Writer');
        await HomePage1Helper.navigateToReportWriterPage();
        StepLogger.verification('"Report Writer Reports" page is displayed in right pane');
        await ReportWriterReportsPageHelper.verifyReportWriterReportsPageIsDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Verify if "Yearly Quarters" is displayed under "Resources" in left pane');
        // Step Handled in verification
        StepLogger.verification('"Yearly Quarters" should be present');
        await ReportWriterReportsPageHelper.verifyLinkUnderResource();

        StepLogger.stepId(3);
        StepLogger.step('Click Yearly Quarters');
        await YearQuartersPageHelper.clickYearlyQuarter();
        StepLogger.verification('User is redirected to Resources -> Yearly Quarters in right pane');
        await YearQuartersPageHelper.verifyYearlyQuarterDisplaced();
    });

    // Jira References - COTRAC-2413
    it('To verify contents of "Resources -> Yearly Quarters" on "Report Writer Reports" page - [22997638]', async () => {
        // Auto generated by aurea-automation - util on Wed, 19 Jun 2019 10:54:32 GMT

        StepLogger.caseId = 22997638;
        StepLogger.stepId(1);
        StepLogger.step('Verify the headers of table displayed on page');
        // Step Handled in verification
        StepLogger.verification(`Below are the headers:
		Action
		Year
		Quarter
		Begin
		End`);
        await YearQuartersPageHelper.verifyYearColumnReporterPage();

        StepLogger.stepId(2);
        StepLogger.step('Verify the buttons displayed below the table');
        // Step Handled in verification
        StepLogger.verification('"New Quarter" and "Duplicate Year" are the buttons displayed');
        await YearQuartersPageHelper.verifyTableButtons();

        StepLogger.stepId(3);
        StepLogger.step('Verify if pagination and page size drop-down are present');
        await YearQuartersPageHelper.verifyPaginationDisplayed();
        StepLogger.verification('Pagination and page size drop-down should be present');
        await YearQuartersPageHelper.verifyPageSizeDisplayed();
    });

    // Jira References - COTRAC-2413
    it('To verify the functionality of pagination on "Resources -> Yearly Quarters" on "Report Writer Reports" page - [22997639]', async () => {
        // Auto generated by aurea-automation - util on Thu, 20 Jun 2019 15:14:10 GMT

        StepLogger.caseId = 22997639;
        StepLogger.stepId(1);
        StepLogger.step('Verify the navigation buttons present on pagination tab by hovering over each button');
        // Handled in verification
        StepLogger.verification(`Below navigation buttons should be present:
				First page
		Previous page
		Next Page
		Last Page`);
        await YearQuartersPageHelper.verifyPaginationButtons();

        StepLogger.stepId(2);
        StepLogger.step('Click on "Next Page" button');
        await YearQuartersPageHelper.clickNextPage();
        StepLogger.verification('List of Quarters on next page should be displayed');
        await YearQuartersPageHelper.verifyQuarterUpdated(YearQuartersPageConstants.yearTableHeader.Q1);

        StepLogger.stepId(3);
        StepLogger.step('Click on "Last Page" button');
        await YearQuartersPageHelper.clickLastPage();
        StepLogger.verification('List of Quarters on last page should be displayed');
        await YearQuartersPageHelper.verifyQuarterUpdated(YearQuartersPageConstants.yearTableHeader.Q2);

        StepLogger.stepId(4);
        StepLogger.step('Click on "Previous Page" button');
        await YearQuartersPageHelper.clickPreviousPage();
        StepLogger.verification('List of Quarters on previous page should be displayed');
        await YearQuartersPageHelper.verifyQuarterUpdated(YearQuartersPageConstants.yearTableHeader.Q3);

        StepLogger.stepId(5);
        StepLogger.step('Click on "First Page" button');
        await YearQuartersPageHelper.clickFirstPage();
        StepLogger.verification('List of Quarters on first page should be displayed');
        await YearQuartersPageHelper.verifyQuarterUpdated(YearQuartersPageConstants.yearTableHeader.Q4);

        StepLogger.stepId(6);
        StepLogger.step('Click on any of the page number button');
        await YearQuartersPageHelper.clickPageNumber(HomePageConstant.elementNames.two);
        StepLogger.verification('User should be redirected to that page');
        await YearQuartersPageHelper.verifySelectedPage(HomePageConstant.elementNames.two);
    });

    // Jira References - COTRAC-2413
    it('To verify the contents of "Quarter Editor" window displayed when clicked on "New Quarter" button - [22997640]', async () => {
        // Auto generated by aurea-automation - util on Thu, 20 Jun 2019 16:33:02 GMT

        StepLogger.caseId = 22997640;
        StepLogger.stepId(1);
        StepLogger.step('Click "New Quarter" button');
        await YearQuartersPageHelper.clickNewQuarter();
        StepLogger.verification('"Quarter Editor" window is displayed');
        await YearQuartersPageHelper.verifyEditFormisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Verify the fields in window');
        StepLogger.verification(`Below fields should be present:
				Year (text)
		Quarter ( drop-down)
		Begin (Calendar pop-up)
		End (Calendar pop-up)`);
        await YearQuartersPageHelper.verifyYearFieldDisplayed();
        await YearQuartersPageHelper.verifyStartDateDisplayed();
        await YearQuartersPageHelper.verifyQuarterDropDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Verify the values in Quarter drop-down');
        await YearQuartersPageHelper.selectValueFromQuarterDrop();
        StepLogger.verification('Q1,Q2,Q3 and Q4 are the values in drop-down');
        await YearQuartersPageHelper.verifyQuarterDropDisplayed();

        StepLogger.stepId(4);
        StepLogger.step('Verify the buttons');
        await YearQuartersPageHelper.verifyCancelButton();
        StepLogger.verification('OK and Cancel buttons are present');
        await YearQuartersPageHelper.verifyOkButton();
    });

    // Jira References - COTRAC-2413
    it('To verify if user is successfully able to select "Begin" and "End" date using Calendar pop-up on "Quarter Editor" window - [22997641]', async () => {
        // Auto generated by aurea-automation - util on Fri, 21 Jun 2019 06:20:49 GMT

        StepLogger.caseId = 22997641;
        StepLogger.stepId(1);
        StepLogger.step('Click "New Quarter" button');
        await YearQuartersPageHelper.clickCancelButton();
        await YearQuartersPageHelper.clickNewQuarter();
        StepLogger.verification('"Quarter Editor" window is displayed');
        await YearQuartersPageHelper.verifyEditFormisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Click Calendar icon against Begin field');
        await YearQuartersPageHelper.setBeginDate();
        StepLogger.verification('Calendar widget is displayed to select a date with default as current month and year');
        await YearQuartersPageHelper.verifyStartDateDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on the "Month Year" displayed on top of widget');
        await YearQuartersPageHelper.setYearField();
        StepLogger.verification('Additional widget to select a month and year is displayed');
        await YearQuartersPageHelper.verifyYearFieldDisplayed();

        StepLogger.stepId(4);
        StepLogger.step('Select a month and year from widget displayed in previous step and click OK');
        await YearQuartersPageHelper.setStartAndEndDate();
        StepLogger.verification('Monthly calendar of selected month is displayed in Calendar widget');
        await YearQuartersPageHelper.verifyStartDateDisplayed();

        StepLogger.stepId(5);
        StepLogger.step('Click on date from the selected month');
        await YearQuartersPageHelper.setBeginDate();
        StepLogger.verification('Selected date is displayed in Begin field');
        await YearQuartersPageHelper.verifyBeginDateSet();

        StepLogger.stepId(6);
        StepLogger.step('Similarly select a date from Calendar widget for End date field');
        await YearQuartersPageHelper.setEndDate();
        StepLogger.verification('User should be able to select End date');
        await YearQuartersPageHelper.verifyEndDateSet();
    });

    // Jira References - COTRAC-2413
    it('To verify the functionality of "Cancel" button on "Quarter Editor" window - [22997643]', async () => {
        // Auto generated by aurea-automation - util on Fri, 21 Jun 2019 06:40:20 GMT

        StepLogger.caseId = 22997643;
        StepLogger.stepId(1);
        StepLogger.step('Click "New Quarter" button');
        await YearQuartersPageHelper.clickCancelButton();
        await YearQuartersPageHelper.clickNewQuarter();
        StepLogger.verification('"Quarter Editor" window is displayed');
        await YearQuartersPageHelper.verifyEditFormisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Fill in the value for Year text field');
        await YearQuartersPageHelper.setYearField();
        StepLogger.verification('User should be able to select a value for Year');
        await YearQuartersPageHelper.verifyYearFieldDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Select Begin and End dates and Quarter from drop-down');
        await YearQuartersPageHelper.setStartAndEndDate();
        StepLogger.verification('User should be able to select the dates and quarter');
        await YearQuartersPageHelper.verifyStartDateDisplayed();

        StepLogger.stepId(4);
        StepLogger.step('Click Cancel button');
        await YearQuartersPageHelper.clickCancelButton();
        StepLogger.verification('"Quarter Editor" window is closed and quarter is not created');
        await YearQuartersPageHelper.verifyEditFormNotDisplayed();
    });

    // Jira References - COTRAC-2413
    it('To verify if user is able to successfully add "New Quarter" on Resources -> Yearly Quarters - [22997644]', async () => {
        // Auto generated by aurea-automation - util on Fri, 21 Jun 2019 06:48:58 GMT

        StepLogger.caseId = 22997644;
        StepLogger.stepId(1);
        StepLogger.step('Click "New Quarter" button');
        await YearQuartersPageHelper.clickNewQuarter();
        StepLogger.verification('"Quarter Editor" window is displayed');
        await YearQuartersPageHelper.verifyEditFormisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Fill in the value for Year text field');
        await YearQuartersPageHelper.setYearField();
        StepLogger.verification('User should be able to select a value for Year');
        await YearQuartersPageHelper.verifyYearFieldDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Select Begin and End dates and Quarter from drop-down');
        await YearQuartersPageHelper.setStartAndEndDate();
        StepLogger.verification('User should be able to select the dates and quarter');
        await YearQuartersPageHelper.verifyStartDateDisplayed();

        StepLogger.stepId(4);
        StepLogger.step('Click OK button');
        await YearQuartersPageHelper.clickOkButton();
        StepLogger.verification('"Quarter Editor" is closed successfully and quarter is added to the table');
        await YearQuartersPageHelper.verifyEditFormNotDisplayed();
        await YearQuartersPageHelper.verifyCountIsDeceased();
    });

    // Jira References - COTRAC-2413
    it('To verify the contents of "Year Duplicator" window displayed when clicked on "Duplicate Year" button - [22997645]', async () => {
        // Auto generated by aurea-automation - util on Fri, 21 Jun 2019 07:00:05 GMT

        StepLogger.caseId = 22997645;
        StepLogger.stepId(1);
        StepLogger.step('Click "Duplicate Year" button');
        await YearQuartersPageHelper.clickDuplicateButton();
        StepLogger.verification('"Year Duplicator" window is displayed');
        await YearQuartersPageHelper.verifyEditFormisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Verity the fields on window');
        // Handled in Verification Step
        StepLogger.verification('"Year to Duplicate" and "New Year" fields should be present');
        await YearQuartersPageHelper.verifyYearDuplicateDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Verify the buttons');
        await YearQuartersPageHelper.verifyDuplicateCancelButton();
        StepLogger.verification('OK and Cancel buttons are present');
        await YearQuartersPageHelper.verifyDuplicateOkButton();
    });

    // Jira References - COTRAC-2413
    it('To verify the functionality of "Cancel" button on "Year Duplicator" window - [22997646]', async () => {
        // Auto generated by aurea-automation - util on Fri, 21 Jun 2019 07:32:08 GMT

        StepLogger.caseId = 22997646;
        StepLogger.stepId(1);
        StepLogger.step('Click "Duplicate Year" button');
        // Opened from previous Case
        StepLogger.verification('"Year Duplicator" window is displayed');
        await YearQuartersPageHelper.verifyEditFormisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Select a value from drop-down for "Year to Duplicate"');
        await YearQuartersPageHelper.clickYearDuplicate();
        StepLogger.verification('User should be able to select value for "Year to Duplicate" field');
        await YearQuartersPageHelper.setYearToDuplicate(YearQuartersPageConstants.yearTableHeader.yearQuarter);

        StepLogger.stepId(3);
        StepLogger.step('Fill in value for "New Year" field which needs to be created');
        const today = new Date();
        await YearQuartersPageHelper.fillNewYearValue(`${today.getFullYear() + Constants.number.two}`);
        StepLogger.verification('User should be able to enter new year');
        await YearQuartersPageHelper.verifyYearDuplicateDisplayed();

        StepLogger.stepId(4);
        StepLogger.step('Click Cancel button');
        await YearQuartersPageHelper.clickDuplicateCancelButton();
        StepLogger.verification('"Year Duplicator" window is closed and no new quarters for year entered in "New Year" field are added');
        await YearQuartersPageHelper.verifyEditFormNotDisplayed();
    });

    // Jira References - COTRAC-2413
    it('To verify if user is successfully able to duplicate the quarters of a selected year - [22997647]', async () => {
        // Auto generated by aurea-automation - util on Fri, 21 Jun 2019 09:17:21 GMT

        StepLogger.caseId = 22997647;
        StepLogger.stepId(1);
        StepLogger.step('Click "Duplicate Year" button');
        // Opened from previous Case
        StepLogger.verification('"Year Duplicator" window is displayed');
        await YearQuartersPageHelper.verifyEditFormisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Select a value from drop-down for "Year to Duplicate"');
        await YearQuartersPageHelper.clickYearDuplicate();
        StepLogger.verification('User should be able to select value for "Year to Duplicate" field');
        await YearQuartersPageHelper.setYearToDuplicate(YearQuartersPageConstants.yearTableHeader.yearQuarter);

        StepLogger.stepId(3);
        StepLogger.step('Fill in value for "New Year" field which needs to be created');
        const today = new Date();
        await YearQuartersPageHelper.fillNewYearValue(`${today.getFullYear() + Constants.number.two}`);
        StepLogger.verification('User should be able to enter new year');
        await YearQuartersPageHelper.verifyYearDuplicateDisplayed();

        StepLogger.stepId(4);
        StepLogger.step('Click OK button');
        await YearQuartersPageHelper.clickDuplicateOkButton();
        StepLogger.verification(`Year Duplicator window is closed and Duplicate quarters as that of
         the one selected in drop-down are added for the desired year`);
        await YearQuartersPageHelper.verifyCountIsDeceased();
    });
});
