export class NewProspectPageConstant {

    static get elementNames() {
        return {
            newProspectDefault: 'New Prospect: ',
            newProspectCommercial: 'New Prospect: Commercial',
            prospect: 'Prospect:',
            admin: 'Admin',
            firstName: 'First Name',
            lastName: 'Last Name',
            middle: 'Middle',
            relationShip: 'Relationship',
            doNotContactInCampaigns: 'Do not contact in marketing campaigns.',
            syncToOutLook: 'Sync To Outlook',
            events: 'Events',
            cases: 'Cases',
            companyName: 'Company Name',
            companyNameValidator: 'COMPANY is required.',
            title: 'Title',
            lastNameRequired: 'Last Name is required',
            firstNameRequired: 'First Name is required',
            dateOfBirth: 'Date of Birth',
            driversLicenceNumber: 'Drivers Licence Number',
            driversLicenceState: 'Drivers Licence State',
            driversLicenceExpiration: 'Drivers Licence Expiration',
            socialSecurityNumber: 'Social Security Number',
            address: 'Address',
            addressCont: 'Address Cont.',
            city: 'City',
            state: 'State',
            regO: 'REG O',
            country: 'Country',
            zip: 'Zip',
            homePhone: 'Home Phone',
            emailOne: 'Email1',
            workPhone: 'Work Phone',
            workPhoneValidator: 'WORK PHONE is required.',
            emailTwo: 'Email2',
            mobile: 'Mobile',
            pager: 'Pager',
            fax: 'Fax',
            communicationPref: 'Communication Preference',
            relatedContacts: 'Related Contacts',
            pipeline: 'Pipeline',
            services: 'Services',
            print: 'Print',
            recommendation: 'Recommendation',
            threeDots: 'threeDots',
            lostAccounts: 'Lost Accounts',
            lostPipeline: 'Lost Pipeline',
            summary: 'Summary',
            accounts: 'Accounts',
            attachments: 'Attachments',
            notes: 'Notes',
            portfolio: 'Portfolio',
            households: 'Households',
            tasks: 'Tasks',
            syncToOutLookOff: 'Sync To Outlook Off',
            syncToOutLookOn: 'Sync To Outlook On',
        };
    }

    static get attributes() {
        return {
            id: {
                mainMenuM1: 'mainMenu_m1',
                firstNameControl: 'first_name_control',
                lastNameControl: 'last_name_control',
                middleNameControl: 'middle_name_control',
                relationShipPage: 'pageRelationship',
                syncToOutLook: 'contactInfo_synctoext',
                doNotContactInCampaigns: 'contactInfo_campaign_opt_out',
                eventPage: 'pageEvents',
                casesPage: 'pageCases',
                companyNameControl: 'company_name_control',
                titleControl: 'title_control',
                firstNameRequired: 'first_name_RequiredFieldValidator',
                lastNameRequired: 'last_name_RequiredFieldValidator',
                dateOfBirth: 'date_of_birth_control',
                socialSecurityNumber: 'social_security_number_control',
                driversLicenceNumber: 'drivers_license_number_control',
                driverLicenceState: 'drivers_license_state_control',
                driversLicenseExpiration: 'drivers_license_expiration_control_dateInput',
                address: 'address1_control',
                addressCont: 'address2_control',
                city: 'city_control',
                rego: 'rego_control',
                state: 'state_control',
                country: 'country_control',
                zip: 'zip_control',
                homePhone: 'home_phone_control',
                emailOne: 'email_1_control',
                workPhone: 'work_phone_control',
                emailTwo: 'email_2_control',
                mobile: 'mobile_control',
                pager: 'pager_control',
                fax: 'fax_control',
                communicationPref: 'list_type_control',
                pipeline: '_tabPipelines_',
                relatedContacts: '_pagePortfolio_',
                services: '_tabServices_',
                threeDots: 'mainMenu_m0',
                recommendation: 'btnOpenRecs',
                print: 'btnPrintPage',
                header: 'myHeader_headingUpdatePanel',
                lostAccounts: '_tabLost_',
                summary: '_tabSummary_',
                accounts: '_tabProducts_',
                lostPipeline: '_tabLostOpps_',
                attachments: '_pageAttachments_',
                notes: '_pageNotes_',
                portfolio: '_tabport_',
                households: '_pageHouseholds_',
                tasks: '_pageTasks_',
                workPhoneValidator: 'work_phone_RequiredFieldValidator',
                companyValidator: 'company_name_RequiredFieldValidator',
            },
            classes: {
                cellNavigation: 'cell-navigation',
                cellContents: 'cell-contents',
                innerWrap: 'innerWrap',
                phone: 'phone',
                checkOff: 'checkbox-off',
                checkOn: 'checkbox-on',
            },
        };
    }

    static get testData() {
        return {
            workPhone: '123456789',
            newWorkPhone: '987654321',
        };
    }
}
