export class YearQuartersPageConstants {
    static readonly yearTableHeader = Object.freeze({
        year: 'Year',
        quarter: 'Quarter',
        begin: 'Begin',
        end: 'End',
        yearlyQuarters: 'Yearly Quarters',
        action: 'Action',
        duplicateYear: 'Duplicate Year',
        pagination: 'pagination',
        pageSize: 'Page Size',
        edit: 'Edit',
        Q2: 'Q2',
        startDate: 'startDate',
        endDate: 'endDate',
        cancel: 'Cancel',
        ok: 'OK',
        lastPage: 'Last Page',
        delete: 'delete',
        item: 'item',
        Q1: 'Q1',
        Q3: 'Q3',
        Q4: 'Q4',
        firstPage: 'First Page',
        nextPage: 'Next Page',
        previousPage: 'Previous Page',
        yearQuarter: '2017',
    });
}
