import { StepLogger } from '../../../../../core/logger/step-logger';
import { PageHelper } from '../../../../components/html/page-helper';
import { DistrictsHelper } from '../../../../page-objects/pages/administration/organization/districts/districts.helper';
import { HomePageHelper } from '../../../../page-objects/pages/home-page/home-page.helper';
import { HomePage1Helper } from '../../../../page-objects/pages/home-page/home-page1.helper';
import { LoginPageHelper } from '../../../../page-objects/pages/login-page/login-page.helper';
import { SuiteNames } from '../../../helpers/suite-names';

describe(SuiteNames.regressionSuite, () => {
    let loginPageHelper: LoginPageHelper;

    beforeAll(async () => {
        loginPageHelper = LoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
    });

    beforeEach(async () => {
        await loginPageHelper.goTo();
        await LoginPageHelper.loginAsAdmin();
    });

    it('To verify that the user is able to navigate to Manage Districts page - [22460538]', async () => {
        // Auto generated by aurea-automation - util on Mon, 01 Apr 2019 12:16:20 GMT

        StepLogger.caseId = 22460538;

        StepLogger.stepId(1);
        StepLogger.step('Click "Administration" link displayed in the left panel.');
        await HomePageHelper.clickAdministrationLink();
        StepLogger.verification('Option available under administration section should be displayed.');
        await HomePageHelper.verifyOptionsUnderAdministration();

        StepLogger.stepId(2);
        StepLogger.step('Click "Organization" displayed under administration.');
        await HomePageHelper.clickOrganizationUnderAdministration();
        StepLogger.verification('Item available under Organization should be displayed.');
        await HomePageHelper.optionsUnderOrganization();

        StepLogger.stepId(3);
        StepLogger.step('Click "Districts"');
        await HomePage1Helper.clickDistrictsUnderOrganization();
        StepLogger.verification('"Manage Districts" should be displayed.');
        await DistrictsHelper.verifyManageDistrictsPageDisplayed();
    });

    it('To verify Manage Districts page - [22460539]', async () => {
        // Auto generated by aurea-automation - util on Mon, 01 Apr 2019 12:34:24 GMT

        StepLogger.caseId = 22460539;

        StepLogger.preCondition('Navigate To Districts Page');
        await HomePage1Helper.navigateToDistrictsPage();

        StepLogger.stepId(1);
        StepLogger.step('Verify the buttons displayed on Manage Districts page');
        StepLogger.verification(`Below buttons are displayed
        Add Markets
        Refresh
        Export to Excel
        Export to Word`);
        await DistrictsHelper.verifyButtons();

        StepLogger.stepId(2);
        StepLogger.step('Click in Search icon at top of page');
        await DistrictsHelper.clickOnSearchButton();
        StepLogger.verification('Search box is displayed');
        await DistrictsHelper.verifySearchBox();

        StepLogger.stepId(3);
        StepLogger.step('Verify the columns displayed');
        StepLogger.verification(`Below columns are displayed
        - District
        - District Code
        - Active`);
        await DistrictsHelper.verifyDistrictsPageItemsGrid();
    });

    it('To verify Edit District window is displayed when clicked on district icon next to a district entry - [22460551]', async () => {
        // Auto generated by aurea-automation - util on Tue, 02 Apr 2019 02:23:47 GMT

        StepLogger.caseId = 22460551;
        StepLogger.stepId(1);
        StepLogger.step('Click "Administration" link displayed in the left panel.');
        await HomePageHelper.clickAdministrationLink();
        StepLogger.verification('Option available under administration section should be displayed.');
        await HomePageHelper.verifyOptionsUnderAdministration();

        StepLogger.stepId(2);
        StepLogger.step('Click "Organization" displayed under administration.');
        await HomePageHelper.clickOrganizationUnderAdministration();
        StepLogger.verification('Item available under Organization should be displayed.');
        await HomePageHelper.optionsUnderOrganization();

        StepLogger.stepId(3);
        StepLogger.step('Click "Districts"');
        await HomePage1Helper.clickDistrictsUnderOrganization();
        StepLogger.verification('"Manage Districts" should be displayed.');
        await DistrictsHelper.verifyManageDistrictsPageDisplayed();

        StepLogger.stepId(4);
        StepLogger.step('Click on Market icon next to District entry');
        await DistrictsHelper.clickOnEditDistrict();
        StepLogger.verification('Edit window is displayed for the district');
        await DistrictsHelper.verifyEditDistrictScreen();
    });

    it('To verify Edit District window is displayed when double clicked on a district entry - [22460555]', async () => {
        // Auto generated by aurea-automation - util on Tue, 02 Apr 2019 05:01:53 GMT

        StepLogger.caseId = 22460555;
        StepLogger.stepId(1);
        StepLogger.step('Click "Administration" link displayed in the left panel.');
        await HomePageHelper.clickAdministrationLink();
        StepLogger.verification('Option available under administration section should be displayed.');
        await HomePageHelper.verifyOptionsUnderAdministration();

        StepLogger.stepId(2);
        StepLogger.step('Click "Organization" displayed under administration.');
        await HomePageHelper.clickOrganizationUnderAdministration();
        StepLogger.verification('Item available under Organization should be displayed.');
        await HomePageHelper.optionsUnderOrganization();

        StepLogger.stepId(3);
        StepLogger.step('Click "Districts"');
        await HomePage1Helper.clickDistrictsUnderOrganization();
        StepLogger.verification('"Manage Districts" should be displayed.');
        await DistrictsHelper.verifyManageDistrictsPageDisplayed();

        StepLogger.stepId(4);
        StepLogger.step('Double Click on  District entry');
        await DistrictsHelper.doubleClickOnDistrictEntry();
        StepLogger.verification('Edit window is displayed for the district');
        await DistrictsHelper.verifyEditDistrictScreen();
    });

    it('To verify user able to close edit district window by clicking on close icon on top right corner of window - [22460557]', async () => {
        // Auto generated by aurea-automation - util on Tue, 02 Apr 2019 05:35:08 GMT

        StepLogger.caseId = 22460557;
        StepLogger.stepId(1);
        StepLogger.step('Click "Administration" link displayed in the left panel.');
        await HomePageHelper.clickAdministrationLink();
        StepLogger.verification('Option available under administration section should be displayed.');
        await HomePageHelper.verifyOptionsUnderAdministration();

        StepLogger.stepId(2);
        StepLogger.step('Click "Organization" displayed under administration.');
        await HomePageHelper.clickOrganizationUnderAdministration();
        StepLogger.verification('Item available under Organization should be displayed.');
        await HomePageHelper.optionsUnderOrganization();

        StepLogger.stepId(3);
        StepLogger.step('Click "Districts"');
        await HomePage1Helper.clickDistrictsUnderOrganization();
        StepLogger.verification('"Manage Districts" should be displayed.');
        await DistrictsHelper.verifyManageDistrictsPageDisplayed();

        StepLogger.stepId(4);
        StepLogger.step('Click on Market icon next to District entry');
        await DistrictsHelper.clickOnEditDistrict();
        StepLogger.verification('Edit window is displayed for the district');
        await DistrictsHelper.verifyEditDistrictScreen();

        StepLogger.stepId(5);
        StepLogger.step('Click Close icon at top right corner');
        await DistrictsHelper.clickOnCloseButton();
        StepLogger.verification('Edit window is closed');
        await DistrictsHelper.verifyNewDistrictsScreenClosed();
    });
});
