export class ContactPageConstant {

    static get elementNames() {
        return {
            overview: 'Overview',
            profile: 'Profile',
            close: 'Close',
            outsideAccounts: 'Outside Accounts',
            addAccount: 'Add Account',
            contact: 'Contact:',
            snapshot: 'Snapshot',
            print: 'Print',
            relationship: 'Relationship',
            newOutsideAccount: 'New Outside Account',
            summary: 'Summary',
            pipelines: 'Pipelines',
            products: 'Products',
            services: 'Services',
            lostPipelines: 'Lost Pipelines',
            lostAccounts: 'Lost Accounts',
            tools: 'Tools',
            productType: 'Product Type',
            product: 'Product',
            amount: 'Amount',
            status: 'Status',
            owner: 'Owner',
            referrer: 'Referrer',
            forecast: 'Forecast',
            outside: 'Outside',
            modified: 'Modified',
            opportunities: 'Opportunities',
            accounts: 'Accounts',
            lostOpportunities: 'Lost Opportunities',
            closedAccounts: 'Closed Accounts',
            overviewOptions: 'Overview Options',
            relatedContacts: 'Related Contacts',
            portfolio: 'Portfolio',
            notes: 'Notes',
            addNote: 'Add Note',
            newNote: 'New Note',
            events: 'Events',
            addEvent: 'Add Event',
            newEvent: 'New Event',
            tasks: 'Tasks',
            addTask: 'Add Task',
            newTask: 'New Task',
            attachments: 'Attachments',
            addAttachments: 'Add Attachments',
            addNoteButtons: 'Add Note',
            subject: 'Subject',
            save: 'Save',
            saveAndClose: 'Save And Close',
            text: 'Text',
            addAttendee: 'Add Attendee',
            firstName: 'First Name',
            lastName: 'Last Name',
            search: 'Search',
            availableAttendees: 'Available Attendees',
            moveRight: 'Move Right',
            collapse: 'Collapse',
            expand: 'Expand',
            addOpportunity: 'Add Opportunity',
            accountType: 'Account Type',
            institution: 'Institution',
            cancel: 'Cancel',
            accoutTypeAndInstitutionRequired: 'Please review the following errors:\nAccount type is required.\nInstitution is required.',
            openAccount: 'openAcct',
            accountTypeOptions: 'Account Type Options',
            institutionOptions: 'Institution Options',
            admin: 'Admin',
            correctionsUtility: 'Corrections Utility',
            grouping: 'Grouping',
            date: 'Date',
            groupingIcon: 'Grouping icon',
            expandGroup: 'Expand group',
            collapseGroup: 'Collapse group',
            newAttachment: 'New Attachment',
            name: 'Name',
            attachmentsColumns: {
                name: 'Name',
                date: 'Date',
                addedBy: 'Added By',
                details: 'Details',
            },
            sortedAsc: 'Sorted asc',
            sortedDesc: 'Sorted desc',
            sortIcon: 'Sort icon',
            refresh: 'Refresh',
            description: 'Description',
            chooseFile: 'Choose file',
            file: 'file',
        };
    }

    static get attributes() {
        return {
            classes: {
                iconOverview: 'icon-overview',
                subSection: 'sub-section',
                uiDialogTitle: 'ui-dialog-title',
                iconRelatedEntities: 'icon-related-entities',
                uiIconCloseThick: 'ui-icon-closethick',
                simpleGridHeader: 'simpleGridHeader',
                overviewSectionHeadingTable: 'overviewSectionHeadingTable',
                gridRowAptean: 'GridRow_Aptean',
                gridAltRowAptean: 'GridAltRow_Aptean',
                sectionPanel: 'sectionPanel',
                collapse: 'icon-collapse-section',
                expand: 'icon-expand-section',
                gridHeaderAptean: 'GridHeader_Aptean',
                iconRefresh: 'icon-refresh',
                iconAttachment: 'icon-attachment',
            },
            id: {
                profileTab: 'Profile_tab',
                summaryTab: 'Summary_tab',
                pipelinesTab: 'Pipelines_tab',
                productsTab: 'Products_tab',
                servicesTab: 'Services_tab',
                lostOppsTab: 'LostOpps_tab',
                lostTab: 'Lost_tab',
                outsideAccount: 'outsideaccount',
                relovGridHolder0: 'relov_gridholder0',
                relovGridHolder: 'relov_gridholder',
                relovGrid0: 'relov_grid0',
                btnAddOutsideAccount: 'btnAddOutsideAccount',
                pagePortfolioTab: 'pagePortfolio_tab',
                tabRelatedTab: 'tabrelated_tab',
                tabPortTab: 'tabport_tab',
                pageNotesTab: 'pageNotes_tab',
                pageTasksTab: 'pageTasks_tab',
                pageAttachmentsTab: 'pageAttachments_tab',
                pageEventsTab: 'pageEvents_tab',
                addNoteButton: 'addNoteButton',
                addEventButton: 'addEventButton',
                addTaskButton: 'addTaskButton',
                addAttendeeButton: 'addAttendeeButton',
                addAttachmentButton: 'addAttachmentButton',
                saveBtn: 'saveBtn',
                saveButton: 'savebutton',
                saveAndCloseButton: 'saveandclosebutton',
                entityDialog: 'entityDialog',
                accountType: '_ddlType',
                institution: '_ddlInstitution',
                grouping: 'ctl00_MenuHolder_ctl00___Page_groupingSelector',
                radEditorStylesheetZero: 'RADEDITORSTYLESHEET0',
            },
            name: {
                firstNameTxt: 'firstNameTxt',
                lastNameTxt: 'lastNameTxt',
                searchBtn: 'searchBtn',
                moveRight: 'moveRight',
                subjectControl: 'subject_control',
            },
        };
    }

    static get messages() {
        return {
            nameRequired: 'Attachment Name is required.',
        };
    }
}
