import { StepLogger } from '../../../../../core/logger/step-logger';
import { PageHelper } from '../../../../components/html/page-helper';
import { BranchesConstants } from '../../../../page-objects/pages/administration/organization/branches/branches.constants';
import { BranchesHelper } from '../../../../page-objects/pages/administration/organization/branches/branches.helper';
import { HomePageHelper } from '../../../../page-objects/pages/home-page/home-page.helper';
import { HomePage1Helper } from '../../../../page-objects/pages/home-page/home-page1.helper';
import { LoginPageHelper } from '../../../../page-objects/pages/login-page/login-page.helper';
import { SuiteNames } from '../../../helpers/suite-names';

describe(SuiteNames.regressionSuite, () => {
    let loginPageHelper: LoginPageHelper;

    beforeAll(async () => {
        loginPageHelper = LoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
    });

    beforeEach(async () => {
        await loginPageHelper.goTo();
        await LoginPageHelper.loginAsAdmin();
    });

    it('To verify that the user is able to navigate to Manage Branches page - [22431109]', async () => {
        // Auto generated by aurea-automation - util on Wed, 27 Mar 2019 05:30:06 GMT

        StepLogger.caseId = 22431109;

        StepLogger.stepId(1);
        StepLogger.step('Click "Administration" link displayed in the left panel.');
        await HomePageHelper.clickAdministrationLink();
        StepLogger.verification('Option available under administration section should be displayed.');
        await HomePageHelper.verifyOptionsUnderAdministration();

        StepLogger.stepId(2);
        StepLogger.step('Click "Organization" displayed under administration.');
        await HomePageHelper.clickOrganizationUnderAdministration();
        StepLogger.verification('Item available under Organization should be displayed.');
        await HomePageHelper.optionsUnderOrganization();

        StepLogger.stepId(3);
        StepLogger.step('Click "Branches"');
        await HomePage1Helper.clickBranchesUnderOrganization();
        StepLogger.verification('"Manage Branches" page should be displayed.');
        await BranchesHelper.verifyManageBranchesPageDisplayed();
    });

    it('To verify the list of Items in Grid on Manage Branches Page - [22431111]', async () => {
        // Auto generated by aurea-automation - util on Wed, 27 Mar 2019 06:28:01 GMT

        StepLogger.caseId = 22431111;

        StepLogger.stepId(1);
        StepLogger.step('Click "Administration->Organization" displayed under administration.');
        await HomePageHelper.clickAdministrationLink();
        await HomePageHelper.clickOrganizationUnderAdministration();
        StepLogger.verification('Item available under Organization should be displayed.');
        await HomePageHelper.optionsUnderOrganization();

        StepLogger.stepId(2);
        StepLogger.step('Click "Branches"');
        await HomePage1Helper.clickBranchesUnderOrganization();
        StepLogger.verification('"Manage Branches" page should be displayed.');
        await BranchesHelper.verifyManageBranchesPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Verify the Items displayed in the grid.');
        StepLogger.verification(`Following items should be displayed in the grid:
        1. Branch
        2.  Branch Code
        3.  Region
        4.  City
        5.  State
        6. Phone
        7.  Active`);
        await BranchesHelper.verifyBranchesPageItemsGrid();
    });

    it('To verify the button available on "Manage Branches page". - [22431114]', async () => {
        // Auto generated by aurea-automation - util on Wed, 27 Mar 2019 07:17:17 GMT

        StepLogger.caseId = 22431114;

        StepLogger.stepId(1);
        StepLogger.step('Click "Administration->Organization" displayed under administration.');
        await HomePageHelper.clickAdministrationLink();
        await HomePageHelper.clickOrganizationUnderAdministration();
        StepLogger.verification('Item available under Organization should be displayed.');
        await HomePageHelper.optionsUnderOrganization();

        StepLogger.stepId(2);
        StepLogger.step('Click "Branches"');
        await HomePage1Helper.clickBranchesUnderOrganization();
        StepLogger.verification('"Manage Branches" page should be displayed.');
        await BranchesHelper.verifyManageBranchesPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('To verify the button available on "Manage Branches page".');
        StepLogger.verification(`Following options should be displayed.
        1. Add
        2.  Refresh
        3.  Grouping Drop down list
        4.  Export to Excel
        5.  Export to Word`);
        await BranchesHelper.verifyButtons();
    });

    it('To verify that user is able to navigate to "New Branch" page. - [22431158]', async () => {
        // Auto generated by aurea-automation - util on Wed, 27 Mar 2019 07:36:21 GMT

        StepLogger.caseId = 22431158;

        StepLogger.stepId(1);
        StepLogger.step('Click "Administration->Organization" displayed under administration.');
        await HomePageHelper.clickAdministrationLink();
        await HomePageHelper.clickOrganizationUnderAdministration();
        StepLogger.verification('Item available under Organization should be displayed.');
        await HomePageHelper.optionsUnderOrganization();

        StepLogger.stepId(2);
        StepLogger.step('Click "Branches"');
        await HomePage1Helper.clickBranchesUnderOrganization();
        StepLogger.verification('"Manage Branches" page should be displayed.');
        await BranchesHelper.verifyManageBranchesPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click "Add Branch"');
        await BranchesHelper.clickOnAddBranch();
        StepLogger.verification('"New Branch" page should be displayed.');
        await BranchesHelper.verifyNewBranchScreenDisplayed();
    });

    it('To verify the status drop down - [22431161]', async () => {
        // Auto generated by aurea-automation - util on Wed, 27 Mar 2019 07:48:15 GMT

        StepLogger.caseId = 22431161;
        const activeStatus = BranchesConstants.activeStatus;
        const inactiveStatus = BranchesConstants.inactiveStatus;

        StepLogger.stepId(1);
        StepLogger.step('Click "Administration->Organization" displayed under administration.');
        await HomePageHelper.clickAdministrationLink();
        await HomePageHelper.clickOrganizationUnderAdministration();
        StepLogger.verification('Item available under Organization should be displayed.');
        await HomePageHelper.optionsUnderOrganization();

        StepLogger.stepId(2);
        StepLogger.step('Click "Branches"');
        await HomePage1Helper.clickBranchesUnderOrganization();
        StepLogger.verification('"Manage Branches" page should be displayed.');
        await BranchesHelper.verifyManageBranchesPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click "Add Branch"');
        await BranchesHelper.clickOnAddBranch();
        StepLogger.verification('"New Branch" page should be displayed.');
        await BranchesHelper.verifyNewBranchScreenDisplayed();

        StepLogger.stepId(4);
        StepLogger.step('Verify the status field.');
        StepLogger.verification(`There should be 2 options available:
        1. Inactive
        2. Active`);
        await BranchesHelper.verifyValuesInStatusDropDown(activeStatus);
        await BranchesHelper.verifyValuesInStatusDropDown(inactiveStatus);
    });
});
