import { StepLogger } from '../../../../../core/logger/step-logger';
import { PageHelper } from '../../../../components/html/page-helper';
import { HomePageHelper } from '../../../../page-objects/pages/home-page/home-page.helper';
import { HomePage } from '../../../../page-objects/pages/home-page/home-page.po';
import { LoginPageHelper } from '../../../../page-objects/pages/login-page/login-page.helper';
import { NewCasePageHelper } from '../../../../page-objects/pages/new-case-page/new-case-page.helper';
import { NewOpportunityPageHelper } from '../../../../page-objects/pages/new-opportunity-page/new-opportunity-page.helper';
import { QueuedOpportunitiesPageConstant } from '../../../../page-objects/pages/queued-opportunities-page/queued-opportunities-page.constants';
import { QueuedOpportunitiesPageHelper } from '../../../../page-objects/pages/queued-opportunities-page/queued-opportunities-page.helper';
import { TasksQueuePageHelper } from '../../../../page-objects/pages/tasks-queue-page/tasks-queue-page.helper';
import { SuiteNames } from '../../../helpers/suite-names';

describe(SuiteNames.regressionSuite, () => {
    let loginPageHelper: LoginPageHelper;

    beforeAll(async () => {
        loginPageHelper = LoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
    });

    beforeEach(async () => {
        await PageHelper.restartBrowser();
        await loginPageHelper.goTo();
    });

    // Jira References - COTRAC-135
    it('Verify if user shall be able to access the Queued Opportunities page - [22425414]', async () => {
        // Auto generated by aurea-automation - util on Mon, 01 Apr 2019 13:09:51 GMT

        StepLogger.caseId = 22425414;
        StepLogger.preCondition('Execute C22395398 to login as an administrator');
        await LoginPageHelper.loginAsAdmin();
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        StepLogger.stepId(1);
        StepLogger.step('Click on Queues menu in left side Navigation Pane.');
        await HomePageHelper.clickQueuesLink();
        StepLogger.verification('The Queues menu should be expanded.');
        await HomePageHelper.verifyQueuesMenuIsExpanded();

        StepLogger.stepId(2);
        StepLogger.step('Check the Queues menu option list.');
        StepLogger.verification(`The Queues menu has the following options:
            Opportunities
            Cases
            Tasks
            Events
            Tickets`);
        await HomePageHelper.verifyOptionsDisplayedUnderQueues();

        StepLogger.stepId(3);
        StepLogger.step('Click on the Opportunities option menu.');
        await HomePageHelper.clickOpportunitiesUnderQueues();
        StepLogger.verification('The Queued Opportunities page is displayed in the right side pane.');
        await QueuedOpportunitiesPageHelper.verifyQueuedOpportunitiesPageDisplayed();
    });

    // Jira References - COTRAC-135
    it('Verify if user shall be able to refresh the data on screen clicking on Refresh button - [22425417]', async () => {
        // Auto generated by aurea-automation - util on Mon, 01 Apr 2019 13:09:51 GMT

        StepLogger.caseId = 22425417;
        StepLogger.preCondition('Execute C22395398 to login as an administrator');
        await LoginPageHelper.loginAsAdmin();
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        StepLogger.stepId(1);
        StepLogger.step('Click on Queues menu in left side Navigation Pane.');
        await HomePageHelper.clickQueuesLink();
        StepLogger.verification('The Queues menu should be expanded.');
        await HomePageHelper.verifyQueuesMenuIsExpanded();

        StepLogger.stepId(2);
        StepLogger.step('Check the Queues menu option list.');
        StepLogger.verification(`The Queues menu has the following options:
            Opportunities
            Cases
            Tasks
            Events
            Tickets`);
        await HomePageHelper.verifyOptionsDisplayedUnderQueues();

        StepLogger.stepId(3);
        StepLogger.step('Click on the Opportunities option menu.');
        await HomePageHelper.clickOpportunitiesUnderQueues();
        StepLogger.verification('The Queued Opportunities page is displayed in the right side pane.');
        await QueuedOpportunitiesPageHelper.verifyQueuedOpportunitiesPageDisplayed();

        StepLogger.stepId(4);
        StepLogger.step('Click on the refresh button on the top left side of the screen');
        await QueuedOpportunitiesPageHelper.clickRefresh();
        StepLogger.verification('The screen is refreshed and data is updated accordingly.');
        await QueuedOpportunitiesPageHelper.verifyQueuedOpportunitiesPageDisplayed();
    });

    // Jira References - COTRAC-135
    it('Verify if user shall be able to view the Add Opportunities screen clicking on Add Opportunities button - [22425416]', async () => {
        // Auto generated by aurea-automation - util on Mon, 01 Apr 2019 13:09:52 GMT

        StepLogger.caseId = 22425416;
        StepLogger.preCondition('Execute C22395398 to login as an administrator');
        await LoginPageHelper.loginAsAdmin();
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        StepLogger.stepId(1);
        StepLogger.step('Click on Queues menu in left side Navigation Pane.');
        await HomePageHelper.clickQueuesLink();
        StepLogger.verification('The Queues menu should be expanded.');
        await HomePageHelper.verifyQueuesMenuIsExpanded();

        StepLogger.stepId(2);
        StepLogger.step('Check the Queues menu option list.');
        StepLogger.verification(`The Queues menu has the following options:
            Opportunities
            Cases
            Tasks
            Events
            Tickets`);
        await HomePageHelper.verifyOptionsDisplayedUnderQueues();

        StepLogger.stepId(3);
        StepLogger.step('Click on the Opportunities option menu.');
        await HomePageHelper.clickOpportunitiesUnderQueues();
        StepLogger.verification('The Queued Opportunities page is displayed in the right side pane.');
        await QueuedOpportunitiesPageHelper.verifyQueuedOpportunitiesPageDisplayed();

        StepLogger.stepId(4);
        StepLogger.step('Click on the notepad sign, Add Opportunities button.');
        await TasksQueuePageHelper.clickAddTaskIcon();
        StepLogger.verification('The Add Opportunities screen is displayed on a new tab clicking the Add Opportunities button.');
        await NewOpportunityPageHelper.verifyNewOpportunityPageIsDisplayed();
    });

    // Jira References - COTRAC-135
    it(`Verify if user shall be able to see the Queued Opportunities Details
		clicking on dollar icon next to Product Type column link - [22425897]`, async () => {
        // Auto generated by aurea-automation - util on Mon, 01 Apr 2019 13:09:51 GMT

        StepLogger.caseId = 22425897;
        StepLogger.preCondition('Execute C22395398 to login as an administrator');
        await LoginPageHelper.loginAsAdmin();
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        StepLogger.stepId(1);
        StepLogger.step('Click on Queues menu in left side Navigation Pane.');
        await HomePageHelper.clickQueuesLink();
        StepLogger.verification('The Queues menu should be expanded.');
        await HomePageHelper.verifyQueuesMenuIsExpanded();

        StepLogger.stepId(2);
        StepLogger.step('Check the Queues menu option list.');
        StepLogger.verification(`The Queues menu has the following options:
            Opportunities
            Cases
            Tasks
            Events
            Tickets`);
        await HomePageHelper.verifyOptionsDisplayedUnderQueues();

        StepLogger.stepId(3);
        StepLogger.step('Click on the Opportunities option menu.');
        await HomePageHelper.clickOpportunitiesUnderQueues();
        StepLogger.verification('The Queued Opportunities page is displayed in the right side pane.');
        await QueuedOpportunitiesPageHelper.verifyQueuedOpportunitiesPageDisplayed();

        StepLogger.stepId(4);
        StepLogger.step('Click on dollar icon next to Product Type column link');
        await QueuedOpportunitiesPageHelper.clickDollar();
        StepLogger.verification('The Queued Opportunities Details are displayed in the new screen.');
        await NewOpportunityPageHelper.verifyDetailOpportunityPageIsDisplayed(false);

        StepLogger.stepId(5);
        StepLogger.step('Click on Close button on the top right side (cross sign) of the screen');
        await NewCasePageHelper.clickCloseButton();
        StepLogger.verification(
            'A warning message is displayed "Are you sure you want to leave this page? Unsaved changes will be lost." with Ok and Cancel button.'
        );

        await NewCasePageHelper.verifyWarningDialog();

        StepLogger.stepId(6);
        StepLogger.step('Click on OK button on warning message dialog.');
        await NewCasePageHelper.clickOkWarningDialog();
        StepLogger.verification('The Queued Opportunities Detail screen is closed and the main application page is displayed again.');
        await NewOpportunityPageHelper.verifyPageClosed();
    });

    // Jira References - COTRAC-135
    it('Verify if user is able to select and view Outside Business from the Grouping Dropdown - [22425910]', async () => {
        // Auto generated by aurea-automation - util on Mon, 01 Apr 2019 13:09:51 GMT

        StepLogger.caseId = 22425910;
        const groupingOption = QueuedOpportunitiesPageConstant.elementNames.outsideBusiness;
        StepLogger.preCondition('Execute C22395398 to login as an administrator');
        await LoginPageHelper.loginAsAdmin();
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        StepLogger.stepId(1);
        StepLogger.step('Click on Queues menu in left side Navigation Pane.');
        await HomePageHelper.clickQueuesLink();
        StepLogger.verification('The Queues menu should be expanded.');
        await HomePageHelper.verifyQueuesMenuIsExpanded();

        StepLogger.stepId(2);
        StepLogger.step('Check the Queues menu option list.');
        StepLogger.verification(`The Queues menu has the following options:
            Opportunities
            Cases
            Tasks
            Events
            Tickets`);
        await HomePageHelper.verifyOptionsDisplayedUnderQueues();

        StepLogger.stepId(3);
        StepLogger.step('Click on the Opportunities option menu.');
        await HomePageHelper.clickOpportunitiesUnderQueues();
        StepLogger.verification('The Queued Opportunities page is displayed in the right side pane.');
        await QueuedOpportunitiesPageHelper.verifyQueuedOpportunitiesPageDisplayed();

        StepLogger.stepId(4);
        StepLogger.step('Select Outside Business from the Grouping Dropdown.');
        await QueuedOpportunitiesPageHelper.selectGroupingOption(groupingOption);
        StepLogger.verification(
            'The data in the grid is grouped by Outside Business and displayed on the screen, it can be expanded and collapsed.'
        );
        await QueuedOpportunitiesPageHelper.verifySelectedGroupingOption(groupingOption);
    });

    // Jira References - COTRAC-135
    it('Verify is user is able to Close Add New Opportunities page. - [22426313]', async () => {
        // Auto generated by aurea-automation - util on Mon, 01 Apr 2019 13:10:12 GMT

        StepLogger.caseId = 22426313;
        StepLogger.preCondition('Execute C22395398 to login as an administrator');
        await LoginPageHelper.loginAsAdmin();
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        StepLogger.stepId(1);
        StepLogger.step('Click on Queues menu in left side Navigation Pane.');
        await HomePageHelper.clickQueuesLink();
        StepLogger.verification('The Queues menu should be expanded.');
        await HomePageHelper.verifyQueuesMenuIsExpanded();

        StepLogger.stepId(2);
        StepLogger.step('Check the Queues menu option list.');
        StepLogger.verification(`The Queues menu has the following options:
            Opportunities
            Cases
            Tasks
            Events
            Tickets`);
        await HomePageHelper.verifyOptionsDisplayedUnderQueues();

        StepLogger.stepId(3);
        StepLogger.step('Click on the Tasks option menu.');
        await HomePageHelper.clickOpportunitiesUnderQueues();
        StepLogger.verification('The Queued Tasks page is displayed in the right side pane.');
        await QueuedOpportunitiesPageHelper.verifyQueuedOpportunitiesPageDisplayed();

        StepLogger.stepId(4);
        StepLogger.step('Click on the dollar sign, Add Opportunities button.');
        await TasksQueuePageHelper.clickAddTaskIcon();
        StepLogger.verification('The Add Opportunities screen is displayed in the new tab on clicking the Add Opportunities button.');
        await NewOpportunityPageHelper.verifyNewOpportunityPageIsDisplayed(false);

        StepLogger.stepId(5);
        StepLogger.step('Click on cross sign on top right hand side of the page to close the Add New Opportunities page.');
        await NewCasePageHelper.clickCloseButton();
        StepLogger.verification(
            'A warning dialog is displayed " Are you sure you want to leave this page? Unsaved changes will be lost." with OK and cancel button'
        );
        await NewCasePageHelper.verifyWarningDialog();

        StepLogger.stepId(6);
        StepLogger.step('Click on OK button on warning dialog.');
        await NewCasePageHelper.clickOkWarningDialog();
        StepLogger.verification(
            'The warning dialog is closed, Add New Task page is closed and the main application page is displayed again.'
        );
        await NewOpportunityPageHelper.verifyPageClosed();
    });

    // Jira References - COTRAC-135
    it('Verify if user is able to select and view Owner from the Grouping Dropdown - [22425957]', async () => {
        // Auto generated by aurea-automation - util on Mon, 01 Apr 2019 13:10:29 GMT

        StepLogger.caseId = 22425957;
        const groupingOption = QueuedOpportunitiesPageConstant.elementNames.owner;

        StepLogger.preCondition('Execute C22395398 to login as an administrator');
        await LoginPageHelper.loginAsAdmin();
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        StepLogger.stepId(1);
        StepLogger.step('Click on Queues menu in left side Navigation Pane.');
        await HomePageHelper.clickQueuesLink();
        StepLogger.verification('The Queues menu should be expanded.');
        await HomePageHelper.verifyQueuesMenuIsExpanded();

        StepLogger.stepId(2);
        StepLogger.step('Check the Queues menu option list.');
        StepLogger.verification(`The Queues menu has the following options:
            Opportunities
            Cases
            Tasks
            Events
            Tickets`);
        await HomePageHelper.verifyOptionsDisplayedUnderQueues();

        StepLogger.stepId(3);
        StepLogger.step('Click on the Opportunities option menu.');
        await HomePageHelper.clickOpportunitiesUnderQueues();
        StepLogger.verification('The Queued Opportunities page is displayed in the right side pane.');
        await QueuedOpportunitiesPageHelper.verifyQueuedOpportunitiesPageDisplayed();

        StepLogger.stepId(4);
        StepLogger.step('Select Owner from the Grouping Dropdown.');
        await QueuedOpportunitiesPageHelper.selectGroupingOption(groupingOption);
        StepLogger.verification('The data in the grid is grouped by Owner and displayed on the screen, it can be expanded and collapsed.');
        await QueuedOpportunitiesPageHelper.verifySelectedGroupingOption(groupingOption);
    });
});
