import { StepLogger } from '../../../../../core/logger/step-logger';
import { PageHelper } from '../../../../components/html/page-helper';
import { HomePageHelper } from '../../../../page-objects/pages/home-page/home-page.helper';
import { HomePage } from '../../../../page-objects/pages/home-page/home-page.po';
import { LoginPageHelper } from '../../../../page-objects/pages/login-page/login-page.helper';
import { QueuedOpportunitiesPageConstant } from '../../../../page-objects/pages/queued-opportunities-page/queued-opportunities-page.constants';
import { QueuedOpportunitiesPageHelper } from '../../../../page-objects/pages/queued-opportunities-page/queued-opportunities-page.helper';
import { SuiteNames } from '../../../helpers/suite-names';

describe(SuiteNames.regressionSuite, () => {
    let loginPageHelper: LoginPageHelper;

    beforeAll(async () => {
        loginPageHelper = LoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
    });

    beforeEach(async () => {
        await PageHelper.restartBrowser();
        await loginPageHelper.goTo();
    });

    // Jira References - COTRAC-135
    it('Verify the list of Queued Cases will be loaded with heading QUEUED OPPORTUNITIES - [22425415]', async () => {
        // Auto generated by aurea-automation - util on Mon, 01 Apr 2019 13:10:11 GMT

        StepLogger.caseId = 22425415;
        StepLogger.preCondition('Execute C22395398 to login as an administrator');
        await LoginPageHelper.loginAsAdmin();
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        StepLogger.stepId(1);
        StepLogger.step('Click on Queues menu in left side Navigation Pane.');
        await HomePageHelper.clickQueuesLink();
        StepLogger.verification('The Queues menu should be expanded.');
        await HomePageHelper.verifyQueuesMenuIsExpanded();

        StepLogger.stepId(2);
        StepLogger.step('Check the Queues menu option list.');
        StepLogger.verification(`The Queues menu has the following options:
            Opportunities
            Cases
            Tasks
            Events
            Tickets`);
        await HomePageHelper.verifyOptionsDisplayedUnderQueues();

        StepLogger.stepId(3);
        StepLogger.step('Click on the Opportunities option menu.');
        await HomePageHelper.clickOpportunitiesUnderQueues();
        StepLogger.verification('The Queued Opportunities page is displayed in the right side pane.');
        await QueuedOpportunitiesPageHelper.verifyQueuedOpportunitiesPageDisplayed();

        StepLogger.stepId(4);
        StepLogger.step('Verify the list of Queued Cases will be loaded with heading QUEUED OPPORTUNITIES');
        StepLogger.verification('The list of Queued Cases will be loaded with heading QUEUED OPPORTUNITIES');
        await QueuedOpportunitiesPageHelper.verifyQueueList();
    });

    // Jira References - COTRAC-135
    it('Verify if user is able to select and view Queue Branch from the Grouping Dropdown - [22425896]', async () => {
        // Auto generated by aurea-automation - util on Mon, 01 Apr 2019 13:10:29 GMT

        StepLogger.caseId = 22425896;
        const groupingOption = QueuedOpportunitiesPageConstant.elementNames.queueBranch;

        StepLogger.preCondition('Execute C22395398 to login as an administrator');
        await LoginPageHelper.loginAsAdmin();
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        StepLogger.stepId(1);
        StepLogger.step('Click on Queues menu in left side Navigation Pane.');
        await HomePageHelper.clickQueuesLink();
        StepLogger.verification('The Queues menu should be expanded.');
        await HomePageHelper.verifyQueuesMenuIsExpanded();

        StepLogger.stepId(2);
        StepLogger.step('Check the Queues menu option list.');
        StepLogger.verification(`The Queues menu has the following options:
            Opportunities
            Cases
            Tasks
            Events
            Tickets`);
        await HomePageHelper.verifyOptionsDisplayedUnderQueues();

        StepLogger.stepId(3);
        StepLogger.step('Click on the Opportunities option menu.');
        await HomePageHelper.clickOpportunitiesUnderQueues();
        StepLogger.verification('The Queued Opportunities page is displayed in the right side pane.');
        await QueuedOpportunitiesPageHelper.verifyQueuedOpportunitiesPageDisplayed();

        StepLogger.stepId(4);
        StepLogger.step('Select Queue Branch from the Grouping Dropdown.');
        await QueuedOpportunitiesPageHelper.selectGroupingOption(groupingOption);
        StepLogger.verification(
            'The data in the grid is grouped by Queue branch and displayed on the screen, it can be expanded and collapsed.'
        );
        await QueuedOpportunitiesPageHelper.verifySelectedGroupingOption(groupingOption);
    });

    // Jira References - COTRAC-135
    it('Verify if user shall be able to Collapse the sections on screen - [22425420]', async () => {
        // Auto generated by aurea-automation - util on Mon, 01 Apr 2019 13:10:29 GMT

        StepLogger.caseId = 22425420;
        const groupingOption = QueuedOpportunitiesPageConstant.elementNames.queueBranch;
        StepLogger.preCondition('Execute C22395398 to login as an administrator');
        await LoginPageHelper.loginAsAdmin();
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        StepLogger.stepId(1);
        StepLogger.step('Click on Queues menu in left side Navigation Pane.');
        await HomePageHelper.clickQueuesLink();
        StepLogger.verification('The Queues menu should be expanded.');
        await HomePageHelper.verifyQueuesMenuIsExpanded();

        StepLogger.stepId(2);
        StepLogger.step('Check the Queues menu option list.');
        StepLogger.verification(`The Queues menu has the following options:
            Opportunities
            Cases
            Tasks
            Events
            Tickets`);
        await HomePageHelper.verifyOptionsDisplayedUnderQueues();

        StepLogger.stepId(3);
        StepLogger.step('Click on the Opportunities option menu.');
        await HomePageHelper.clickOpportunitiesUnderQueues();
        StepLogger.verification('The Queued Opportunities page is displayed in the right side pane.');
        await QueuedOpportunitiesPageHelper.verifyQueuedOpportunitiesPageDisplayed();

        StepLogger.stepId(4);
        StepLogger.step('Select Queue branch from the Grouping Dropdown.');
        await QueuedOpportunitiesPageHelper.selectGroupingOption(groupingOption);
        StepLogger.verification('The data in the grid is grouped by Queue branch and displayed on the screen.');
        await QueuedOpportunitiesPageHelper.verifySelectedGroupingOption(groupingOption);

        StepLogger.stepId(5);
        StepLogger.step('Click on minus sign (-) next to Queue branch group.');
        await QueuedOpportunitiesPageHelper.clickOnCollapseGroupIcon();
        StepLogger.verification('The details of that section on screen is collapsed.');
        await QueuedOpportunitiesPageHelper.verifyGroupCollapsed();
    });

    // Jira References - COTRAC-135
    it('Verify if user is able to filter the Queues from the Queues dropdown - [22425418]', async () => {
        // Auto generated by aurea-automation - util on Mon, 01 Apr 2019 13:10:29 GMT

        StepLogger.caseId = 22425418;
        StepLogger.preCondition('Execute C22395398 to login as an administrator');
        await LoginPageHelper.loginAsAdmin();
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        StepLogger.stepId(1);
        StepLogger.step('Click on Queues menu in left side Navigation Pane.');
        await HomePageHelper.clickQueuesLink();
        StepLogger.verification('The Queues menu should be expanded.');
        await HomePageHelper.verifyQueuesMenuIsExpanded();

        StepLogger.stepId(2);
        StepLogger.step('Check the Queues menu option list.');
        StepLogger.verification(`The Queues menu has the following options:
            Opportunities
            Cases
            Tasks
            Events
            Tickets`);
        await HomePageHelper.verifyOptionsDisplayedUnderQueues();

        StepLogger.stepId(3);
        StepLogger.step('Click on the Opportunities option menu.');
        await HomePageHelper.clickOpportunitiesUnderQueues();
        StepLogger.verification('The Queued Opportunities page is displayed in the right side pane.');
        await QueuedOpportunitiesPageHelper.verifyQueuedOpportunitiesPageDisplayed();

        StepLogger.stepId(4);
        StepLogger.step('Select any option from the Queues dropdown on the top of the page.');
        const selectedView = await QueuedOpportunitiesPageHelper.clickQueueFilter();
        StepLogger.verification('All the Opportunities for the selected Queue option are displayed on the page.');
        await QueuedOpportunitiesPageHelper.verifySelectedQueueOption(selectedView, true);
    });

    // Jira References - COTRAC-135
    it('Verify if user shall be able to Expand the sections on screen - [22425421]', async () => {
        // Auto generated by aurea-automation - util on Mon, 01 Apr 2019 13:10:29 GMT

        StepLogger.caseId = 22425421;
        const groupingOption = QueuedOpportunitiesPageConstant.elementNames.queueBranch;

        StepLogger.preCondition('Execute C22395398 to login as an administrator');
        await LoginPageHelper.loginAsAdmin();
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        StepLogger.stepId(1);
        StepLogger.step('Click on Queues menu in left side Navigation Pane.');
        await HomePageHelper.clickQueuesLink();
        StepLogger.verification('The Queues menu should be expanded.');
        await HomePageHelper.verifyQueuesMenuIsExpanded();

        StepLogger.stepId(2);
        StepLogger.step('Check the Queues menu option list.');
        StepLogger.verification(`The Queues menu has the following options:
            Opportunities
            Cases
            Tasks
            Events
            Tickets`);
        await HomePageHelper.verifyOptionsDisplayedUnderQueues();

        StepLogger.stepId(3);
        StepLogger.step('Click on the Opportunities option menu.');
        await HomePageHelper.clickOpportunitiesUnderQueues();
        StepLogger.verification('The Queued Opportunities page is displayed in the right side pane.');
        await QueuedOpportunitiesPageHelper.verifyQueuedOpportunitiesPageDisplayed();

        StepLogger.stepId(4);
        StepLogger.step('Select Queue branch from the Grouping Dropdown.');
        await QueuedOpportunitiesPageHelper.selectGroupingOption(groupingOption);
        StepLogger.verification('The data in the grid is grouped by Queue branch and displayed on the screen.');
        await QueuedOpportunitiesPageHelper.verifySelectedGroupingOption(groupingOption);

        StepLogger.stepId(5);
        StepLogger.step('Click on minus sign (-) next to Queue branch group.');
        await QueuedOpportunitiesPageHelper.clickOnCollapseGroupIcon();
        StepLogger.verification('The details of that section on screen is collapsed.');
        await QueuedOpportunitiesPageHelper.verifyGroupCollapsed();

        StepLogger.stepId(6);
        StepLogger.step('Click on plus sign (+) next to Queue branch group.');
        await QueuedOpportunitiesPageHelper.clickOnExpandGroupIcon();
        StepLogger.verification('The details of that section on screen is expanded');
        await QueuedOpportunitiesPageHelper.verifyGroupExpanded();
    });
});
