import { StepLogger } from '../../../../../core/logger/step-logger';
import { PageHelper } from '../../../../components/html/page-helper';
import { HomePageOneHelper } from '../../../../page-objects/pages/home-page/home-page-one.helper';
import { HomePageConstant } from '../../../../page-objects/pages/home-page/home-page.constants';
import { HomePageHelper } from '../../../../page-objects/pages/home-page/home-page.helper';
import { LoginPageHelper } from '../../../../page-objects/pages/login-page/login-page.helper';
import { NewCasePageHelper } from '../../../../page-objects/pages/new-case-page/new-case-page.helper';
import { NewOpportunityPageConstant } from '../../../../page-objects/pages/new-opportunity-page/new-opportunity-page.constants';
import { NewOpportunityPageHelper } from '../../../../page-objects/pages/new-opportunity-page/new-opportunity-page.helper';
import { NewProspectPageConstant } from '../../../../page-objects/pages/new-prospect-page/new-prospect-page.constants';
import { NewProspectPageHelper } from '../../../../page-objects/pages/new-prospect-page/new-prospect-page.helper';

import { SuiteNames } from '../../../helpers/suite-names';

describe(SuiteNames.regressionSuite, () => {
    let uniqueName = PageHelper.getUniqueId();
    let loginPageHelper: LoginPageHelper;

    beforeAll(async () => {
        loginPageHelper = LoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
    });

    beforeEach(async () => {
        await PageHelper.restartBrowser();
        await loginPageHelper.goTo();
        await LoginPageHelper.loginAsAdmin();
    });

    // Jira References - COTRAC-95
    it('Verify if user shall be able to access the Check Existing Contact modal screen - [22984007]', async () => {
        // Auto generated by aurea-automation - util on Wed, 27 Mar 2019 23:52:38 GMT

        StepLogger.caseId = 22984007;
        StepLogger.stepId(1);
        StepLogger.step('Click on New menu button.');
        await HomePageHelper.clickNewLink();
        StepLogger.verification('The New menu list is displayed successfully.');
        await HomePageHelper.verifyOptionsUnderNew();

        StepLogger.stepId(2);
        StepLogger.step('Click on Commercial Prospect menu button.');
        await HomePageHelper.clickCommercialProspectUnderNew();
        StepLogger.verification('The "Check Existing Contact" modal screen is displayed successfully.');
        await HomePageHelper.verifyCheckExistingContactDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Fill the Company input text with "test" text and click on Search Contacts button.');
        await HomePageHelper.enterCompanyNameAndClickSearchButton(NewOpportunityPageConstant.testData.companyName);
        StepLogger.verification('The contacts list is displayed successfully.');
        await NewOpportunityPageHelper.verifyContactResultsAreDisplayed();
    });

    // Jira References - COTRAC-95
    it('Verify if Company input field is a mandatory field - [22984010]', async () => {
        // Auto generated by aurea-automation - util on Wed, 27 Mar 2019 23:53:38 GMT

        StepLogger.caseId = 22984010;
        StepLogger.stepId(1);
        StepLogger.step('Click on New menu button.');
        await HomePageHelper.clickNewLink();
        StepLogger.verification('The New menu list is displayed successfully.');
        await HomePageHelper.verifyOptionsUnderNew();

        StepLogger.stepId(2);
        StepLogger.step('Click on Commercial Prospect menu button.');
        await HomePageHelper.clickCommercialProspectUnderNew();
        StepLogger.verification('The "Check Existing Contact" modal screen is displayed successfully.');
        await HomePageHelper.verifyCheckExistingContactDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on Search Contacts button.');
        await HomePageHelper.clickSearchContactsOnCheckExistingContactModal(false);
        StepLogger.verification('The mandatory message is displayed under the Company input field and a popup is opened.');
        await HomePageHelper.verifyAlertError();
    });

    // Jira References - COTRAC-95
    it('Verify if user shall be able to search a contact - [22984032]', async () => {
        // Auto generated by aurea-automation - util on Wed, 27 Mar 2019 23:53:38 GMT

        StepLogger.caseId = 22984032;
        StepLogger.stepId(1);
        StepLogger.step('Click on New menu button.');
        await HomePageHelper.clickNewLink();
        StepLogger.verification('The New menu list is displayed successfully.');
        await HomePageHelper.verifyOptionsUnderNew();

        StepLogger.stepId(2);
        StepLogger.step('Click on Commercial Prospect menu button.');
        await HomePageHelper.clickCommercialProspectUnderNew();
        StepLogger.verification('The "Check Existing Contact" modal screen is displayed successfully.');
        await HomePageHelper.verifyCheckExistingContactDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Fill the Company input field with text "test" and click on Search Contact button.');
        await HomePageHelper.enterCompanyNameAndClickSearchButton(NewOpportunityPageConstant.testData.companyName);
        StepLogger.verification('The Contact list is displayed successfully.');
        await HomePageHelper.verifyContactsListIsDisplayed();
    });

    // Jira References - COTRAC-95
    it('Verify if user shall be able to create a new prospect with "Do not contact in marketing campaigns." ' +
        'toggle button enabled - [22984045]', async () => {
            // Auto generated by aurea-automation - util on Wed, 27 Mar 2019 23:53:38 GMT
            const workPhone = NewProspectPageConstant.testData.workPhone;

            StepLogger.caseId = 22984045;
            StepLogger.stepId(1);
            StepLogger.step('Click on New menu button.');
            await HomePageHelper.clickNewLink();
            StepLogger.verification('The New menu list is displayed successfully.');
            await HomePageHelper.verifyOptionsUnderNew();

            StepLogger.stepId(2);
            StepLogger.step('Click on Commercial Prospect menu button.');
            await HomePageHelper.clickCommercialProspectUnderNew();
            StepLogger.verification('The "Check Existing Contact" modal screen is displayed successfully.');
            await HomePageHelper.verifyCheckExistingContactDisplayed();

            StepLogger.stepId(3);
            StepLogger.step('Fill the Company input field.');
            await HomePageHelper.enterCompanyOnCheckExistingContactModal(uniqueName);
            StepLogger.verification('The Company input field is filled successfully.');
            await HomePageHelper.verifyCompanyIsEnteredOnCheckExistingContactModal(uniqueName);

            StepLogger.stepId(4);
            StepLogger.step('Fill the First input field with a nonexistent company name.');
            await HomePageHelper.enterFirstNameOnCheckExistingContactModal(uniqueName);
            StepLogger.verification('The First Name input field is filled successfully.');
            await HomePageHelper.verifyFirstNameIsEnteredOnCheckExistingContactModal(uniqueName);

            StepLogger.stepId(5);
            StepLogger.step('Fill the Last input field.');
            await HomePageHelper.enterLastNameOnCheckExistingContactModal(uniqueName);
            StepLogger.verification('The Last Name input field is filled successfully.');
            await HomePageHelper.verifyLastNameIsEnteredOnCheckExistingContactModal(uniqueName);

            StepLogger.stepId(6);
            StepLogger.step('Select Commercial option in the Return dropdown list.');
            await HomePageHelper.selectReturnOptionOnCheckExistingContactModal(HomePageConstant.commercial);
            StepLogger.verification('The Commercial option is displayed in the dropdown field.');
            await HomePageHelper.verifyReturnOptionIsSelectedOnCheckExistingContactModal(HomePageConstant.commercial);

            StepLogger.stepId(7);
            StepLogger.step('Click on Search Contacts button.');
            await HomePageHelper.clickSearchContactsOnCheckExistingContactModal();
            StepLogger.verification('The Continue With New Prospect button is enabled.');
            await HomePageHelper.verifyContinueWithNewProspectIsEnabled();

            StepLogger.stepId(8);
            StepLogger.step('Click on Continue With New Prospect button.');
            await HomePageHelper.clickContinueWithNewProspectButton();
            StepLogger.verification('The New Prospect screen is displayed successfully.');
            await NewProspectPageHelper.verifyNewProspectCommercialPageIsDisplayed(false);

            StepLogger.stepId(9);
            StepLogger.step('Fill the Work Phone input field.');
            await NewProspectPageHelper.typeInPhoneTb(workPhone);
            StepLogger.verification('The Work Phone input field is filled successfully.');
            await NewProspectPageHelper.verifyPhoneIsEnteredOnCheckExistingContactModal(workPhone);

            StepLogger.stepId(10);
            StepLogger.step('Enable the "Do Not Contact In Marketing Campaigns" toggle button.');
            await NewProspectPageHelper.clickDoNotContactInCampaigns();
            StepLogger.verification('The toggle button is enabled successfully.');
            await NewProspectPageHelper.verifyDoNotContactInCampaigns();

            StepLogger.stepId(11);
            StepLogger.step('Click on Save button.');
            await NewProspectPageHelper.clickSaveButton();
            StepLogger.verification('The New Prospect Company is saved successfully.');
            await NewProspectPageHelper.verifyProspectHeaderSection();
        });

    // Jira References - COTRAC-95
    it('Verify if user shall be able to update the prospect company created - [22985960]', async () => {
        // Auto generated by aurea-automation - util on Wed, 03 Apr 2019 13:16:52 GMT

        StepLogger.caseId = 22985960;
        StepLogger.stepId(1);
        StepLogger.step('Click on Search button.');
        await HomePageHelper.clickSearchButton();
        StepLogger.verification('The Search input field and dropdown list is displayed.');
        await HomePageHelper.verifySearchCriteriaIsDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Select Contact in the Search dropdown list.');
        await HomePageHelper.selectContactsFromSearchDropdown();
        StepLogger.verification('The Contact option is selected.');
        await HomePageHelper.verifyContactsOptionIsSelectedInDropdown();

        StepLogger.stepId(3);
        StepLogger.step('Fill the search input field with the company name ' +
            'created in the step 5 mentioned in the preconditions and click on search button.');
        await NewCasePageHelper.clickSearchText();
        await NewCasePageHelper.enterSearchText(uniqueName);
        StepLogger.verification('The company created is displayed in the list.');
        await NewCasePageHelper.verifyCasesListDisplayed();

        StepLogger.stepId(4);
        StepLogger.step('Click on company card.');
        await NewCasePageHelper.clickCompanyCard(uniqueName);
        StepLogger.verification('The Prospect company screen is displayed.');
        await NewProspectPageHelper.verifyCompanyTitleDisplayed(uniqueName, false);

        StepLogger.stepId(5);
        StepLogger.step('Update the fields Company, Work Phone and click on save button.');
        uniqueName = await NewProspectPageHelper.fillCompanyAndPhoneAndSave();
        StepLogger.verification('The Company and Work Phone is updated successfully.');
        await NewProspectPageHelper.verifySavedCompanyNameAndWorkphone(uniqueName);
    });

    // Jira References - COTRAC-95
    it('Verify if user shall be able to search the new prospect company created - [22984064]', async () => {
        // Auto generated by aurea-automation - util on Wed, 27 Mar 2019 23:53:38 GMT

        StepLogger.caseId = 22984064;
        StepLogger.stepId(1);
        StepLogger.step('Click on Search button.');
        await HomePageHelper.clickSearchButton();
        StepLogger.verification('The Search input field and dropdown list is displayed.');
        await HomePageHelper.verifySearchCriteriaIsDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Select Contact in the Search dropdown list.');
        await HomePageHelper.selectContactsFromSearchDropdown();
        StepLogger.verification('The Contact option is selected.');
        await HomePageHelper.verifyContactsOptionIsSelectedInDropdown();

        StepLogger.stepId(3);
        StepLogger.step('Fill the search input field with the company name created in the step 5 mentioned in the preconditions and click on search button.');
        await NewCasePageHelper.clickSearchText();
        await NewCasePageHelper.enterSearchText(uniqueName);
        StepLogger.verification('The company created is displayed in the list.');
        await NewCasePageHelper.verifyCasesListDisplayed();
    });

    // Jira References - COTRAC-95
    it('Verify if user can see the Search Contacts button on the Check Existing Contact modal - [22984021]', async () => {
        // Auto generated by aurea-automation - util on Fri, 29 Mar 2019 21:54:10 GMT

        StepLogger.caseId = 22984021;
        StepLogger.stepId(1);
        StepLogger.step('Click on New menu button.');
        await HomePageHelper.clickNewLink();
        StepLogger.verification('The New menu list is displayed successfully.');
        await HomePageHelper.verifyOptionsUnderNew();

        StepLogger.stepId(2);
        StepLogger.step('Click on Commercial Prospect menu button.');
        await HomePageHelper.clickCommercialProspectUnderNew();
        StepLogger.verification('The "Check Existing Contact" modal screen is displayed successfully.');
        await HomePageHelper.verifyCheckExistingContactDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Check if the Search Contacts button.');
        StepLogger.verification('The Contacts button is displayed successfully.');
        await HomePageHelper.verifySearchContactsOnCheckExistingContactModal();
    });

    // Jira References - COTRAC-95
    it('Verify if user can see the Last Name input field on the Check Existing Contact modal - [22984018]', async () => {
        // Auto generated by aurea-automation - util on Fri, 29 Mar 2019 21:54:11 GMT

        StepLogger.caseId = 22984018;
        StepLogger.stepId(1);
        StepLogger.step('Click on New menu button.');
        await HomePageHelper.clickNewLink();
        StepLogger.verification('The New menu list is displayed successfully.');
        await HomePageHelper.verifyOptionsUnderNew();

        StepLogger.stepId(2);
        StepLogger.step('Click on Commercial Prospect menu button.');
        await HomePageHelper.clickCommercialProspectUnderNew();
        StepLogger.verification('The "Check Existing Contact" modal screen is displayed successfully.');
        await HomePageHelper.verifyCheckExistingContactDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Check if the Last Name input field.');
        StepLogger.verification('The Last Name input field is displayed successfully.');
        await HomePageHelper.verifyLastNameIsDisplayedOnCheckExistingContactModal();
    });

    // Jira References - COTRAC-95
    it('Verify if user can see the text information on top of the screen - [22984008]', async () => {
        // Auto generated by aurea-automation - util on Fri, 29 Mar 2019 21:54:11 GMT

        StepLogger.caseId = 22984008;
        StepLogger.stepId(1);
        StepLogger.step('Click on New menu button.');
        await HomePageHelper.clickNewLink();
        StepLogger.verification('The New menu list is displayed successfully.');
        await HomePageHelper.verifyOptionsUnderNew();

        StepLogger.stepId(2);
        StepLogger.step('Click on Commercial Prospect menu button.');
        await HomePageHelper.clickCommercialProspectUnderNew();
        StepLogger.verification('The "Check Existing Contact" modal screen is displayed successfully.');
        await HomePageHelper.verifyCheckExistingContactDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Check the information text on top of the screen.');
        StepLogger.verification('The text "Enter the following new prospect information to ' +
            'confirm that the prospect does not already exist". is displayed successfully.');
        await HomePageHelper.verifyEnterNewProspectOnCheckExistingContactModal();
    });

    // Jira References - COTRAC-95
    it('Verify if user can see the First Name input field on the Check Existing Contact modal - [22984017]', async () => {
        // Auto generated by aurea-automation - util on Fri, 29 Mar 2019 21:54:11 GMT

        StepLogger.caseId = 22984017;
        StepLogger.stepId(1);
        StepLogger.step('Click on New menu button.');
        await HomePageHelper.clickNewLink();
        StepLogger.verification('The New menu list is displayed successfully.');
        await HomePageHelper.verifyOptionsUnderNew();

        StepLogger.stepId(2);
        StepLogger.step('Click on Commercial Prospect menu button.');
        await HomePageHelper.clickCommercialProspectUnderNew();
        StepLogger.verification('The "Check Existing Contact" modal screen is displayed successfully.');
        await HomePageHelper.verifyCheckExistingContactDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Check if the First Name input field.');
        StepLogger.verification('The First Name input field is displayed successfully.');
        await HomePageHelper.verifyFirstNameIsDisplayedOnCheckExistingContactModal();
    });

    // Jira References - COTRAC-95
    it('Verify if user can see the Return dropdown list on the Check Existing Contact modal - [22984019]', async () => {
        // Auto generated by aurea-automation - util on Fri, 29 Mar 2019 21:54:11 GMT

        StepLogger.caseId = 22984019;
        StepLogger.stepId(1);
        StepLogger.step('Click on New menu button.');
        await HomePageHelper.clickNewLink();
        StepLogger.verification('The New menu list is displayed successfully.');
        await HomePageHelper.verifyOptionsUnderNew();

        StepLogger.stepId(2);
        StepLogger.step('Click on Commercial Prospect menu button.');
        await HomePageHelper.clickCommercialProspectUnderNew();
        StepLogger.verification('The "Check Existing Contact" modal screen is displayed successfully.');
        await HomePageHelper.verifyCheckExistingContactDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Check if the Return dropdown list field.');
        StepLogger.verification('The Return dropdown list field is displayed successfully.');
        await HomePageHelper.verifyReturnOptionOnCheckExistingContactModal();
    });

    // Jira References - COTRAC-95
    it('Verify if user can see the grid columns on the Check Existing Contact modal - [22984022]', async () => {
        // Auto generated by aurea-automation - util on Fri, 29 Mar 2019 21:54:11 GMT

        StepLogger.caseId = 22984022;
        StepLogger.stepId(1);
        StepLogger.step('Click on New menu button.');
        await HomePageHelper.clickNewLink();
        StepLogger.verification('The New menu list is displayed successfully.');
        await HomePageHelper.verifyOptionsUnderNew();

        StepLogger.stepId(2);
        StepLogger.step('Click on Commercial Prospect menu button.');
        await HomePageHelper.clickCommercialProspectUnderNew();
        StepLogger.verification('The "Check Existing Contact" modal screen is displayed successfully.');
        await HomePageHelper.verifyCheckExistingContactDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Check the Contacts grid columns list.');
        StepLogger.verification(`The grid is displayed with columns:
            -Name
            -Address
            -Work Phone
            -Home Phone
            -Tax ID
            -Details`);
        await HomePageHelper.verifyContactGridHeader();
    });

    // Jira References - COTRAC-95
    it('Verify if user can see the grid default text on the Check Existing Contact modal - [22984024]', async () => {
        // Auto generated by aurea-automation - util on Fri, 29 Mar 2019 21:54:11 GMT

        StepLogger.caseId = 22984024;
        StepLogger.stepId(1);
        StepLogger.step('Click on New menu button.');
        await HomePageHelper.clickNewLink();
        StepLogger.verification('The New menu list is displayed successfully.');
        await HomePageHelper.verifyOptionsUnderNew();

        StepLogger.stepId(2);
        StepLogger.step('Click on Commercial Prospect menu button.');
        await HomePageHelper.clickCommercialProspectUnderNew();
        StepLogger.verification('The "Check Existing Contact" modal screen is displayed successfully.');
        await HomePageHelper.verifyCheckExistingContactDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Check the grid message.');
        StepLogger.verification('The message "Please enter prospect information above" is displayed successfully.');
        await HomePageOneHelper.verifyGridMessage();
    });

    // Jira References - COTRAC-95
    it('Verify if user can see the Use Selected Contact button on the Check Existing Contact modal - [22984027]', async () => {
        // Auto generated by aurea-automation - util on Fri, 29 Mar 2019 21:54:11 GMT

        StepLogger.caseId = 22984027;
        StepLogger.stepId(1);
        StepLogger.step('Click on New menu button.');
        await HomePageHelper.clickNewLink();
        StepLogger.verification('The New menu list is displayed successfully.');
        await HomePageHelper.verifyOptionsUnderNew();

        StepLogger.stepId(2);
        StepLogger.step('Click on Commercial Prospect menu button.');
        await HomePageHelper.clickCommercialProspectUnderNew();
        StepLogger.verification('The "Check Existing Contact" modal screen is displayed successfully.');
        await HomePageHelper.verifyCheckExistingContactDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Check the Use Selected Contact button.');
        StepLogger.verification('The Use Selected Contact button is displayed disabled by default successfully.');
        await HomePageOneHelper.verifyUseSelectedContact();
    });

    // Jira References - COTRAC-95
    it('Verify if the Check Existing Contact grid pagination tool is working properly - [22984025]', async () => {
        // Auto generated by aurea-automation - util on Fri, 29 Mar 2019 21:54:11 GMT
        const pageOne = HomePageConstant.elementNames.one;
        const pageTwo = HomePageConstant.elementNames.two;

        StepLogger.caseId = 22984025;
        StepLogger.stepId(1);
        StepLogger.step('Click on New menu button.');
        await HomePageHelper.clickNewLink();
        StepLogger.verification('The New menu list is displayed successfully.');
        await HomePageHelper.verifyOptionsUnderNew();

        StepLogger.stepId(2);
        StepLogger.step('Click on Commercial Prospect menu button.');
        await HomePageHelper.clickCommercialProspectUnderNew();
        StepLogger.verification('The "Check Existing Contact" modal screen is displayed successfully.');
        await HomePageHelper.verifyCheckExistingContactDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Fill the company input field with char "a" and click on Search Contacts button.');
        await HomePageHelper.enterCompanyNameAndClickSearchButton(NewOpportunityPageConstant.testData.companyA);
        StepLogger.verification('The list of contacts is displayed successfully.');
        await HomePageHelper.verifyContactListCheckExistingContactModal();

        StepLogger.stepId(4);
        StepLogger.step('Click on ">" right arrow button.');
        await HomePageHelper.clickOnNextArrow();
        StepLogger.verification('The next page is displayed successfully.');
        await HomePageHelper.verifyNavigatedToCorrectPage(pageOne);

        StepLogger.stepId(5);
        StepLogger.step('Click on "<" left arrow button.');
        await HomePageHelper.clickOnPreviousArrow();
        StepLogger.verification('The previous page is displayed successfully.');
        await HomePageHelper.verifyNavigatedToCorrectPage(pageTwo);

        StepLogger.stepId(6);
        StepLogger.step('Click on page number button.');
        await HomePageHelper.clickOnPageNumber(pageTwo);
        StepLogger.verification('The page number selected is displayed successfully.');
        await HomePageHelper.verifyNavigatedToCorrectPage(pageOne);
    });

    // Jira References - COTRAC-95
    it('Verify if user can see the Cancel button on the Check Existing Contact modal - [22984028]', async () => {
        // Auto generated by aurea-automation - util on Fri, 29 Mar 2019 21:54:13 GMT

        StepLogger.caseId = 22984028;
        StepLogger.stepId(1);
        StepLogger.step('Click on New menu button.');
        await HomePageHelper.clickNewLink();
        StepLogger.verification('The New menu list is displayed successfully.');
        await HomePageHelper.verifyOptionsUnderNew();

        StepLogger.stepId(2);
        StepLogger.step('Click on Commercial Prospect menu button.');
        await HomePageHelper.clickCommercialProspectUnderNew();
        StepLogger.verification('The "Check Existing Contact" modal screen is displayed successfully.');
        await HomePageHelper.verifyCheckExistingContactDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Check the Cancel button on screen.');
        StepLogger.verification('The Cancel button is displayed successfully.');
        await HomePageOneHelper.verifyCancel();
    });
});
