import { StepLogger } from '../../../../../core/logger/step-logger';
import { PageHelper } from '../../../../components/html/page-helper';
import { HomePageOneHelper } from '../../../../page-objects/pages/home-page/home-page-one.helper';
import { HomePageConstant } from '../../../../page-objects/pages/home-page/home-page.constants';
import { HomePageHelper } from '../../../../page-objects/pages/home-page/home-page.helper';
import { LoginPageHelper } from '../../../../page-objects/pages/login-page/login-page.helper';
import { NewAccountPageHelper } from '../../../../page-objects/pages/new-account-page/new-account-page.helper';
import { NewProspectPageHelper } from '../../../../page-objects/pages/new-prospect-page/new-prospect-page.helper';

import { SuiteNames } from '../../../helpers/suite-names';

describe(SuiteNames.regressionSuite, () => {
    const uniqueName = PageHelper.getUniqueId();
    const commercial = HomePageConstant.commercial;
    let loginPageHelper: LoginPageHelper;

    beforeAll(async () => {
        loginPageHelper = LoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
    });

    beforeEach(async () => {
        await PageHelper.restartBrowser();
        await loginPageHelper.goTo();
        await LoginPageHelper.loginAsAdmin();
    });

    // Jira References - COTRAC-95
    it('Verify if user shall be able to close the Check Existing Contact modal clicking on "X" button - [22984030]', async () => {
        // Auto generated by aurea-automation - util on Mon, 01 Apr 2019 13:50:27 GMT

        StepLogger.caseId = 22984030;
        StepLogger.stepId(1);
        StepLogger.step('Click on New menu button.');
        await HomePageHelper.clickNewLink();
        StepLogger.verification('The New menu list is displayed successfully.');
        await HomePageHelper.verifyOptionsUnderNew();

        StepLogger.stepId(2);
        StepLogger.step('Click on Commercial Prospect menu button.');
        await HomePageHelper.clickCommercialProspectUnderNew();
        StepLogger.verification('The "Check Existing Contact" modal screen is displayed successfully.');
        await HomePageHelper.verifyCheckExistingContactDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on "x" button.');
        await HomePageOneHelper.clickCrossButton();
        StepLogger.verification('The Check Existing Contact screen is closed successfully.');
        await HomePageOneHelper.verifyCheckExistingContactClosed();
    });

    // Jira References - COTRAC-95
    it('Verify if user shall be able to close the Check Existing Contact modal clicking on Cancel button - [22984029]', async () => {
        // Auto generated by aurea-automation - util on Mon, 01 Apr 2019 13:50:28 GMT

        StepLogger.caseId = 22984029;
        StepLogger.stepId(1);
        StepLogger.step('Click on New menu button.');
        await HomePageHelper.clickNewLink();
        StepLogger.verification('The New menu list is displayed successfully.');
        await HomePageHelper.verifyOptionsUnderNew();

        StepLogger.stepId(2);
        StepLogger.step('Click on Commercial Prospect menu button.');
        await HomePageHelper.clickCommercialProspectUnderNew();
        StepLogger.verification('The "Check Existing Contact" modal screen is displayed successfully.');
        await HomePageHelper.verifyCheckExistingContactDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on Cancel button.');
        await HomePageOneHelper.clickCancel();
        StepLogger.verification('The Check Existing Contact screen is closed successfully.');
        await HomePageOneHelper.verifyCheckExistingContactClosed();
    });

    // Jira References - COTRAC-95
    it('Verify if user shall be able to close the New Prospect screen clicking on Close button - [22984037]', async () => {
        // Auto generated by aurea-automation - util on Mon, 01 Apr 2019 13:50:29 GMT

        StepLogger.caseId = 22984037;
        StepLogger.stepId(1);
        StepLogger.step('Click on New menu button.');
        await HomePageHelper.clickNewLink();
        StepLogger.verification('The New menu list is displayed successfully.');
        await HomePageHelper.verifyOptionsUnderNew();

        StepLogger.stepId(2);
        StepLogger.step('Click on Commercial Prospect menu button.');
        await HomePageHelper.clickCommercialProspectUnderNew();
        StepLogger.verification('The "Check Existing Contact" modal screen is displayed successfully.');
        await HomePageHelper.verifyCheckExistingContactDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Fill the Company input field.');
        await HomePageHelper.enterCompanyOnCheckExistingContactModal(uniqueName);
        StepLogger.verification('The Company input field is filled successfully.');
        await HomePageHelper.verifyCompanyIsEnteredOnCheckExistingContactModal(uniqueName);

        StepLogger.stepId(4);
        StepLogger.step('Fill the First input field with a nonexistent company name.');
        await HomePageHelper.enterFirstNameOnCheckExistingContactModal(uniqueName);
        StepLogger.verification('The First Name input field is filled successfully.');
        await HomePageHelper.verifyFirstNameIsEnteredOnCheckExistingContactModal(uniqueName);

        StepLogger.stepId(5);
        StepLogger.step('Fill the Last input field.');
        await HomePageHelper.enterLastNameOnCheckExistingContactModal(uniqueName);
        StepLogger.verification('The Last Name input field is filled successfully.');
        await HomePageHelper.verifyLastNameIsEnteredOnCheckExistingContactModal(uniqueName);

        StepLogger.stepId(6);
        StepLogger.step('Select Commercial option in the Return dropdown list.');
        await HomePageHelper.selectReturnOptionOnCheckExistingContactModal(commercial);
        StepLogger.verification('The Commercial option is displayed in the dropdown field.');
        await HomePageHelper.verifyReturnOptionIsSelectedOnCheckExistingContactModal(commercial);

        StepLogger.stepId(7);
        StepLogger.step('Click on Search Contacts button.');
        await HomePageHelper.clickSearchContactsOnCheckExistingContactModal();
        StepLogger.verification('The Continue With New Prospect button is enabled.');
        await HomePageHelper.verifyContinueWithNewProspectIsEnabled();

        StepLogger.stepId(8);
        StepLogger.step('Click on Continue With New Prospect button.');
        await HomePageHelper.clickContinueWithNewProspectButton();
        StepLogger.verification('The New Prospect screen is displayed successfully.');
        await NewProspectPageHelper.verifyNewProspectCommercialPageIsDisplayed(false);

        StepLogger.stepId(9);
        StepLogger.step('Click on Close button.');
        await NewProspectPageHelper.clickCloseButton();
        StepLogger.verification('The popup confirmation is displayed.');
        await NewAccountPageHelper.verifyConfirmWindow();

        StepLogger.stepId(10);
        StepLogger.step('Click on Ok button.');
        await NewAccountPageHelper.clickDialogOk();
        StepLogger.verification('The New Prospect screen is closed successfully.');
        await NewProspectPageHelper.verifyNewProspectPageClosed();
    });

    // Jira References - COTRAC-95
    it('Verify if New Prospect header screen is displaying properly - [22984036]', async () => {
        // Auto generated by aurea-automation - util on Mon, 01 Apr 2019 13:50:29 GMT

        StepLogger.caseId = 22984036;
        StepLogger.stepId(1);
        StepLogger.step('Click on New menu button.');
        await HomePageHelper.clickNewLink();
        StepLogger.verification('The New menu list is displayed successfully.');
        await HomePageHelper.verifyOptionsUnderNew();

        StepLogger.stepId(2);
        StepLogger.step('Click on Commercial Prospect menu button.');
        await HomePageHelper.clickCommercialProspectUnderNew();
        StepLogger.verification('The "Check Existing Contact" modal screen is displayed successfully.');
        await HomePageHelper.verifyCheckExistingContactDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Fill the Company input field.');
        await HomePageHelper.enterCompanyOnCheckExistingContactModal(uniqueName);
        StepLogger.verification('The Company input field is filled successfully.');
        await HomePageHelper.verifyCompanyIsEnteredOnCheckExistingContactModal(uniqueName);

        StepLogger.stepId(4);
        StepLogger.step('Fill the First input field with a nonexistent company name.');
        await HomePageHelper.enterFirstNameOnCheckExistingContactModal(uniqueName);
        StepLogger.verification('The First Name input field is filled successfully.');
        await HomePageHelper.verifyFirstNameIsEnteredOnCheckExistingContactModal(uniqueName);

        StepLogger.stepId(5);
        StepLogger.step('Fill the Last input field.');
        await HomePageHelper.enterLastNameOnCheckExistingContactModal(uniqueName);
        StepLogger.verification('The Last Name input field is filled successfully.');
        await HomePageHelper.verifyLastNameIsEnteredOnCheckExistingContactModal(uniqueName);

        StepLogger.stepId(6);
        StepLogger.step('Select Commercial option in the Return dropdown list.');
        await HomePageHelper.selectReturnOptionOnCheckExistingContactModal(commercial);
        StepLogger.verification('The Commercial option is displayed in the dropdown field.');
        await HomePageHelper.verifyReturnOptionIsSelectedOnCheckExistingContactModal(commercial);

        StepLogger.stepId(7);
        StepLogger.step('Click on Search Contacts button.');
        await HomePageHelper.clickSearchContactsOnCheckExistingContactModal();
        StepLogger.verification('The Continue With New Prospect button is enabled.');
        await HomePageHelper.verifyContinueWithNewProspectIsEnabled();

        StepLogger.stepId(8);
        StepLogger.step('Click on Continue With New Prospect button.');
        await HomePageHelper.clickContinueWithNewProspectButton();
        StepLogger.verification('The New Prospect screen is displayed successfully.');
        await NewProspectPageHelper.verifyNewProspectCommercialPageIsDisplayed(false);

        StepLogger.stepId(9);
        StepLogger.step('Check the New Prospect Header screen.');
        StepLogger.verification(`The components list is displayed:
            -New Prospect title
            -Save button
            -Close button`);
        await NewProspectPageHelper.verifyHeaderSection();
    });

    // Jira References - COTRAC-95
    it('Verify if Work Phone is a mandatory field - [22984039]', async () => {
        // Auto generated by aurea-automation - util on Mon, 01 Apr 2019 13:50:29 GMT

        StepLogger.caseId = 22984039;
        StepLogger.stepId(1);
        StepLogger.step('Click on New menu button.');
        await HomePageHelper.clickNewLink();
        StepLogger.verification('The New menu list is displayed successfully.');
        await HomePageHelper.verifyOptionsUnderNew();

        StepLogger.stepId(2);
        StepLogger.step('Click on Commercial Prospect menu button.');
        await HomePageHelper.clickCommercialProspectUnderNew();
        StepLogger.verification('The "Check Existing Contact" modal screen is displayed successfully.');
        await HomePageHelper.verifyCheckExistingContactDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Fill the Company input field.');
        await HomePageHelper.enterCompanyOnCheckExistingContactModal(uniqueName);
        StepLogger.verification('The Company input field is filled successfully.');
        await HomePageHelper.verifyCompanyIsEnteredOnCheckExistingContactModal(uniqueName);

        StepLogger.stepId(4);
        StepLogger.step('Fill the First input field with a nonexistent company name.');
        await HomePageHelper.enterFirstNameOnCheckExistingContactModal(uniqueName);
        StepLogger.verification('The First Name input field is filled successfully.');
        await HomePageHelper.verifyFirstNameIsEnteredOnCheckExistingContactModal(uniqueName);

        StepLogger.stepId(5);
        StepLogger.step('Fill the Last input field.');
        await HomePageHelper.enterLastNameOnCheckExistingContactModal(uniqueName);
        StepLogger.verification('The Last Name input field is filled successfully.');
        await HomePageHelper.verifyLastNameIsEnteredOnCheckExistingContactModal(uniqueName);

        StepLogger.stepId(6);
        StepLogger.step('Select Commercial option in the Return dropdown list.');
        await HomePageHelper.selectReturnOptionOnCheckExistingContactModal(commercial);
        StepLogger.verification('The Commercial option is displayed in the dropdown field.');
        await HomePageHelper.verifyReturnOptionIsSelectedOnCheckExistingContactModal(commercial);

        StepLogger.stepId(7);
        StepLogger.step('Click on Search Contacts button.');
        await HomePageHelper.clickSearchContactsOnCheckExistingContactModal();
        StepLogger.verification('The Continue With New Prospect button is enabled.');
        await HomePageHelper.verifyContinueWithNewProspectIsEnabled();

        StepLogger.stepId(8);
        StepLogger.step('Click on Continue With New Prospect button.');
        await HomePageHelper.clickContinueWithNewProspectButton();
        StepLogger.verification('The New Prospect screen is displayed successfully.');
        await NewProspectPageHelper.verifyNewProspectCommercialPageIsDisplayed(false);

        StepLogger.stepId(9);
        StepLogger.step('Click on Save button.');
        await NewProspectPageHelper.clickSaveButton();
        StepLogger.verification('The mandatory message is displayed under the Work Phone input field.');
        await NewProspectPageHelper.verifyWorkPhoneValidationMsgDisplayed();
    });

    // Jira References - COTRAC-95
    it('Verify if Company is a mandatory field - [22984038]', async () => {
        // Auto generated by aurea-automation - util on Mon, 01 Apr 2019 13:50:29 GMT

        StepLogger.caseId = 22984038;
        StepLogger.stepId(1);
        StepLogger.step('Click on New menu button.'); await HomePageHelper.clickNewLink();
        StepLogger.verification('The New menu list is displayed successfully.');
        await HomePageHelper.verifyOptionsUnderNew();

        StepLogger.stepId(2);
        StepLogger.step('Click on Commercial Prospect menu button.');
        await HomePageHelper.clickCommercialProspectUnderNew();
        StepLogger.verification('The "Check Existing Contact" modal screen is displayed successfully.');
        await HomePageHelper.verifyCheckExistingContactDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Fill the Company input field.');
        await HomePageHelper.enterCompanyOnCheckExistingContactModal(uniqueName);
        StepLogger.verification('The Company input field is filled successfully.');
        await HomePageHelper.verifyCompanyIsEnteredOnCheckExistingContactModal(uniqueName);

        StepLogger.stepId(4);
        StepLogger.step('Fill the First input field with a nonexistent company name.');
        await HomePageHelper.enterFirstNameOnCheckExistingContactModal(uniqueName);
        StepLogger.verification('The First Name input field is filled successfully.');
        await HomePageHelper.verifyFirstNameIsEnteredOnCheckExistingContactModal(uniqueName);

        StepLogger.stepId(5);
        StepLogger.step('Fill the Last input field.');
        await HomePageHelper.enterLastNameOnCheckExistingContactModal(uniqueName);
        StepLogger.verification('The Last Name input field is filled successfully.');
        await HomePageHelper.verifyLastNameIsEnteredOnCheckExistingContactModal(uniqueName);

        StepLogger.stepId(6);
        StepLogger.step('Select Commercial option in the Return dropdown list.');
        await HomePageHelper.selectReturnOptionOnCheckExistingContactModal(commercial);
        StepLogger.verification('The Commercial option is displayed in the dropdown field.');
        await HomePageHelper.verifyReturnOptionIsSelectedOnCheckExistingContactModal(commercial);

        StepLogger.stepId(7);
        StepLogger.step('Click on Search Contacts button.');
        await HomePageHelper.clickSearchContactsOnCheckExistingContactModal();
        StepLogger.verification('The Continue With New Prospect button is enabled.');
        await HomePageHelper.verifyContinueWithNewProspectIsEnabled();

        StepLogger.stepId(8);
        StepLogger.step('Click on Continue With New Prospect button.');
        await HomePageHelper.clickContinueWithNewProspectButton();
        StepLogger.verification('The New Prospect screen is displayed successfully.');
        await NewProspectPageHelper.verifyNewProspectCommercialPageIsDisplayed(false);

        StepLogger.stepId(9);
        StepLogger.step('Clear the Company input click on Save button.');
        await NewProspectPageHelper.typeInCompanyTb();
        await NewProspectPageHelper.clickSaveButton();
        StepLogger.verification('The mandatory message is displayed under the Company input field.');
        await NewProspectPageHelper.verifyCompanyNameValidationMsgDisplayed();
    });

    // Jira References - COTRAC-95
    it('Verify if user shall be able to see the New Prospect screen - [22984034]', async () => {
        // Auto generated by aurea-automation - util on Mon, 01 Apr 2019 14:01:27 GMT

        StepLogger.caseId = 22984034;
        StepLogger.stepId(1);
        StepLogger.step('Click on New menu button.');
        await HomePageHelper.clickNewLink();
        StepLogger.verification('The New menu list is displayed successfully.');
        await HomePageHelper.verifyOptionsUnderNew();

        StepLogger.stepId(2);
        StepLogger.step('Click on Commercial Prospect menu button.');
        await HomePageHelper.clickCommercialProspectUnderNew();
        StepLogger.verification('The "Check Existing Contact" modal screen is displayed successfully.');
        await HomePageHelper.verifyCheckExistingContactDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Fill the Company input field.');
        await HomePageHelper.enterCompanyOnCheckExistingContactModal(uniqueName);
        StepLogger.verification('The Company input field is filled successfully.');
        await HomePageHelper.verifyCompanyIsEnteredOnCheckExistingContactModal(uniqueName);

        StepLogger.stepId(4);
        StepLogger.step('Fill the First input field with a nonexistent company name.');
        await HomePageHelper.enterFirstNameOnCheckExistingContactModal(uniqueName);
        StepLogger.verification('The First Name input field is filled successfully.');
        await HomePageHelper.verifyFirstNameIsEnteredOnCheckExistingContactModal(uniqueName);

        StepLogger.stepId(5);
        StepLogger.step('Fill the Last input field.');
        await HomePageHelper.enterLastNameOnCheckExistingContactModal(uniqueName);
        StepLogger.verification('The Last Name input field is filled successfully.');
        await HomePageHelper.verifyLastNameIsEnteredOnCheckExistingContactModal(uniqueName);

        StepLogger.stepId(6);
        StepLogger.step('Select Commercial option in the Return dropdown list.');
        await HomePageHelper.selectReturnOptionOnCheckExistingContactModal(commercial);
        StepLogger.verification('The Commercial option is displayed in the dropdown field.');
        await HomePageHelper.verifyReturnOptionIsSelectedOnCheckExistingContactModal(commercial);

        StepLogger.stepId(7);
        StepLogger.step('Click on Search Contacts button.');
        await HomePageHelper.clickSearchContactsOnCheckExistingContactModal();
        StepLogger.verification('The Continue With New Prospect button is enabled.');
        await HomePageHelper.verifyContinueWithNewProspectIsEnabled();

        StepLogger.stepId(8);
        StepLogger.step('Click on Continue With New Prospect button.');
        await HomePageHelper.clickContinueWithNewProspectButton();
        StepLogger.verification('The New Prospect screen is displayed successfully.');
        await NewProspectPageHelper.verifyNewProspectCommercialPageIsDisplayed(false);
    });

    // Jira References - COTRAC-95
    it('Verify if user shall be able to see the Address section - [22984042]', async () => {
        // Auto generated by aurea-automation - util on Mon, 01 Apr 2019 18:29:01 GMT

        StepLogger.caseId = 22984042;
        StepLogger.stepId(1);
        StepLogger.step('Click on New menu button.');
        await HomePageHelper.clickNewLink();
        StepLogger.verification('The New menu list is displayed successfully.');
        await HomePageHelper.verifyOptionsUnderNew();

        StepLogger.stepId(2);
        StepLogger.step('Click on Commercial Prospect menu button.');
        await HomePageHelper.clickCommercialProspectUnderNew();
        StepLogger.verification('The "Check Existing Contact" modal screen is displayed successfully.');
        await HomePageHelper.verifyCheckExistingContactDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Fill the Company input field.');
        await HomePageHelper.enterCompanyOnCheckExistingContactModal(uniqueName);
        StepLogger.verification('The Company input field is filled successfully.');
        await HomePageHelper.verifyCompanyIsEnteredOnCheckExistingContactModal(uniqueName);

        StepLogger.stepId(4);
        StepLogger.step('Fill the First input field with a nonexistent company name.');
        await HomePageHelper.enterFirstNameOnCheckExistingContactModal(uniqueName);
        StepLogger.verification('The First Name input field is filled successfully.');
        await HomePageHelper.verifyFirstNameIsEnteredOnCheckExistingContactModal(uniqueName);

        StepLogger.stepId(5);
        StepLogger.step('Fill the Last input field.');
        await HomePageHelper.enterLastNameOnCheckExistingContactModal(uniqueName);
        StepLogger.verification('The Last Name input field is filled successfully.');
        await HomePageHelper.verifyLastNameIsEnteredOnCheckExistingContactModal(uniqueName);

        StepLogger.stepId(6);
        StepLogger.step('Select Commercial option in the Return dropdown list.');
        await HomePageHelper.selectReturnOptionOnCheckExistingContactModal(commercial);
        StepLogger.verification('The Commercial option is displayed in the dropdown field.');
        await HomePageHelper.verifyReturnOptionIsSelectedOnCheckExistingContactModal(commercial);

        StepLogger.stepId(7);
        StepLogger.step('Click on Search Contacts button.');
        await HomePageHelper.clickSearchContactsOnCheckExistingContactModal();
        StepLogger.verification('The Continue With New Prospect button is enabled.');
        await HomePageHelper.verifyContinueWithNewProspectIsEnabled();

        StepLogger.stepId(8);
        StepLogger.step('Click on Continue With New Prospect button.');
        await HomePageHelper.clickContinueWithNewProspectButton();
        StepLogger.verification('The New Prospect screen is displayed successfully.');
        await NewProspectPageHelper.verifyNewProspectCommercialPageIsDisplayed(false);

        StepLogger.stepId(9);
        StepLogger.step('Check the Address section.');
        StepLogger.verification(`The Name Address should display the fields:
            -Address
            -Address (Cont)
            -City
            -Reg O
            -State
            -Country
            -Zip`);
        await NewProspectPageHelper.verifyAddressSection();
    });
});
