import { StepLogger } from '../../../../core/logger/step-logger';
import { PageHelper } from '../../../components/html/page-helper';
import { HomePage } from '../../../page-objects/pages/home-page/home-page.po';
import { HomePage1Helper } from '../../../page-objects/pages/home-page/home-page1.helper';
import { LoginPageHelper } from '../../../page-objects/pages/login-page/login-page.helper';
import { ReportWriterReportsPageHelper } from '../../../page-objects/pages/report-writer-reports-page/report-writer-reports-page.helper';
import { SuiteNames } from '../../helpers/suite-names';

describe(SuiteNames.regressionSuite, () => {
    let loginPageHelper: LoginPageHelper;

    beforeAll(async () => {
        loginPageHelper = LoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
    });

    beforeEach(async () => {
        await PageHelper.restartBrowser();
        await loginPageHelper.goTo();
    });

    // Jira References - COTRAC-2202
    it('Login to application and navigate to Report Writer link. - [23008174]', async () => {
        // Auto generated by aurea-automation - util on Mon, 08 Apr 2019 08:34:55 GMT

        StepLogger.caseId = 23008174;
        StepLogger.stepId(1);
        StepLogger.step('Verify User should be logged in to application');
        await LoginPageHelper.loginAsAdmin();
        StepLogger.verification('User should be logged in to application and user should be on application Home page');
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Verify Reports menu is appearing on the left side of the page.');
        StepLogger.verification('Reports menu should be appearing on the left side of the page.');
        await HomePage1Helper.verifyReportsLink();

        StepLogger.stepId(3);
        StepLogger.step('Click on the Reports menu');
        await HomePage1Helper.clickReportsLink();
        StepLogger.verification('Reports menu should expand.');
        await HomePage1Helper.verifyReportExpand();

        StepLogger.stepId(4);
        StepLogger.step('Verify Report Writer is appearing under Report menu.');
        StepLogger.verification('Report Writer should be appearing under Report menu.');
        await HomePage1Helper.verifyReportItemDisplay();
    });

    // Jira References - COTRAC-2202
    it('Verify user is able to access Report Writer Reports page. - [23008176]', async () => {
        // Auto generated by aurea-automation - util on Mon, 08 Apr 2019 07:36:01 GMT

        StepLogger.caseId = 23008176;

        StepLogger.stepId(1);
        StepLogger.step('Click on the Verify User should be logged in to application');
        await LoginPageHelper.loginAsAdmin();
        StepLogger.verification('User should be logged in to application and user should be on application Home page');
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        // Step 2-4 have been covered in step 5
        StepLogger.stepId(2);
        StepLogger.step('Verify Reports menu is appearing on the left side of the page.');
        StepLogger.verification('Reports menu should be appearing on the left side of the page.');

        StepLogger.stepId(3);
        StepLogger.step('Click on the Reports menu');
        StepLogger.verification('Reports menu should expand.');

        StepLogger.stepId(4);
        StepLogger.step('Verify Report Writer is appearing under Report menu.');
        StepLogger.verification('Report Writer should be appearing under Report menu.');

        StepLogger.stepId(5);
        StepLogger.step('Click on the Report Writer link.');
        await HomePage1Helper.navigateToReportWriterPage();
        StepLogger.verification('"Report Writer Reports" page should open.');
        await ReportWriterReportsPageHelper.verifyReportWriterReportsPageIsDisplayed();
    });

    // Jira References - COTRAC-2202
    it('Verify columns appearing on Report Writer Reports page. - [23008177]', async () => {
        // Auto generated by aurea-automation - util on Mon, 08 Apr 2019 07:46:39 GMT

        StepLogger.caseId = 23008177;
        StepLogger.stepId(1);
        StepLogger.step('Verify User should be logged in to application');
        await LoginPageHelper.loginAsAdmin();
        StepLogger.verification('User should be logged in to application and user should be on application Home page');
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        // Step 2-4 have been covered in step 5
        StepLogger.stepId(2);
        StepLogger.step('Verify Reports menu is appearing on the left side of the page.');
        StepLogger.verification('Reports menu should be appearing on the left side of the page.');

        StepLogger.stepId(3);
        StepLogger.step('Click on the Reports menu');
        StepLogger.verification('Reports menu should expand.');

        StepLogger.stepId(4);
        StepLogger.step('Verify Report Writer is appearing under Report menu.');
        StepLogger.verification('Report Writer should be appearing under Report menu.');

        StepLogger.stepId(5);
        StepLogger.step('Click on the Report Writer link.');
        await HomePage1Helper.navigateToReportWriterPage();
        StepLogger.verification('"Report Writer Reports" page should open.');
        await ReportWriterReportsPageHelper.verifyReportWriterReportsPageIsDisplayed();

        StepLogger.stepId(6);
        StepLogger.step('Verify columns appearing on the page');
        StepLogger.verification(`Following columns should be appearing on the page:
        - Action
        - Name
        - Type
        - Last Change
        - Description`);
        await ReportWriterReportsPageHelper.verifyColumnReporterPage();
    });

    // Jira References - COTRAC-2202
    it('Verify options appearing under Resources section. - [23008186]', async () => {
        // Auto generated by aurea-automation - util on Mon, 08 Apr 2019 08:42:28 GMT

        StepLogger.caseId = 23008186;
        StepLogger.stepId(1);
        StepLogger.step('Click on the Verify User should be logged in to application');
        await LoginPageHelper.loginAsAdmin();
        StepLogger.verification('User should be logged in to application and user should be on application Home page');
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        // Step 2-4 have been covered in step 5
        StepLogger.stepId(2);
        StepLogger.step('Verify Reports menu is appearing on the left side of the page.');
        StepLogger.verification('Reports menu should be appearing on the left side of the page.');

        StepLogger.stepId(3);
        StepLogger.step('Click on the Reports menu');
        StepLogger.verification('Reports menu should expand.');

        StepLogger.stepId(4);
        StepLogger.step('Verify Report Writer is appearing under Report menu.');
        StepLogger.verification('Report Writer should be appearing under Report menu.');

        StepLogger.stepId(5);
        StepLogger.step('Click on the Report Writer link.');
        await HomePage1Helper.navigateToReportWriterPage();
        StepLogger.verification('"Report Writer Reports" page should open.');
        await ReportWriterReportsPageHelper.verifyReportWriterReportsPageIsDisplayed();

        StepLogger.stepId(6);
        StepLogger.step('Verify Resources section is appearing on the left side of the page.');
        StepLogger.verification('Resources section should be appearing on the left side of the page.');
        await ReportWriterReportsPageHelper.verifyResource();

        StepLogger.stepId(7);
        StepLogger.step('Verify links appearing under Resources section');
        StepLogger.verification(`Following  links should be appearing under Resources section:
        1- Images
        2- Yearly Quarters`);
        await ReportWriterReportsPageHelper.verifyLinkUnderResource();
    });

    // Jira References - COTRAC-2202
    it('Verify options appearing under Reports section. - [23008188]', async () => {
        // Auto generated by aurea-automation - util on Mon, 08 Apr 2019 12:10:39 GMT

        StepLogger.caseId = 23008188;
        StepLogger.stepId(1);
        StepLogger.step('Click on the Verify User should be logged in to application');
        await LoginPageHelper.loginAsAdmin();
        StepLogger.verification('User should be logged in to application and user should be on application Home page');
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        // Step 2-4 have been covered in step 5
        StepLogger.stepId(2);
        StepLogger.step('Verify Reports menu is appearing on the left side of the page.');
        StepLogger.verification('Reports menu should be appearing on the left side of the page.');

        StepLogger.stepId(3);
        StepLogger.step('Click on the Reports menu');
        StepLogger.verification('Reports menu should expand.');

        StepLogger.stepId(4);
        StepLogger.step('Verify Report Writer is appearing under Report menu.');
        StepLogger.verification('Report Writer should be appearing under Report menu.');

        StepLogger.stepId(5);
        StepLogger.step('Click on the Report Writer link.');
        await HomePage1Helper.navigateToReportWriterPage();
        StepLogger.verification('"Report Writer Reports" page should open.');
        await ReportWriterReportsPageHelper.verifyReportWriterReportsPageIsDisplayed();

        StepLogger.stepId(6);
        StepLogger.step('Verify Reports section is appearing on the left side of the page.');
        StepLogger.verification('Reports section should be appearing on the left side of the page.');
        await ReportWriterReportsPageHelper.verifyReport();

        StepLogger.stepId(7);
        StepLogger.step('Verify links appearing under Reports section');
        StepLogger.verification(`Following  links should be appearing under Reports section:
        - Create /Edit`);
        await ReportWriterReportsPageHelper.verifyLinkUnderReport();
    });

    // Jira References - COTRAC-2202
    it('Verify user clicks on New Report button. - [23008192]', async () => {
        // Auto generated by aurea-automation - util on Tue, 09 Apr 2019 04:00:44 GMT

        StepLogger.caseId = 23008192;
        StepLogger.stepId(1);
        StepLogger.step('Click on the Verify User should be logged in to application');
        await LoginPageHelper.loginAsAdmin();
        StepLogger.verification('User should be logged in to application and user should be on application Home page');
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        // Step 2-4 have been covered in step 5
        StepLogger.stepId(2);
        StepLogger.step('Verify Reports menu is appearing on the left side of the page.');
        StepLogger.verification('Reports menu should be appearing on the left side of the page.');

        StepLogger.stepId(3);
        StepLogger.step('Click on the Reports menu');
        StepLogger.verification('Reports menu should expand.');

        StepLogger.stepId(4);
        StepLogger.step('Verify Report Writer is appearing under Report menu.');
        StepLogger.verification('Report Writer should be appearing under Report menu.');

        StepLogger.stepId(5);
        StepLogger.step('Click on the Report Writer link.');
        await HomePage1Helper.navigateToReportWriterPage();
        StepLogger.verification('"Report Writer Reports" page should open.');
        await ReportWriterReportsPageHelper.verifyReportWriterReportsPageIsDisplayed();

        StepLogger.stepId(6);
        StepLogger.step('Click on the "New Report" button.');
        await ReportWriterReportsPageHelper.clickNewReport();
        StepLogger.verification('CoreTrac Report Writer page should open with new report form.');
        await ReportWriterReportsPageHelper.verifyReportName();
    });

    // Jira References - COTRAC-2202
    it('Verify buttons appearing under Activity column. - [23008179]', async () => {
        // Auto generated by aurea-automation - util on Tue, 09 Apr 2019 04:20:38 GMT

        StepLogger.caseId = 23008179;
        StepLogger.stepId(1);
        StepLogger.step('Click on the Verify User should be logged in to application');
        await LoginPageHelper.loginAsAdmin();
        StepLogger.verification('User should be logged in to application and user should be on application Home page');
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        // Step 2-4 have been covered in step 5
        StepLogger.stepId(2);
        StepLogger.step('Verify Reports menu is appearing on the left side of the page.');
        StepLogger.verification('Reports menu should be appearing on the left side of the page.');

        StepLogger.stepId(3);
        StepLogger.step('Click on the Reports menu');
        StepLogger.verification('Reports menu should expand.');

        StepLogger.stepId(4);
        StepLogger.step('Verify Report Writer is appearing under Report menu.');
        StepLogger.verification('Report Writer should be appearing under Report menu.');

        StepLogger.stepId(5);
        StepLogger.step('Click on the Report Writer link.');
        await HomePage1Helper.navigateToReportWriterPage();
        StepLogger.verification('"Report Writer Reports" page should open.');
        await ReportWriterReportsPageHelper.verifyReportWriterReportsPageIsDisplayed();

        StepLogger.stepId(6);
        StepLogger.step('Verify buttons appearing under Activity column.');
        StepLogger.verification(`Following buttons should be appearing under Activity column:
        - edit this report
        - Copy This report
        - Delete This report
        - Lock this report
        - Run this report.`);
        await ReportWriterReportsPageHelper.verifyButtonsUnderActions();
    });

    // Jira References - COTRAC-2202
    it('Verify buttons appearing on the page. - [23008178]', async () => {
        // Auto generated by aurea-automation - util on Tue, 09 Apr 2019 04:42:12 GMT

        StepLogger.caseId = 23008178;
        StepLogger.stepId(1);
        StepLogger.step('Click on the Verify User should be logged in to application');
        await LoginPageHelper.loginAsAdmin();
        StepLogger.verification('User should be logged in to application and user should be on application Home page');
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        // Step 2-4 have been covered in step 5
        StepLogger.stepId(2);
        StepLogger.step('Verify Reports menu is appearing on the left side of the page.');
        StepLogger.verification('Reports menu should be appearing on the left side of the page.');

        StepLogger.stepId(3);
        StepLogger.step('Click on the Reports menu');
        StepLogger.verification('Reports menu should expand.');

        StepLogger.stepId(4);
        StepLogger.step('Verify Report Writer is appearing under Report menu.');
        StepLogger.verification('Report Writer should be appearing under Report menu.');

        StepLogger.stepId(5);
        StepLogger.step('Click on the Report Writer link.');
        await HomePage1Helper.navigateToReportWriterPage();
        StepLogger.verification('"Report Writer Reports" page should open.');
        await ReportWriterReportsPageHelper.verifyReportWriterReportsPageIsDisplayed();

        StepLogger.stepId(6);
        StepLogger.step('Verify buttons appearing on the page.');
        StepLogger.verification(`Following buttons should be appearing on the page:
        - New Report
        - New Union Report`);
        await ReportWriterReportsPageHelper.verifyReportsLinks();
    });

    // Jira References - COTRAC-2202
    it('Verify options appearing under Schema section. - [23008183]', async () => {
        // Auto generated by aurea-automation - util on Tue, 09 Apr 2019 05:43:06 GMT

        StepLogger.caseId = 23008183;
        StepLogger.stepId(1);
        StepLogger.step('Click on the Verify User should be logged in to application');
        await LoginPageHelper.loginAsAdmin();
        StepLogger.verification('User should be logged in to application and user should be on application Home page');
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        // Step 2-4 have been covered in step 5
        StepLogger.stepId(2);
        StepLogger.step('Verify Reports menu is appearing on the left side of the page.');
        StepLogger.verification('Reports menu should be appearing on the left side of the page.');

        StepLogger.stepId(3);
        StepLogger.step('Click on the Reports menu');
        StepLogger.verification('Reports menu should expand.');

        StepLogger.stepId(4);
        StepLogger.step('Verify Report Writer is appearing under Report menu.');
        StepLogger.verification('Report Writer should be appearing under Report menu.');

        StepLogger.stepId(5);
        StepLogger.step('Click on the Report Writer link.');
        await HomePage1Helper.navigateToReportWriterPage();
        StepLogger.verification('"Report Writer Reports" page should open.');
        await ReportWriterReportsPageHelper.verifyReportWriterReportsPageIsDisplayed();

        StepLogger.stepId(6);
        StepLogger.step('Verify Schema section is appearing on the left side of the page.');
        StepLogger.verification('Schema section should be appearing on the left side of the page.');
        await ReportWriterReportsPageHelper.verifySchema();

        StepLogger.stepId(7);
        StepLogger.step('Verify links appearing under Schema section');
        StepLogger.verification(`Following  links should be appearing under Schema section:
        1- Connections
        2- Create
        3- Edit`);
        await ReportWriterReportsPageHelper.verifyLinkUnderSchema();
    });

    // Jira References - COTRAC-2202
    it('Verify user is able to Expand any of the section appearing in the table. - [23008197]', async () => {
        // Auto generated by aurea-automation - extension on Tue, 16 Apr 2019 09: 58: 26 GMT

        StepLogger.caseId = 23008197;
        StepLogger.stepId(1);
        StepLogger.step('Click on the Verify User should be logged in to application');
        await LoginPageHelper.loginAsAdmin();
        StepLogger.verification('User should be logged in to application and user should be on application Home page');
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        // Step 2-4 have been covered in step 5
        StepLogger.stepId(2);
        StepLogger.step('Verify Reports menu is appearing on the left side of the page.');
        StepLogger.verification('Reports menu should be appearing on the left side of the page.');

        StepLogger.stepId(3);
        StepLogger.step('Click on the Reports menu');
        StepLogger.verification('Reports menu should expand.');

        StepLogger.stepId(4);
        StepLogger.step('Verify Report Writer is appearing under Report menu.');
        StepLogger.verification('Report Writer should be appearing under Report menu.');

        StepLogger.stepId(5);
        StepLogger.step('Click on the Report Writer link.');
        await HomePage1Helper.navigateToReportWriterPage();
        StepLogger.verification('"Report Writer Reports" page should open.');
        await ReportWriterReportsPageHelper.verifyReportWriterReportsPageIsDisplayed();

        StepLogger.stepId(6);
        StepLogger.step('Click on the arrow button appearing under  section appearing under table.');
        await ReportWriterReportsPageHelper.clickArrowCollapse();
        StepLogger.verification('Selected Section should collapse.');
        await ReportWriterReportsPageHelper.verifyArrowExpand();

        StepLogger.stepId(7);
        StepLogger.step('Click on the arrow button again in the collapsed section.');
        await ReportWriterReportsPageHelper.clickArrowExpand();
        StepLogger.verification('Section should expand again.');
        await ReportWriterReportsPageHelper.verifyArrowCollapse();
    });

    // Jira References - COTRAC-2202
    it('Verify user is able to Collapse any of the section appearing in the table. - [23008196]', async () => {
        // Auto generated by aurea-automation - extension on Tue, 16 Apr 2019 10: 25: 09 GMT

        StepLogger.caseId = 23008196;
        StepLogger.stepId(1);
        StepLogger.step('Click on the Verify User should be logged in to application');
        await LoginPageHelper.loginAsAdmin();
        StepLogger.verification('User should be logged in to application and user should be on application Home page');
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        // Step 2-4 have been covered in step 5
        StepLogger.stepId(2);
        StepLogger.step('Verify Reports menu is appearing on the left side of the page.');
        StepLogger.verification('Reports menu should be appearing on the left side of the page.');

        StepLogger.stepId(3);
        StepLogger.step('Click on the Reports menu');
        StepLogger.verification('Reports menu should expand.');

        StepLogger.stepId(4);
        StepLogger.step('Verify Report Writer is appearing under Report menu.');
        StepLogger.verification('Report Writer should be appearing under Report menu.');

        StepLogger.stepId(5);
        StepLogger.step('Click on the Report Writer link.');
        await HomePage1Helper.navigateToReportWriterPage();
        StepLogger.verification('"Report Writer Reports" page should open.');
        await ReportWriterReportsPageHelper.verifyReportWriterReportsPageIsDisplayed();

        StepLogger.stepId(6);
        StepLogger.step('Click on the arrow button appearing under  section appearing under table.');
        await ReportWriterReportsPageHelper.clickArrowCollapse();
        await ReportWriterReportsPageHelper.clickArrowExpand();
        StepLogger.verification('Selected Section should collapse.');
        await ReportWriterReportsPageHelper.verifyArrowCollapse();
    });

    // Jira References - COTRAC-2202
    it('Verify user clicks on New Union Report button - [23008194]', async () => {
        // Auto generated by aurea-automation - extension on Tue, 16 Apr 2019 10: 28: 56 GMT

        StepLogger.caseId = 23008194;
        StepLogger.stepId(1);
        StepLogger.step('Click on the Verify User should be logged in to application');
        await LoginPageHelper.loginAsAdmin();
        StepLogger.verification('User should be logged in to application and user should be on application Home page');
        await HomePage.hamburgerIcon.verifyDisplayedStatus();

        // Step 2-4 have been covered in step 5
        StepLogger.stepId(2);
        StepLogger.step('Verify Reports menu is appearing on the left side of the page.');
        StepLogger.verification('Reports menu should be appearing on the left side of the page.');

        StepLogger.stepId(3);
        StepLogger.step('Click on the Reports menu');
        StepLogger.verification('Reports menu should expand.');

        StepLogger.stepId(4);
        StepLogger.step('Verify Report Writer is appearing under Report menu.');
        StepLogger.verification('Report Writer should be appearing under Report menu.');

        StepLogger.stepId(5);
        StepLogger.step('Click on the Report Writer link.');
        await HomePage1Helper.navigateToReportWriterPage();
        StepLogger.verification('"Report Writer Reports" page should open.');
        await ReportWriterReportsPageHelper.verifyReportWriterReportsPageIsDisplayed();

        StepLogger.stepId(6);
        StepLogger.step('Verify user clicks on the New Union Report button');
        await ReportWriterReportsPageHelper.clickUnionReport();
        StepLogger.verification('CoreTrac Report Writer page should open with new form fields.');
        await ReportWriterReportsPageHelper.verifyGeneralTabDisplayed();
    });
});
