import { StepLogger } from '../../../../../core/logger/step-logger';
import { PageHelper } from '../../../../components/html/page-helper';
import { CustomItemTypesHelper } from '../../../../page-objects/pages/administration/configuration/custom-item-types/custom-item-types.helper';
import { CustomItemHelper } from '../../../../page-objects/pages/administration/configuration/custom-item/custom-item.helper';
import { DispositionsHelper } from '../../../../page-objects/pages/administration/configuration/dispositions/dispositions.helper';
import { EventTypesHelper } from '../../../../page-objects/pages/administration/configuration/event-types/event-types.helper';
import { LostReasonsHelper } from '../../../../page-objects/pages/administration/configuration/lost-reasons/lost-reasons.helper';
import { HomePageOneHelper } from '../../../../page-objects/pages/home-page/home-page-one.helper';
import { HomePageHelper } from '../../../../page-objects/pages/home-page/home-page.helper';
import { HomePage1Helper } from '../../../../page-objects/pages/home-page/home-page1.helper';
import { LoginPageHelper } from '../../../../page-objects/pages/login-page/login-page.helper';
import { ReportWriterReportsPageHelper } from '../../../../page-objects/pages/report-writer-reports-page/report-writer-reports-page.helper';
import { BrowseHelper } from '../../../../page-objects/pages/reports/browse/browse.helper';
import { CustomReportsHelper } from '../../../../page-objects/pages/reports/custom-reports/custom-reports.helper';
import { PendingReportsHelper } from '../../../../page-objects/pages/reports/pending-reports/pending-reports.helper';
import { DocumentsHelper } from '../../../../page-objects/pages/resources/documents/documents.helper';
import { LinksHelper } from '../../../../page-objects/pages/resources/links/links.helper';
import { SuiteNames } from '../../../helpers/suite-names';

describe(SuiteNames.regressionSuite, () => {
    let loginPageHelper: LoginPageHelper;

    beforeAll(async () => {
        loginPageHelper = LoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
    });

    beforeEach(async () => {
        await PageHelper.restartBrowser();
        await loginPageHelper.goTo();
        await LoginPageHelper.loginAsAdmin();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see Lost Reasons screen under the sub-menu Configuration - [22412589]', async () => {
        // Auto generated by aurea-automation - util on Fri, 24 May 2019 10:22:09 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412589;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Click on Lost Reasons button under the sub-menu Configuration');
        await HomePageHelper.clickAdministrationLink();
        await HomePageHelper.clickConfigurationUnderAdministration();
        await HomePageOneHelper.clickLostReasonsButtonUnderConfigurationSubmenuUnderAdministrationMenu();
        StepLogger.verification('Should display the Lost Reasons screen properly.');
        await LostReasonsHelper.verifyLostReasonsPageDisplayed();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see Event Types screen under the sub-menu Configuration - [22412587]', async () => {
        // Auto generated by aurea-automation - util on Fri, 24 May 2019 10:22:14 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412587;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Click on Event Types button under the sub-menu Configuration');
        await HomePageHelper.clickAdministrationLink();
        await HomePageHelper.clickConfigurationUnderAdministration();
        await HomePageOneHelper.clickEventTypesButtonUnderConfigurationSubmenuUnderAdministrationMenu();
        StepLogger.verification('Should display the Event Types screen properly.');
        await EventTypesHelper.verifyEventTypesPageDisplayed();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see Disposition screen under the sub-menu Configuration - [22412586]', async () => {
        // Auto generated by aurea-automation - util on Fri, 24 May 2019 10:22:16 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412586;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Click on Disposition button under the sub-menu Configuration');
        await HomePageHelper.clickAdministrationLink();
        await HomePageHelper.clickConfigurationUnderAdministration();
        await HomePageOneHelper.clickDispositionsButtonUnderConfigurationSubmenuUnderAdministrationMenu();
        StepLogger.verification('Should display the Disposition screen properly.');
        await DispositionsHelper.verifyDispositionsPageDisplayed();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see Custom Item Types screen under the sub-menu Configuration - [22412585]', async () => {
        // Auto generated by aurea-automation - util on Fri, 24 May 2019 10:21:22 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412585;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Click on Custom Item Types button under the sub-menu Configuration');
        await HomePageHelper.clickAdministrationLink();
        await HomePage1Helper.navigateConfigurationCustomItemTypes();
        StepLogger.verification('Should display the Custom Types Item screen properly.');
        await CustomItemTypesHelper.verifyCustomItemTypesPageDisplayed();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see Custom Item screen under the sub-menu Configuration - [22412568]', async () => {
        // Auto generated by aurea-automation - util on Fri, 24 May 2019 10:21:41 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412568;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Click on Custom Item button under the sub-menu Configuration');
        await HomePageHelper.clickAdministrationLink();
        await HomePage1Helper.navigateConfigurationCustomItems();
        StepLogger.verification('Should display the Custom Item screen properly.');
        await CustomItemHelper.verifyCustomItemPageDisplayed();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see the Configuration sub-menu under the menu Administration - [22412565]', async () => {
        // Auto generated by aurea-automation - util on Fri, 24 May 2019 10:22:37 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412565;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Check the Configuration sub-menu under the Administration menu.');
        await HomePageHelper.clickAdministrationLink();
        StepLogger.verification('Should display the Configuration sub-menu properly.');
        await HomePageOneHelper.verifyConfigurationDisplayedUnderAdministration();
        await HomePageHelper.clickConfigurationUnderAdministration();
        await HomePageHelper.verifyOptionsUnderConfiguration();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see the Administration menu - [22412560]', async () => {
        // Auto generated by aurea-automation - util on Fri, 24 May 2019 10:21:45 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412560;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Check the Administration menu under the main menu.');
        StepLogger.verification('Should display the Administration menu properly.');
        await HomePageOneHelper.verifyAdministrationDisplayed();
        await HomePageHelper.clickAdministrationLink();
        await HomePageHelper.verifyOptionsUnderAdministration();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see Links screen under the menu Resources - [22412545]', async () => {
        // Auto generated by aurea-automation - util on Fri, 24 May 2019 10:22:29 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412545;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Click on Links button under the Resources menu.');
        await HomePageOneHelper.clickResources();
        await HomePageOneHelper.clickLinksButtonUnderResourcesMenu();
        StepLogger.verification('Should display the Links screen properly.');
        await LinksHelper.verifyLinksPageDisplayed();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see Documents screen under the menu Resources - [22412544]', async () => {
        // Auto generated by aurea-automation - util on Fri, 24 May 2019 10:21:21 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412544;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Click on Documents button under the Resources menu.');
        await HomePageOneHelper.clickResources();
        await HomePageOneHelper.clickDocumentsButtonUnderResourcesMenu();
        StepLogger.verification('Should display the Documents screen properly.');
        await DocumentsHelper.verifyDocumentsPageDisplayed();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see the Resources menu - [22412543]', async () => {
        // Auto generated by aurea-automation - util on Fri, 24 May 2019 10:21:28 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412543;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Check the Resources menu is displaying properly under the main menu.');
        StepLogger.verification('Should display the Resources menu under the main menu properly.');
        await HomePageOneHelper.verifyResourcesDisplayed();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see Pending Reports screen under the menu Reports - [22412542]', async () => {
        // Auto generated by aurea-automation - util on Fri, 24 May 2019 10:22:41 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412542;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Click on Pending Reports button under the Reports menu');
        await HomePage1Helper.clickReportsLink();
        await HomePageOneHelper.clickPendingReportsButtonUnderReportsMenu();
        StepLogger.verification('Should display the Pending Reports screen properly.');
        await PendingReportsHelper.verifyPendingReportsPageDisplayed();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see Report Writer screen under the menu Reports - [22412540]', async () => {
        // Auto generated by aurea-automation - util on Fri, 24 May 2019 10:21:11 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412540;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Click on Report Writer button under the Reports menu');
        await HomePage1Helper.navigateToReportWriterPage();
        StepLogger.verification('Should display the Report Writer screen properly.');
        await ReportWriterReportsPageHelper.verifyReportWriterReportsPageIsDisplayed();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see Custom Reports screen under the menu Reports - [22412539]', async () => {
        // Auto generated by aurea-automation - util on Fri, 24 May 2019 10:22:33 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412539;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Click on Custom Reports button under the Reports menu');
        await HomePage1Helper.clickReportsLink();
        await HomePageOneHelper.clickCustomReportsButtonUnderReportsMenu();
        StepLogger.verification('Should display the Custom Reports screen properly.');
        await CustomReportsHelper.verifyCustomReportsPageDisplayed();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see Browse screen under the menu Reports - [22412538]', async () => {
        // Auto generated by aurea-automation - util on Fri, 24 May 2019 10:22:02 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412538;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Click on Browse button under the Reports menu');
        await HomePage1Helper.clickReportsLink();
        await HomePage1Helper.clickOnBrowseButton();
        StepLogger.verification('Should display the Browse screen properly.');
        await BrowseHelper.verifyBrowsePageDisplayed();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see the Reports menu - [22412537]', async () => {
        // Auto generated by aurea-automation - util on Fri, 24 May 2019 10:22:29 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412537;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Check the Reports menu under the main menu.');
        await HomePage1Helper.clickReportsLink();
        StepLogger.verification('Should display the Reports menu properly.');
        await HomePage1Helper.verifyReportsLink();
        await HomePage1Helper.verifyReportItemDisplay();
    });
});
