import { StepLogger } from '../../../../../core/logger/step-logger';
import { PageHelper } from '../../../../components/html/page-helper';
import { HomePageOneHelper } from '../../../../page-objects/pages/home-page/home-page-one.helper';
import { HomePageHelper } from '../../../../page-objects/pages/home-page/home-page.helper';
import { HomePage1Helper } from '../../../../page-objects/pages/home-page/home-page1.helper';
import { LoginPageHelper } from '../../../../page-objects/pages/login-page/login-page.helper';
import { NewAccountPageHelper } from '../../../../page-objects/pages/new-account-page/new-account-page.helper';
import { NewCasePageHelper } from '../../../../page-objects/pages/new-case-page/new-case-page.helper';
import {
    NewOpportunityPageHelper
} from '../../../../page-objects/pages/new-opportunity-page/new-opportunity-page.helper';
import { LostHelper } from '../../../../page-objects/pages/opportunities/lost/lost.helper';
import { PipelinePageHelper } from '../../../../page-objects/pages/pipeline/pipeline.helper';
import { ProductionPageHelper } from '../../../../page-objects/pages/production-page/production-page.helper';
import { SuiteNames } from '../../../helpers/suite-names';

describe(SuiteNames.regressionSuite, () => {
    let loginPageHelper: LoginPageHelper;

    beforeAll(async () => {
        loginPageHelper = LoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
    });

    beforeEach(async () => {
        await PageHelper.restartBrowser();
        await loginPageHelper.goTo();
        await LoginPageHelper.loginAsAdmin();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see Referrals screen under the Opportunities menu - [22412517]', async () => {
        // Auto generated by aurea-automation - util on Mon, 27 May 2019 05:46:24 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412517;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        // navigateToReferralsPage() method has verification inside it
        StepLogger.stepId(4);
        StepLogger.step('Click on Referrals button.');
        StepLogger.verification('Should display the Referrals screen properly.');
        await HomePageHelper.navigateToReferralsPage();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see Lost screen under the Opportunities menu - [22412516]', async () => {
        // Auto generated by aurea-automation - util on Mon, 27 May 2019 05:46:18 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412516;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Click on Lost button.');
        await HomePage1Helper.clickOnOpportunitiesMenu();
        await HomePageOneHelper.clickLostButtonUnderOpportunitiesMenu();
        StepLogger.verification('Should display the Lost screen properly.');
        await LostHelper.verifyLostPageDisplayed();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see Production screen under the Opportunities menu - [22412515]', async () => {
        // Auto generated by aurea-automation - util on Mon, 27 May 2019 05:46:21 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412515;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Click on Production button.');
        await HomePage1Helper.navigateToProductionPage();
        StepLogger.verification('Should display the Production screen properly.');
        await ProductionPageHelper.verifyProductionPageIsDisplayed();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see Pipeline screen under the Opportunities menu - [22412514]', async () => {
        // Auto generated by aurea-automation - util on Mon, 27 May 2019 05:46:27 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412514;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Clicks on Pipeline button.');
        await HomePage1Helper.navigateToPipelinePage();
        StepLogger.verification('Should display the Pipeline screen properly.');
        await PipelinePageHelper.verifyPipelinePageDisplayed();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see the Opportunities menu - [22412513]', async () => {
        // Auto generated by aurea-automation - util on Mon, 27 May 2019 05:46:24 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412513;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Check the Opportunities menu option on left side of the screen.');
        StepLogger.verification('Should display the Opportunities item under the main menu properly.');
        await HomePageOneHelper.verifyOpportunitiesMenuDisplayed();
        await HomePage1Helper.clickOnOpportunitiesMenu();
        await HomePage1Helper.verifyOpportunitiesSubmenuOptions();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see Retail Prospect screen under the New menu - [22412511]', async () => {
        // Auto generated by aurea-automation - util on Mon, 27 May 2019 05:46:28 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412511;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Click on Retail Prospect button under New menu.');
        await HomePageHelper.clickNewLink();
        await HomePageHelper.clickRetailProspectUnderNew();
        StepLogger.verification('Should display the Retail Prospect screen properly.');
        await HomePageHelper.verifyCheckExistingContactDisplayed();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see Commercial Prospect screen under the New menu - [22412509]', async () => {
        // Auto generated by aurea-automation - util on Mon, 27 May 2019 05:46:32 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412509;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Click on Commercial Prospect button under New menu.');
        await HomePageHelper.clickNewLink();
        await HomePageHelper.clickCommercialProspectUnderNew();
        StepLogger.verification('Should display the Commercial Prospect screen properly.');
        await HomePageHelper.verifyCheckExistingContactDisplayed();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see Case screen under the New menu - [22412507]', async () => {
        // Auto generated by aurea-automation - util on Mon, 27 May 2019 05:46:35 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412507;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Click on Case button under the New menu.');
        await HomePageHelper.clickNewLink();
        await HomePageHelper.clickCaseUnderNew();
        StepLogger.verification('Should display the Case screen in a new tab properly.');
        await NewCasePageHelper.verifyNewCasePageDisplayed();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see Account screen under the New menu - [22412505]', async () => {
        // Auto generated by aurea-automation - util on Mon, 27 May 2019 05:46:38 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412505;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Click on Account menu item under the New menu.');
        await HomePageHelper.clickNewLink();
        await HomePageHelper.clickAccountUnderNew();
        StepLogger.verification('Should open the Account screen in a new tab properly.');
        await NewAccountPageHelper.verifyNewAccountPageDisplayed();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see Opportunity screen under the New menu - [22412504]', async () => {
        // Auto generated by aurea-automation - util on Mon, 27 May 2019 05:46:33 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412504;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Click on Opportunity button on menu.');
        await HomePageHelper.clickNewLink();
        await HomePageHelper.clickOpportunityUnderNew();
        StepLogger.verification('Should open the Opportunity screen in a new tab properly.');
        await NewOpportunityPageHelper.verifyNewOpportunityPageIsDisplayed();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see the New menu - [22412502]', async () => {
        // Auto generated by aurea-automation - util on Mon, 27 May 2019 05:46:45 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412502;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Check the New menu item.');
        StepLogger.verification('Should display the New menu item in the menu list properly.');
        await HomePageOneHelper.verifyNewMenuDisplayed();
        await HomePageHelper.clickNewLink();
        await HomePageHelper.verifyOptionsUnderNew();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see the Home screen clicking on Home menu - [22412500]', async () => {
        // Auto generated by aurea-automation - util on Mon, 27 May 2019 05:46:38 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412500;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Click on Home menu.');
        await HomePageHelper.clickHomeLink();
        StepLogger.verification('Should display the Home screen properly.');
        await HomePageOneHelper.verifyHomepageDisplayed();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see the Menu on left side of screen properly - [22412499]', async () => {
        // Auto generated by aurea-automation - util on Mon, 27 May 2019 05:46:39 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412499;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Check the Menu on left side of the screen.');
        StepLogger.verification('Should display the menu expanded by default properly.');
        await HomePageOneHelper.verifyLeftPaneMenuItemsDisplayed();
    });
});
