import { StepLogger } from '../../../../../core/logger/step-logger';
import { PageHelper } from '../../../../components/html/page-helper';
import { DistrictsHelper } from '../../../../page-objects/pages/administration/organization/districts/districts.helper';
import { RegionsHelper } from '../../../../page-objects/pages/administration/organization/regions/regions.helper';
import { DocumentsHelper } from '../../../../page-objects/pages/administration/resources/documents/documents.helper';
import { LinksHelper } from '../../../../page-objects/pages/administration/resources/links/links.helper';
import { RolesHelper } from '../../../../page-objects/pages/administration/security/roles/roles.helper';
import { UsersHelper } from '../../../../page-objects/pages/administration/security/users/users.helper';
import { CaseAreasHelper } from '../../../../page-objects/pages/administration/service-center/case-areas-page/case-areas.helper';
import { KnowledgeBaseHelper } from '../../../../page-objects/pages/administration/service-center/knowledge-base/knowledge-base.helper';
import { TicketCategoriesHelper } from '../../../../page-objects/pages/administration/service-center/ticket-categories/ticket-categories.helper';
import { ApplicationStatusHelper } from '../../../../page-objects/pages/administration/system/application-status/application-status.helper';
import { ProcessingLogHelper } from '../../../../page-objects/pages/administration/system/processing-log/processing-log.helper';
import { SessionsHelper } from '../../../../page-objects/pages/administration/system/sessions/sessions.helper';
import { UnmatchedHelper } from '../../../../page-objects/pages/administration/system/unmatched/unmatched.helper';
import { HomePageOneHelper } from '../../../../page-objects/pages/home-page/home-page-one.helper';
import { HomePageHelper } from '../../../../page-objects/pages/home-page/home-page.helper';
import { HomePage1Helper } from '../../../../page-objects/pages/home-page/home-page1.helper';
import { LoginPageHelper } from '../../../../page-objects/pages/login-page/login-page.helper';
import { MyProfilePageHelper } from '../../../../page-objects/pages/my-profile/my-profile.helper';
import { SuiteNames } from '../../../helpers/suite-names';

describe(SuiteNames.regressionSuite, () => {
    let loginPageHelper: LoginPageHelper;

    beforeAll(async () => {
        loginPageHelper = LoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
    });

    beforeEach(async () => {
        await PageHelper.restartBrowser();
        await loginPageHelper.goTo();
        await LoginPageHelper.loginAsAdmin();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see the Sign off option properly - [22412630]', async () => {
        // Auto generated by aurea-automation - util on Wed, 22 May 2019 15:13:23 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412630;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Check the Sign Off button under the main menu.');
        StepLogger.verification('Should display the Sign Off button properly.');
        await HomePageOneHelper.verifySignOffButtonDisplayed();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see My Profile screen - [22412629]', async () => {
        // Auto generated by aurea-automation - util on Wed, 22 May 2019 15:13:57 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412629;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Click on My Profiles button under the main menu.');
        await HomePageOneHelper.clickMyProfile();
        StepLogger.verification('Should display My Profile screen in a new tab properly.');
        await MyProfilePageHelper.verifyNewCasePageDisplayed(false);
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see Unmatched screen under the System sub-menu - [22412628]', async () => {
        // Auto generated by aurea-automation - util on Wed, 22 May 2019 15:14:17 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412628;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Click on Unmatched button under the System sub-menu.');
        await HomePageHelper.clickAdministrationLink();
        await HomePage1Helper.clickSystemUnderAdministration();
        await HomePageOneHelper.clickUnmatched();
        StepLogger.verification('Should display the Unmatched screen properly.');
        await UnmatchedHelper.verifyUnmatchedPageDisplayed();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see Sessions screen under the System sub-menu - [22412626]', async () => {
        // Auto generated by aurea-automation - util on Wed, 22 May 2019 15:14:41 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412626;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Click on Sessions button under the System sub-menu.');
        await HomePageHelper.clickAdministrationLink();
        await HomePage1Helper.clickSystemUnderAdministration();
        await HomePage1Helper.clickSessionUnderAdministration();
        StepLogger.verification('Should display the Sessions screen properly.');
        await SessionsHelper.verifySessionsPageDisplayed();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see Processing Log screen under the System sub-menu - [22412625]', async () => {
        // Auto generated by aurea-automation - util on Wed, 22 May 2019 15:15:00 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412625;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Click on Processing Log button under the System sub-menu.');
        await HomePageHelper.clickAdministrationLink();
        await HomePage1Helper.clickSystemUnderAdministration();
        await HomePage1Helper.clickProcessingLog(false);
        StepLogger.verification('Should display the Processing Log screen properly.');
        await ProcessingLogHelper.verifyProcessingLogPageDisplayed();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see Application Status screen under the System sub-menu - [22412624]', async () => {
        // Auto generated by aurea-automation - util on Wed, 22 May 2019 15:15:23 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412624;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Click on Application Status button under the System sub-menu.');
        await HomePageHelper.clickAdministrationLink();
        await HomePage1Helper.navigateSystemApplicationStatus();
        StepLogger.verification('Should display the Application Status screen properly.');
        await ApplicationStatusHelper.verifyApplicationStatusPageDisplayed();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see Ticket Categories screen under Service Center the sub-menu - [22412622]', async () => {
        // Auto generated by aurea-automation - util on Wed, 22 May 2019 15:15:42 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412622;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Click on Ticket Categories button under the Service Center sub-menu.');
        await HomePageHelper.clickAdministrationLink();
        await HomePageHelper.clickServiceCenterUnderAdministration();
        await HomePageHelper.clickTicketCategoriesUnderServiceCenterUnderAdministration();
        StepLogger.verification('Should display the Ticket Categories screen properly.');
        await TicketCategoriesHelper.verifyTicketCategoriesPageDisplayed();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see Knowledge Base screen under the Service Center sub-menu - [22412621]', async () => {
        // Auto generated by aurea-automation - util on Wed, 22 May 2019 15:16:05 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412621;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Click on Knowledge Base button under the Service Center sub-menu.');
        await HomePageHelper.clickAdministrationLink();
        await HomePageHelper.clickServiceCenterUnderAdministration();
        await HomePageHelper.clickKnowledgeBaseUnderServiceCenterUnderAdministration();
        StepLogger.verification('Should display the Knowledge Base screen properly.');
        await KnowledgeBaseHelper.verifyKnowledgeBasePageDisplayed();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see Case Areas screen under the Service Center sub-menu - [22412620]', async () => {
        // Auto generated by aurea-automation - util on Wed, 22 May 2019 15:16:31 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412620;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Click on Case Areas button under the Service Center sub-menu.');
        await HomePageHelper.clickAdministrationLink();
        await HomePageHelper.clickServiceCenterUnderAdministration();
        await HomePageHelper.clickCaseAreasUnderServiceCenterUnderAdministration();
        StepLogger.verification('Should display the Case Areas screen properly.');
        await CaseAreasHelper.verifyCaseAreasPageDisplayed();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see Users screen under the sub-menu Security - [22412619]', async () => {
        // Auto generated by aurea-automation - util on Wed, 22 May 2019 15:16:50 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412619;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Click on Users button under the Security sub-menu.');
        await HomePageHelper.clickAdministrationLink();
        await HomePage1Helper.clickSecurityCenterUnderAdministration();
        await HomePage1Helper.clickOnUser();
        StepLogger.verification('Should display the Users screen properly.');
        await UsersHelper.verifyUsersPageDisplayed();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see Roles screen under the sub-menu Security - [22412618]', async () => {
        // Auto generated by aurea-automation - util on Fri, 24 May 2019 10:41:41 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412618;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Click on Roles button under the Security sub-menu.');
        await HomePageHelper.clickAdministrationLink();
        await HomePage1Helper.clickSecurityCenterUnderAdministration();
        await HomePageOneHelper.clickOnRolesUnderSecuritySubmenuUnderAdministrationMenu();
        StepLogger.verification('Should display the Roles screen properly.');
        await RolesHelper.verifyRolesPageDisplayed();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see Links screen under the sub-menu Resources - [22412617]', async () => {
        // Auto generated by aurea-automation - util on Fri, 24 May 2019 10:42:10 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412617;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Click on Links button under the Resources sub-menu.');
        await HomePageHelper.clickAdministrationLink();
        await HomePageOneHelper.clickResourcesUnderAdministrationMenu();
        await HomePageOneHelper.clickLinksButtonUnderResourcesSubmenuUnderAdministrationMenu();
        StepLogger.verification('Should display the Links screen properly.');
        await LinksHelper.verifyLinksPageDisplayed();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see Documents screen under the sub-menu Resources - [22412616]', async () => {
        // Auto generated by aurea-automation - util on Fri, 24 May 2019 10:42:02 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412616;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Click on Documents button under the Resources sub-menu.');
        await HomePageHelper.clickAdministrationLink();
        await HomePageOneHelper.clickResourcesUnderAdministrationMenu();
        await HomePageOneHelper.clickDocumentsButtonUnderResourcesSubmenuUnderAdministrationMenu();
        StepLogger.verification('Should display the Documents screen properly.');
        await DocumentsHelper.verifyDocumentsPageDisplayed();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see Regions screen under the sub-menu Organization - [22412615]', async () => {
        // Auto generated by aurea-automation - util on Fri, 24 May 2019 10:42:14 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412615;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Click on Regions button under the Organizations sub-menu.');
        await HomePageHelper.clickAdministrationLink();
        await HomePageHelper.clickOrganizationUnderAdministration();
        await HomePage1Helper.clickRegionsUnderOrganization();
        StepLogger.verification('Should display the Regions screen properly.');
        await RegionsHelper.verifyManageRegionsPageDisplayed();
    });

    // Jira References - COTRAC-88
    it('Verify if user shall be able to see Districts screen under the sub-menu Organization - [22412613]', async () => {
        // Auto generated by aurea-automation - util on Fri, 24 May 2019 10:42:59 GMT

        // Step-1,2 & 3 are verified as part of the prerequisite in beforeEach method
        StepLogger.caseId = 22412613;
        StepLogger.stepId(1);
        StepLogger.step('Goto URL : http://ct-allinone-qa.coretrac.dev.avolin.com/ResourceOne/App/index.html#login');
        StepLogger.verification('User should be able to navigate to the login page.');

        StepLogger.stepId(2);
        StepLogger.step('Enter username: r1adminpassword : editipt');
        StepLogger.verification('User should be able to enter the data.');

        StepLogger.stepId(3);
        StepLogger.step('Click "Sign in".');
        StepLogger.verification('User should be able to login successfully.');

        StepLogger.stepId(4);
        StepLogger.step('Click on Districts button under the Organizations sub-menu.');
        await HomePageHelper.clickAdministrationLink();
        await HomePageHelper.clickOrganizationUnderAdministration();
        await HomePage1Helper.clickDistrictsUnderOrganization();
        StepLogger.verification('Should display the Districts screen properly.');
        await DistrictsHelper.verifyManageDistrictsPageDisplayed();
    });
});
